### ISSUE TITLE
Support 1.19

### ISSUE THREAD

**Issue by amalon** [PrismarineJS/node-minecraft-protocol#1011]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.34
 - server: vanilla/spigot/paper: N/A
 - node: 18.3.0-1

## Detailed description of a problem
https://github.com/vincss/mcsleepingserverstarter/issues/101
When a Minecraft JE 1.19 client attempts to connect to mcsleepingserverstarter, it gets a message in the log about `Chunk size is XXX but only Y was read` as in the above bug report, and the client says:
```
Failed to connect to the server
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(25) + length(1) exceeds writerIndex(25): PooledUnsafeDirectByteBuf(ridx: 25, widx: 25, cap: 25)
```

Please can 1.19 protocol support be added?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/issues/575

**Comment by rom1504** [comment]
done
