### ISSUE TITLE
Impossible to login with an other account with msal

### ISSUE THREAD

**Issue by leopoldhub** [PrismarineJS/node-minecraft-protocol#1031]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.31.0
 - node: 16.15.1

## Detailed description of a problem
I cant connect with an other account once I connect with msal.
If I change the account email, minecraft-protocol uses my previous account token to connect.
I tried to clean npm cache without success

**Comment by leopoldhub** [comment]
Ok, I found the solution, I needed to delete the "nmp-cache" in my ".minecraft" folder.
However, the problem still exists, it is impossible to switch account without manualy deleting the cache... do you think this feature could be added?

**Comment by extremeheat** [comment]
If you want to use a different account you need to use a different username as explained in the documentation

**Comment by leopoldhub** [comment]
> If you want to use a different account you need to use a different username as explained in the documentation

So changing the mail is not sufficient?

**Comment by U5B** [comment]
> > If you want to use a different account you need to use a different username as explained in the documentation
> 
> So changing the mail is not sufficient?

Correct, the username should be changed too.
The username is used as an identifier internally for Minecraft's tokens.
