### ISSUE TITLE
1.19.1-1.19.3

### ISSUE THREAD

**Issue by PandaUprising** [PrismarineJS/node-minecraft-protocol#1037]
Support for 1.19.1-1.19.2

Any updates on this issue? no pressure or anything just wondering where your at with it!

Thank you, PandaUprising

**Comment by extremeheat** [comment]
Feel free to work on it, I don’t believe anyone is actively working on 1.19.1/2 so far.

**Comment by PandaUprising** [comment]
It would be interesting if another plugin E.g. ViaVersion could help with this or smth

**Comment by PandaUprising** [comment]
> Feel free to work on it, I don’t believe anyone is actively working on 1.19.1/2 so far.

What would I do to add support for these versions?

**Comment by extremeheat** [comment]
Review the Minecraft Java code diff between 1.19 and 1.19.1 then implement them here

https://github.com/extremeheat/extracted_mcauthlib/pull/1/files

Mainly chat changes

**Comment by PandaUprising** [comment]
> Review the Minecraft Java code diff between 1.19 and 1.19.1 then implement them here
> 
> https://github.com/extremeheat/extracted_minecraft_data/pull/1/files
> 
> https://github.com/extremeheat/extracted_mcauthlib/pull/1/files
> 
> Mainly chat changes

Ok cool, will have a look at that!

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-data/issues/643

**Comment by rom1504** [comment]
let's jump straight to 1.19.2 imo

**Comment by rom1504** [comment]
https://wiki.vg/index.php?title=Protocol&action=history

**Comment by rom1504** [comment]
https://github.com/extremeheat/extracted_minecraft_data/pull/1

**Comment by rom1504** [comment]
https://github.com/extremeheat/extracted_minecraft_data/pull/1/files#diff-cfc7f62190ac809b821fb45202a01f8de05f0c3081bd1e6350c6718f53b8692aR809

**Comment by rom1504** [comment]
https://github.com/extremeheat/extracted_minecraft_data/pull/1/files#diff-34a0b417dd277e6028b09a69130946df06fe14d800c4f80d6e09a32b030d78aeR12

**Comment by rom1504** [comment]
lot of chat stuff changed

**Comment by Shorent** [comment]
I'm not super familiar with this project and would like to help, in your opinion what in node-minecraft-protocol most likely needs to change to fit the new minecraft protocol? Just wondering where I should look first.

I'd love to help 1.19.2 mineflayer going

**Comment by rom1504** [comment]
only https://github.com/PrismarineJS/minecraft-data/issues/643
copying protocol.json from 1.19 in 1.19.2 folder
then making the right changes

**Comment by Fruce** [comment]
> Support for 1.19.1-1.19.2
> 
> Any updates on this issue? no pressure or anything just wondering where your at with it!
> 
> Thank you, PandaUprising

YES! please please make it happen!!!!

**Comment by Fruce** [comment]
Need 1.19.1 and 1.19.2 support asap !

**Comment by s-bauer** [comment]
> Need 1.19.1 and 1.19.2 support asap !

You're not in a position to demand anything. This is open-source. Implement it yourself or wait till someone else does the work for you - for free!

**Comment by Kreyren** [comment]
> Need 1.19.1 and 1.19.2 support asap ! -- @Fruce (https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037#issuecomment-1294575602)

If this is in a production environment then consider hiring a developer to fix it if you are not qualified to do that yourself or submit a bug bounty through e.g. https://issuehunt.io or https://github.com/sponsors/PrismarineJS.

In terms of the amount of bug bountry consider minimal wage per hour and the amount of development hours it will take to solve the issue.

> You're not in a position to demand anything. This is open-source -- @s-bauer (https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037#issuecomment-1305858521)

You sound like an annoying child when you make this painfully incompetent excuse, shush and be responsible for the code you write.

**Comment by BasToTheMax** [comment]
How can we implement 1.19(.2)?
What changes need to be made?

**Comment by rom1504** [comment]
See the open PR on the topic. The chat need to be changed.

Feel free to discuss at #contribute in discord

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/1046 next step is this

**Comment by PandaUprising** [comment]
And now comes 1.19.3...

**Comment by TinyDerp** [comment]
Any news on 1.19.3?

**Comment by rom1504** [comment]
blocked by https://github.com/PrismarineJS/node-minecraft-protocol/issues/1046 ; please read

**Comment by DanielRamosAcosta** [comment]
Now that #1046 has been merged, what would be the next steps? Anything that we could help @rom1504?

**Comment by sebasdt** [comment]
hey, What is the progress on 1.19.3? I saw in the latest update 1.19.3 is supported, is this correct?

**Comment by Prosciuttino** [comment]
> hey, What is the progress on 1.19.3? I saw in the latest update 1.19.3 is supported, is this correct?

not yet

**Comment by rom1504** [comment]
It's done

Mineflayer PR still open
