### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by MelonHell** [PrismarineJS/node-minecraft-protocol#1097]

**Comment by Anadinnn** [comment]
So when could we expect 1.19.4 to be supported?

**Comment by kerkkoh** [comment]
Would love to see 1.19.4 support. `minecraft-data` seems to have a PR open for 1.19.4 support already https://github.com/PrismarineJS/minecraft-data/pull/700, but from the looks of it a lot of projects ultimately depend on this package specifically.

**Comment by rom1504** [comment]
mcdata pr doesn't have protocol json updates

**Comment by TFBosoN** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/703 protocol partially updated if someone wants to finish it.. my skills are too low for that unfortunately

**Comment by Maks-gaming** [comment]
can be closed as completed?

**Comment by rom1504** [comment]
Yes
