### ISSUE TITLE
player text question

### ISSUE THREAD

**Issue by antonqpl** [PrismarineJS/node-minecraft-protocol#1104]
is it possible to change players to look like that ![image](https://user-images.githubusercontent.com/99998467/236689426-09c4396a-bf78-4017-a8a3-6329bfdf37b1.png), not like ![image](https://user-images.githubusercontent.com/99998467/236689444-59cd8c9a-4f95-48b6-8e12-10fa3328f539.png)?

**Comment by rom1504** [comment]
yes
