### ISSUE TITLE
What to do with writeRaw/readRaw in 1.8

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#113]
/summon @deathcap : this is mostly a question for you

The way WriteRaw and ReadRaw currently work, they can easily be misused, and they can very easily break at each new version of the protocol. This makes it very annoying to update.

So instead of just taking the buffer and naively writing it to the socket, I thought it'd be smarter to how make writeraw's buffer only contain packetId+data. writeRaw would then do the magic of appending the correct length/dataLength combo, compressing the buffer, encrypting the buffer, doing a voodoo dance around it and sacrifice a :sheep:.

Similarely, readRaw could return a buffer containing only the decompressed/decrypted packet with just packetId and the data (length of the packet can be checked with buffer.length). 

Would this suit your needs ?

**Comment by deathcap** [comment]
:+1: sounds good to me. The purpose of writeRaw as I see it is to avoid having to encode/decode the packet structure, so accepting a buffer containing packetId+data, then having it compress/encrypt for you would satisfy these requirements.

**Comment by roblabla** [comment]
Cool. I'll add this soon. BTW, you should join the gitter, lots of stuff happening. 

Also, the ursa-compatible wrapper is now on npm, http://npmjs.com/package/ursa-purejs
