### ISSUE TITLE
Use node-yggdrasil module

### ISSUE THREAD

**Issue by wtfaremyinitials** [PrismarineJS/node-minecraft-protocol#117]
Instead of using our own yggdrasil module, it would make more sense to use an external module. node-yggdrasil is perfectly fit for this.

**Comment by wtfaremyinitials** [comment]
https://github.com/wtfaremyinitials/prismarine-yggdrasil

**Comment by roblabla** [comment]
PrismarineJS/prismarine-yggdrasil#2 it'd be a good idea to not reinvent the wheel and use the existing node-yggdrasil module.

**Comment by wtfaremyinitials** [comment]
So you're changing your mind about your implementation of yggdrasil being better? :stuck_out_tongue:  @roblabla

**Comment by roblabla** [comment]
I don't remember claiming my implementation is better :| .

**Comment by wtfaremyinitials** [comment]
When we first brought this up your initial reaction was you'd rather continue using the one we already have :3

I don't really want to scroll that far up Gitter, though.

**Comment by roblabla** [comment]
My initial reaction was that the module was years old, had no documentation, and wasn't under our control as far as the repository is concerned. But if the original author of the original module is still active on github and willing to accept PRs that fix bugs and whatnot, then I have no problems with using it :P

**Comment by wtfaremyinitials** [comment]
Works for me

**Comment by roblabla** [comment]
Dependant on zekesonxx/node-yggdrasil#1 and zekesonxx/node-yggdrasil#2.

Most of the code necessary to move on is ready.

**Comment by rom1504** [comment]
How does this relate to https://github.com/thechunknetwork/mojang-api ?

It would be nice to have a module that handle both mojang APIs entirely and then to use that in node-minecraft-protocol

**Comment by rom1504** [comment]
This is done.
