### ISSUE TITLE
The read/write/sizeOf interface

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#121]
Currently, there is a very major problem in the read/write/sizeOf functions of the internal binary parser. Their return values are modeled around 1.6 assumptions that do not hold true anymore. For instance, returning null if there is not enough data, even though since 1.7, not having enough data means there was an error in what the client sent, or an error in the protocol file.

Most importantly, read returns not just the read value, but the read size. This leads to an incredibly convoluted API. Write and sizeOf has less problems.

I think it would be in our best interest to rethink the read interface, lest we let the maintainers go :dizzy_face: !

It might also be a good idea to split the serializer into different files, similar to what is done in roblabla/Protocols

**Comment by rom1504** [comment]
splitting into different files is done.

**Comment by rom1504** [comment]
On that theme : would it make sense to regroup read/write/sizeOf in classes ?
Instead of having something like 
```js
'varint': [readVarInt, writeVarInt, sizeOfVarInt]

function readVarInt(buffer, offset) {

}

function sizeOfVarInt(value) {

}

function writeVarInt(value, buffer, offset) {

}
```

having 

```js
'varint': varint

class varint
{
  function read(buffer, offset) {

  }

  function sizeOf(value) {

  }

  function write(value, buffer, offset) {

  }
}
```

That doesn't change much functionally but I think it could be cleaner that repeating the name of the type again and again.

**Comment by rom1504** [comment]
"read returns not just the read value, but the read size" don't we need the size ?

**Comment by roblabla** [comment]
Not if the cursor is kept on the buffer object.

**Comment by rom1504** [comment]
I don't know what you mean by "polling interface" and "pushing interface"

**Comment by roblabla** [comment]
pushing interface : we are made aware of new data, we react to it.
polling interface : we wait until more data is made available to us.

pushing is on('data')
polling is a "blocking" read()

**Comment by rom1504** [comment]
Aren't node stream only implemantable with a pushing approach?

**Comment by roblabla** [comment]
@rom1504 we can layer a small compatibility shim to get pulling api on top of pushing api without much pain.

**Comment by rom1504** [comment]
see https://github.com/roblabla/ProtoDef/issues/24 for ideas about improving that interface but doing it asyncly makes things complicated and slow

I'd like to get rid of the offset handling, and make it "automatically handled", which can be done without going async.

Leaving this open, but this isn't really a priority anymore.

**Comment by rom1504** [comment]
tracking of that issue moved to https://github.com/roblabla/ProtoDef/issues/49
