### ISSUE TITLE
Move each examples into its own directory with its own package.json

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#122]
Some example require extra dependencies (client_chat, for instance, requires ansi-color), which adds useless bloat to the package. It might be a good idea to move those examples into their own folder, with their own package.json, in order to avoid that clutter.

**Comment by deathcap** [comment]
Alternatively you could move them into their own directories, with their own package.json files (I did this in a few voxel.js examples to solve the same problem, avoiding `npm install` at the top level from unnecessarily pulling in everything); the advantage of keeping in the same repo is the examples can be more easily kept in sync

**Comment by wtfaremyinitials** [comment]
@deathcap I think that may be the best solution

**Comment by wtfaremyinitials** [comment]
Tons of schoolwork, I can probably get to finishing it in either a couple hours or a couple days, depending.

**Comment by roblabla** [comment]
There's no real rush on getting this fixed, take your time ;)
