### ISSUE TITLE
Investigate the slow connection time

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#123]
For some reason, connection time is horrendously slow (between 8-10 seconds), even with native URSA. There are multiple sources of slowness :

- The DNS lookup may take up to 4 seconds on my machine to fail to resolve
- The requests to mojang may take up to 2-3 seconds each
- The js RSA implementation is slow (fixed by using URSA, sorta).
- Sometimes generating random numbers can be slow.

We should profile the login time of node-minecraft-protocol to identify and fix the potential bottlenecks.

**Comment by JavaPortals** [comment]
Is the latest changes pushed to the repo so I can help test it?

**Comment by roblabla** [comment]
I'm about to push my changes on #108, and probably land the PR since it's pretty much done.

**Comment by JavaPortals** [comment]
Alright. Just tag me if you want me to test it out.

**Comment by zuazo** [comment]
Hey guys, I do not notice any connection slowdown using the current master code. Are you sure it's not your connection?

**Comment by roblabla** [comment]
create an offline minecraft_server.jar, login using notchian client and then try with node-minecraft-protocol's client. At least on my computer, node-minecraft-protocol appears to be much slower.

**Comment by zuazo** [comment]
Testing current master with vanilla `1.8.3` local server in offline mode inside a Debian machine (client and server):

```ruby
#  cat client_helloworld.js 
var mc = require('minecraft-protocol');

var client = mc.createClient({
  host: '127.0.0.1',
  username: 'client001'
});
client.on('login', function() {
  console.info("I'm in!");
  client.write('chat', { message: 'Pachamama!' });
});
client.on('chat', function(username, message) {
  console.info('bye bye my friend!');
  client.end('disconnect.quitting');
});
```

Connection time seems fast to me:

```
$ time node client_helloworld.js 
I'm in!
bye bye my friend!

real    0m0.302s
user    0m0.080s
sys     0m0.008s
```

I don't know. Maybe this only affects Windows, OS X or some specific platform?

**Comment by roblabla** [comment]
I use a linux server for my tests, (only running notchian client on windows),so I don't think so. What about online-mode connection time ? I'll do some timings of mine when I have a moment.

**Comment by zuazo** [comment]
It takes 1-2 seconds to connect using online mode. It seems similar to the vanilla client.

```
$ time node client_helloworld_online.js 
I'm in!
bye bye my friend!

real    0m1.751s
user    0m0.108s
sys     0m0.016s
$ time node client_helloworld_online.js 
I'm in!
bye bye my friend!

real    0m1.675s
user    0m0.124s
sys     0m0.000s
$ time node client_helloworld_online.js 
I'm in!
bye bye my friend!

real    0m1.552s
user    0m0.112s
sys     0m0.008s
```

**Comment by deathcap** [comment]
Maybe related to IPv6? (random guess. I see FML disables IPv6 at startup, presumably for faster connections)

**Comment by roblabla** [comment]
Closing this, it was due to my dns not being set up properly.
