### ISSUE TITLE
1.20 & 1.20.1 Support

### ISSUE THREAD

**Issue by TheDevMinerTV** [PrismarineJS/node-minecraft-protocol#1230]
**Is your feature request related to a problem? Please describe.**

Please support Minecraft: Java Edition 1.20.

**Describe the solution you'd like**

Support Minecraft: Java Edition 1.20.

**Describe alternatives you've considered**

**Additional context**

**Comment by TheDevMinerTV** [comment]
Depends on https://github.com/PrismarineJS/minecraft-data/issues/711

**Comment by rom1504** [comment]
Done
