### ISSUE TITLE
Still disconnects when using node-minecraft-protocol/blob/master/examples/proxy/proxy.js

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/node-minecraft-protocol#1242]
[ +] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.43.2
 - minecraft-data: 3.40.0
 - server: vanilla 1.20.1
 - client: oficial vanilla 1.20.1
 - node: 18.16.1

## Detailed description of a problem
Still disconnects when using node-minecraft-protocol/blob/master/examples/proxy/proxy.js. In some cases, without error output in the proxy console. This happens when you interact with aggressive mobs (I think when the mob hits me or when I hit the mob). Also noticed lags when shooting from a bow. Sometimes the arrow does not fly out of the bow, but after a few seconds it appears already in the target.

## Expected behavior
no disconnect

#### session 1 (punch on a villager, then immediately disconnect me)
video: https://youtu.be/M0ok5kB2Dno
log: [session.01.txt](https://github.com/PrismarineJS/node-minecraft-protocol/files/12095056/session.01.txt)
in console:
```
Chunk size is 63 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400217f000d003100390032002e003100360038002e0031002e003100360033000063de
client.connect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
Disconnecting client because error Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Framer.ondata (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/readable-stream/lib/internal/streams/readable.js:662:22)
    at Framer.emit (node:events:513:28)
    at addChunk (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/readable-stream/lib/internal/streams/readable.js:278:12) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
client.disconnect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
```

#### session 2 (the skeleton hit me with an arrow, then immediately disconnect me)
video: https://youtu.be/ai3rL5FEPaE
log: [session.02.txt](https://github.com/PrismarineJS/node-minecraft-protocol/files/12095138/session.02.txt)
in console:
```
client.connect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
client.disconnect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
```

#### session 3 (zobi beats me with a shovel, then immediately disconnect me)
video: https://youtu.be/8ybl0VyZKs0
log: [session.03.txt](https://github.com/PrismarineJS/node-minecraft-protocol/files/12095258/session.03.txt)
in console:
```
client.connect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
client.disconnect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
```

#### session 4 (shooting zombies with a bow, then immediately disconnect me)
video: https://youtu.be/Lvbz4auqZ7o
log: [session.04.txt](https://github.com/PrismarineJS/node-minecraft-protocol/files/12095281/session.04.txt)
in console:
```
client.connect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
Disconnecting client because error Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
client.disconnect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
```

#### session 5 (lags when archery)
video: https://youtu.be/OyE-j0AAZxs
log: [session.05.txt](https://github.com/PrismarineJS/node-minecraft-protocol/files/12095400/session.05.txt)
in console:
```
client.connect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
client.disconnect Olympiar 798330cf-4512-33ec-9512-eed5d3bdf870
```

**Comment by lastuniverse** [comment]
still this error appears
```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/utils.js:70:5)
    at Object.readBool [as bool] (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/datatypes/utils.js:133:41)
    at eval (eval at compile (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2966:29)
    at Object.packet_damage_event (eval at compile (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2972:9)
    at eval (eval at compile (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:258:12), <anonymous>:3011:64)
    at packet (eval at compile (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:258:12), <anonymous>:3100:9)
    at CompiledProtodef.read (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/home/roman/work/minecraft_advanced_proxy/proxy/node_modules/protodef/src/utils.js:50:16)

```

**Comment by lastuniverse** [comment]
Thank you very much for your response. Looking forward to fixes.

**Comment by PondWader** [comment]
> Thank you very much for your response. Looking forward to fixes.

You can update now to the latest unreleased mc data by doing:
```
cd node_modules/minecraft-data
rm -rf minecraft-data
git clone https://github.com/prismarinejs/minecraft-data
```
And see if that fixes your issues.

**Comment by lastuniverse** [comment]
Thanks a lot, I'll post the results

**Comment by lastuniverse** [comment]
There is no more crash due to damage (no error, no disconnect). But there is a strange disconnect in the following situation.
In the server settings, spawning of mobs, npc and monsters is disabled. Connected to the server through a proxy. Spawn zombies with the `/summon ...` command. Visually, nothing happens, no zombies appear. After a dozen seconds, a disconnect occurs or a zombie appears, which has been running after me for a long time. With the disconnect option, there are no errors in the proxy console, there is only a message
`client.disconnect {myNick} {myUUID}`

**Comment by lastuniverse** [comment]
There is a suspicion that this is not directly related to the mobs. Periodically, there are many situations when it seems that packets from the server do not reach the client and vice versa. Feeling as if the network is lag. This usually ends with a disconnect, within a few tens of seconds. When I restart, I often find that the actions performed before the disconnect were not applied.

In justification, I will say that I have a powerful processor, 64 gigabytes of RAM, the server, proxy and client communicate with each other via localhost. Moreover, if you go directly (not through a proxy), such situations do not arise.

I think that the reason is in the internal data processing mechanisms inside the proxy. Perhaps it hangs on some of the packets transmitted between the server and the client, but so far it has not been possible to calculate on which ones.

**Comment by lastuniverse** [comment]
Here is an example of how it happens
https://youtu.be/HIMi-PWQucc

**Comment by PondWader** [comment]
This may be happening due to proxying of the `bundle_delimiter` packet which can result in the client getting stuck, as it witholds packets but for some reason the packets do not get released correctly. I suspect this is due to how NMP handles the bundle delimiter internally whilst also emitting it.

You could try filtering out the `bundle_delimiter` packet, as a packet not to proxy and that issue will probably stop.

This is something I may look in to.

**Comment by PondWader** [comment]
Ah yes, I see the problem with NMP, I'll PR a fix tomorrow.

**Comment by lastuniverse** [comment]
Thank you very much for your help.

**Comment by lastuniverse** [comment]
Filtered out the bundle delimiter. 
`if (meta.name === "bundle_delimiter") return;`

The proxy has been working without failure for half an hour. I'll leave it until the morning, if it doesn't disconnect or disconnect, I'll unsubscribe. Thank you for your help!

**Comment by lastuniverse** [comment]
I caught a nodejs crash in the morning (a process with a proxy) due to out of memory.
I will observe where exactly the memory is leaking and unsubscribe as I find out

**Comment by lastuniverse** [comment]
Thank you very much, now everything works flawlessly.
