### ISSUE TITLE
Error: Cannot find module './dist/index.js'

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#125]
Since the merge of https://github.com/PrismarineJS/node-minecraft-protocol/pull/115, `require('minecraft-protocol')` fails for me with:

```
> require('minecraft-protocol')
Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (node-minecraft-protocol/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I ran `npm install` in the node-minecraft-protocol directory but it only outputs a few warnings, no errors:

```
node-minecraft-protocol $ npm install
npm WARN package.json batch@0.3.2 No repository field.
npm WARN package.json ansi-color@0.2.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field
```

if I revert 439c240247faedbbde46849d6be9a3f8721e3b6a, then the require() succeeds.

I am not familiar with server-side build processes but best I can tell this has to do with gulp, which seems to be supposed to generate ./dist/index.js. If so should a shell command to invoke gulp be added to the package.json install script or what?

**Comment by wtfaremyinitials** [comment]
If you npm install the module, the compiled version will be included. To build it yourself, run `npm install -g gulp && gulp` in the root of node-minecraft-protocol

**Comment by deathcap** [comment]
Thanks, if I run `npm install -g gulp && gulp` then it does create the compiled `dist` files as expected. 

Could this step be documented somewhere? (not obvious for someone who hasn't ever used gulp)

**Comment by wtfaremyinitials** [comment]
I figured most people would be downloading from npm, not git, so I didn't originally bother. I'll send a PR later that prints out a helpful error when dist/index.js isn't found

**Comment by roblabla** [comment]
Right, so I'm going to assume you used the github url as a dependency link, instead of the published package. I just tried adding a prepublish hook in hope that it would fix the problem, but npm doesn't run the prepublish hook from github links (only from local installation and before publishing)... npm/npm#3856     

After invistigations, there is a relatively clever hack that can be used to make everybody happy :

- npm prepublish: compile es6, remove scripts.postinstall from package.json.
- npm postpublish: bring back scripts.postinstall to package.json.
- npm postinstall: compile es6 (only done for git users).

**Comment by roblabla** [comment]
Thinking further about it, scratch what I said before. Adding the prepublish is a step in the good direction, and whenever npm closes issue 3055, it will fix the problem entirely. In the meantime, going inside minecraft-protocol and running `npm install <noarg>` will be necessary. I'm sending a PR to bring the prepublish script in.

**Comment by roblabla** [comment]
https://github.com/npm/npm/pull/7627 there's a PR for npm that fixes our issue :smile_cat: ! Let's hope it gets merged soon.

**Comment by deathcap** [comment]
So prepublish is supposed to run to populate `dist` in the tarball for download? With 0.13.1 (first release with GH-115) not seeing it:

```
tmp $ npm install minecraft-protocol
 
> ursa@0.8.4 install /private/tmp/node_modules/minecraft-protocol/node_modules/ursa
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  CXX(target) Release/obj.target/ursaNative/src/asprintf.o
  SOLINK_MODULE(target) Release/ursaNative.node
  SOLINK_MODULE(target) Release/ursaNative.node: Finished
minecraft-protocol@0.13.1 node_modules/minecraft-protocol
├── buffer-equal@0.0.0
├── ansi-color@0.2.1
├── node-uuid@1.4.3
├── prismarine-nbt@0.0.1 (node-int64@0.3.3)
├── superagent@0.10.0 (methods@0.0.1, cookiejar@1.3.0, emitter-component@0.0.6, mime@1.2.5, qs@0.5.2, formidable@1.0.9, better-assert@0.1.0)
├── ursa-purejs@0.0.1 (node-rsa@0.2.23)
└── ursa@0.8.4 (bindings@1.2.1, nan@1.7.0)
tmp $ node
> require('minecraft-protocol')
Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/tmp/node_modules/minecraft-protocol/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
> 
```

`src` is present in the .tgz but not `dist`:

```
Downloads $ curl http://registry.npmjs.org/minecraft-protocol/-/minecraft-protocol-0.13.1.tgz | tar -tpzf -
package/.npmignore
package/README.md
package/browser.js
package/gulpfile.js
package/index.js
package/examples/client_chat.js
package/examples/client_echo.js
package/examples/proxy.js
package/examples/server.js
package/examples/server_helloworld.js
package/.editorconfig
package/.jshintrc
package/circle.yml
package/src/client.js
package/src/ping.js
package/src/protocol.js
package/src/server.js
package/src/yggdrasil.js
package/test/benchmark.js
package/test/test.js
```

if I `cd node_modules/minecraft-protocol ; npm install` then it does create `dist`, but not from a top-level `npm install minecraft-protocol`

**Comment by roblabla** [comment]
Yeah, just realized I screwed up. I need to add an empty .npmignore so that dist is published on npm. :tired_face: .

**Comment by roblabla** [comment]
Alright, 7416ea7e4c21b362ea93d7bbd90c6d60aef7f074 fixed it.

**Comment by deathcap** [comment]
```
tmp $ npm install minecraft-protocol
minecraft-protocol@0.13.2 node_modules/minecraft-protocol
tmp $ node
> require('minecraft-protocol')
{ createClient: [Function: createClient],
…
```

0.13.2 works great, thanks! I'm fine with closing this (unless you want to keep it open for https://github.com/npm/npm/pull/7627, but I'm at least no longer hitting it in my normal workflow using `npm link`)
