### ISSUE TITLE
Problems with Deserializer

### ISSUE THREAD

**Issue by XaviscoB** [PrismarineJS/node-minecraft-protocol#1308]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.47.0
 - server: Paper 1.8.9
 - node: 20.15.0

## Detailed description of a problem
I'm trying to read the raw packets sent by the connection socket using the Deserializer provided by the lib following the [example](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/compiler_parse_buffer/index.js) but it's not going according to plan, I'm not sure if my application is correct or if it's a problem with the Deserializer itself

## Current code
```js
const { createDeserializer, states } = require('minecraft-protocol')
const deserializer = createDeserializer({ state: states.STATUS, version: '1.8.9', isServer: false})

function convertBufferToObject (buffer) {
  return deserializer.parsePacketBuffer(buffer)
}

// ...
clientSocket.on('data', (data) => {
        console.log(convertBufferToObject(data))
        serverSocket.write(data)
 });
```

## Expected behavior
I expected to receive the packet decoded and already partitioned, as is expected when we pull the event packet when creating a Client using the Minecraft Protocol

## Additional context
![image](https://github.com/PrismarineJS/node-minecraft-protocol/assets/130815183/2e3291a3-efa2-4b9a-9234-aa957d2a8924)

In this specific context, I'm redirecting traffic to a proxy inside a client that's running externally, I tried using createClient to make the connection but it makes a connection to the server itself, I need only the packets to be decoded and partitioned

**Comment by rom1504** [comment]
You need all the transforms not only the serialization one

**Comment by XaviscoB** [comment]
> You need all the transforms not only the serialization one

Can you explain it better? I'm not sure I understand

**Comment by XaviscoB** [comment]
> You need all the transforms not only the serialization one

I took a look at the code and saw that it was right in front of me

I passed the received buffer through the socket in the following order


serializer -> framer -> socket -> splitter -> deserializer

it was literally written as a comment in the code, thank you very much for your attention, now I was able to read the packets correctly
