### ISSUE TITLE
0.13.1 broke require('minecraft-protocol/lib/client')

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#136]
Using minecraft-protocol 0.13.0 I was able to require certain parts of the library as follows:

```javascript
var Client = require('minecraft-protocol/lib/client')
    , protocol = require('minecraft-protocol/lib/protocol')
```

this no longer works as of 0.13.1:

```
> require('minecraft-protocol/lib/client')
Error: Cannot find module 'minecraft-protocol/lib/client'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
```

* http://registry.npmjs.org/minecraft-protocol/-/minecraft-protocol-0.13.0.tgz
* http://registry.npmjs.org/minecraft-protocol/-/minecraft-protocol-0.13.1.tgz

"^0.13.0" semver matches 0.13.1 so this change can be picked up automatically (patch release).. is lib/* not expected to be considered part of the public API? If not I guess I can change to `require('minecraft-protocol').Client`, `require('minecraft-protocol').protocol`, but wanted to be sure. 0.13.1 change log had no mention of this change:

## 0.13.1
* Externalized rsa-wrap library to its own npm module, named ursa-native
* Fixed broken bed-related packets (thanks rom1504)

but it appears to be from https://github.com/PrismarineJS/node-minecraft-protocol/pull/115 Add support for ES Harmony with Babel

**Comment by wtfaremyinitials** [comment]
```js
require('minecraft-protocol/dist/protocol')
```

Should do the trick.

0.13.1 added the new ES6 build system

**Comment by deathcap** [comment]
Concerned about using `require('minecraft-protocol/dist/protocol')`, relying on an implementation detail(?) of the internal module paths (also https://github.com/PrismarineJS/node-minecraft-protocol/issues/125, but npm install fixes that).. `require('minecraft-protocol').protocol` works but for `require('minecraft-protocol')`.Client there's a slight complication, not currently exposed to browserify: https://github.com/PrismarineJS/node-minecraft-protocol/pull/137

**Comment by wtfaremyinitials** [comment]
The long term plan is to turn minecraft-protocol into a stream, and split off the createClient and createServer logic into their own module.

**Comment by roblabla** [comment]
The position of raw files in a module is an internal implementation detail @deathcap. Unless the library explicitly says "you can use module_name/x/y", you seriously shouldn't be using it. Semver is about public API stuff, the public API was not broken. Closing.

**Comment by deathcap** [comment]
@wtfaremyinitials Sounds good, I have my own version of `createClient` using websockets, could turn it into a module to complement the future native TCP-based createClient/Server modules. Maybe we could also have modules using the WebRTC transport or other protocols for peer-to-peer networking with MC (e.g. with https://github.com/rtc-io/rtc-quickconnect). related: https://github.com/PrismarineJS/prismarine-server/issues/16

@roblabla ok, makes sense. If GH-137 is accepted I'll be able to update my code to 0.13.1
