### ISSUE TITLE
Rename named_entity_spawn to entity_spawn ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#142]
Since it's not named anymore...
See http://wiki.vg/Protocol#Spawn_Player and https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L141

**Comment by roblabla** [comment]
We are using protocollib's packet names. 0x0C is still NAMED_ENTITY_SPAWN there : https://github.com/aadnk/ProtocolLib/blob/master/ProtocolLib/src/main/java/com/comphenix/protocol/PacketType.java#L123 .

**Comment by rom1504** [comment]
Oh ok, I didn't know that.

Well I guess this name is ok, the "named" is not a big deal.
