### ISSUE TITLE
Broken Examples, failing to require minecraft-protocol

### ISSUE THREAD

**Issue by bschlenk** [PrismarineJS/node-minecraft-protocol#143]
The examples are now broken. They are still requiring the parent folder, but they've all been moved one folder deeper. Requiring the parent of the parent folder should fix them.

**Comment by wtfaremyinitials** [comment]
*facepalm*

I'll fix that later today.

**Comment by wtfaremyinitials** [comment]
#144

**Comment by wtfaremyinitials** [comment]
Fixed
