### ISSUE TITLE
BungeeCord : Fails to parse

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#145]
Split from #129.

@adam-janis : 
> I am using protocol version 0.13.1 and connecting to server v1.8.. which should be supported, isn't?
> http://pastebin.com/yUAuTEBE
> http://pastebin.com/NsgiE4Ah
> Yes, it was told me that its running on bungeecord with 1.7.2 - 1.8.x protocol..

**Comment by zuazo** [comment]
I have not been able to reproduce the error using a local BungeeCord & spigot server (`1.8.3-R0.1`). @adam-janis, can you help on how to reproduce the error? Any special condition?

**Comment by adam-janis** [comment]
I guess the best would be to connect to the server which I used? Can I
provide you an ip?

**Comment by zuazo** [comment]
You can send me the IP via email if you are not comfortable posting it here.

**Comment by rom1504** [comment]
Fairly outdated, I think it might be time to close this one.

**Comment by roblabla** [comment]
Yeah. We need to remember to fix #129 tho one of those days.
