### ISSUE TITLE
Investigate spectator mode

### ISSUE THREAD

**Issue by wtfaremyinitials** [PrismarineJS/node-minecraft-protocol#146]
At the moment, a simple proxy causes spectator mode (gamemode 3) to not allow noclip. I think the parser may be missing something.

**Comment by rom1504** [comment]
How do you enable noclip ?

**Comment by wtfaremyinitials** [comment]
Switch to game mode 3



—

**Comment by rom1504** [comment]
So, according to Thinkofdeath, it might be related to a cape flag, so that might be http://wiki.vg/Protocol#Client_Settings or http://wiki.vg/Protocol#Spawn_Player

http://wiki.vg/Protocol#Spawn_Player has the entityMetadata field (http://wiki.vg/Entities#Entity_Metadata_Format https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/datatypes/minecraft.js#L178 ), so I wouldn't be too surprised this comes from this, this field is kind of annoying.

**Comment by roblabla** [comment]
@rom1504 those aren't sent as part of createClient/createServer, are they ?

**Comment by rom1504** [comment]
No I don't think so

**Comment by rom1504** [comment]
No much progress here except for something : if you make a proxy forwarding everything using the raw event (even in not-play state) then gamemode3 works.
Still no idea why.

What might be tried is transforming that raw proxy to a normal proxy progressively and see at which point it breaks.

**Comment by rom1504** [comment]
gamemode3 issue can be caused by uuid mismatch, need to try to see if the pb is still there when setting both the back end server and the proxy server in offline mode

**Comment by rom1504** [comment]
same problem in craftyjs

**Comment by rom1504** [comment]
any chance this is linked with #90 ?

**Comment by rom1504** [comment]
Not linked to #90, I don't even know what #90 is about, we can't wait to change state, and there is no client.on('state' in createServer.

**Comment by rom1504** [comment]
https://gist.github.com/roblabla/2e7a460722ea8c16b01d raw proxy

**Comment by rom1504** [comment]
My last try on this issue:
* raw proxy (gm3 working) https://gist.github.com/rom1504/d8a28f7baf171de03a7e https://github.com/rom1504/node-minecraft-protocol/blob/proxy_raw/examples/proxy/proxy_raw.js
* normal proxy (gm3 broken) https://gist.github.com/rom1504/0bcc02039e8ccf5a23d5 https://github.com/rom1504/node-minecraft-protocol/blob/testing_gm3/examples/proxy/proxy.js

Still 0 success.

**Comment by rom1504** [comment]
I think my idea from https://github.com/PrismarineJS/node-minecraft-protocol/issues/146#issuecomment-127936812 is probably the easiest way to get it done (or any way it's the last idea I didn't try): 
"What might be tried is transforming that raw proxy to a normal proxy progressively and see at which point it breaks."

**Comment by rom1504** [comment]
So manually setting the uuid to the same the client expects fix this bug.

Finally found the issue :)

I'll do a PR to fix that soon.
