### ISSUE TITLE
Fix test for world_particles packet (0x2a)

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#148]
https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/37
◦ play,ClientBound,0x2a: DID NOT PARSE THE WHOLE THING!

It seems there's a problem with the test or the packet  (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L371)

**Comment by rom1504** [comment]
might be related to https://github.com/PrismarineJS/node-minecraft-protocol/issues/135

**Comment by rom1504** [comment]
btw, shouldn't it make the test fail ?

**Comment by roblabla** [comment]
It's a bug in the test introduced by the fact I modified array a  little bit to fix 0x2a. Related to #129.

**Comment by roblabla** [comment]
#226 fixes this
