### ISSUE TITLE
Misnamed field 'blockId'

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#149]
node-minecraft-protocol 0.13.3 decodes the packet sent by:

/give player iron_pickaxe

as:

"{"id":47,"state":"play","windowId":0,"slot":38,"item":{"blockId":257,"itemCount":1,"itemDamage":0}}"

but '"blockId":257"' refers to the iron pickaxe, which is an item not a block. 

http://wiki.vg/Protocol#Set_Slot
http://wiki.vg/Slot_Data
https://github.com/PrismarineJS/minecraft-data/blob/master/enums/items.json

**Comment by rom1504** [comment]
everything in the inventory (=slot) is a block to node-minecraft-protocol https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L1120 , mineflayer figures out if it's a block or an item afterwards (see https://github.com/andrewrk/mineflayer/blob/master/lib/plugins/inventory.js#L392 and https://github.com/andrewrk/mineflayer/blob/master/lib/item.js#L15)

**Comment by rom1504** [comment]
btw mineflayer now has a creative api (https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#botcreativesetinventoryslotslot-item) , you might want to use that instead of /give

**Comment by roblabla** [comment]
I'm meh about changing the name. I agree it's confusing, but this would be a breaking change and I feel like it's pretty much unnecessary.
