### ISSUE TITLE
Support 15w14a

### ISSUE THREAD

**Issue by wtfaremyinitials** [PrismarineJS/node-minecraft-protocol#151]
Although it's an April Fool's joke, it appears to be based on top of real 1.9

**Comment by roblabla** [comment]
Supporting snapshots in general would be a good idea ^^.

**Comment by wtfaremyinitials** [comment]
These two packets appear to be issues:

```
C->S 0x04 PLAYER_POSITION
C->S 0x06 PLAYER_POSITION_AND_LOOK
```

I'm looking for more.

**Comment by rom1504** [comment]
The real snapshop is being handled in #205 , I think we can close this ;)

**Comment by wtfaremyinitials** [comment]
Agreed.
