### ISSUE TITLE
Emit some kind of error for missing or additional fields in write

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#156]
Additional fields are currently ignored (see https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L1503)
Missing fields are currenlty passed as undefined.

It would be better to emit some error.
Related to https://github.com/andrewrk/mineflayer/issues/269

**Comment by rom1504** [comment]
same as #127

**Comment by roblabla** [comment]
Missing is easy to do. Additional might have some non-acceptable overhead though.

**Comment by rom1504** [comment]
Missing is mostly about throwing an error if `value[typeArg.name]` is undefined there https://github.com/roblabla/ProtoDef/blob/master/src/datatypes/structures.js#L134

**Comment by rom1504** [comment]
moved tracking to https://github.com/roblabla/ProtoDef/issues/61
