### ISSUE TITLE
Include packet name in packet structure for generic 'packet' event

### ISSUE THREAD

**Issue by trumank** [PrismarineJS/node-minecraft-protocol#160]
It would be handy if a `name` property was added to packets so that packets emitted to the `packet` event could be easily identified without needing to translate the packet ID. For example, this would print the name of all received packets:

```javascript
client.on('packet', function(packet) {
  console.log(packet.name);
}
```

**Comment by roblabla** [comment]
Agreed, but "name" is going to be collisioning with some packet data. I've been thinking maybe separating packet metadata (id, state, name) from the actual data (the contents of the packet) might be a good idea. Like so : 

```
client.on('packet', function(data, packet) {
  console.log(packet); // { name: "chat", id: 1, state: "PLAY" }
});
```

Thoughts ?

**Comment by trumank** [comment]
Oh, that's a much better idea. This would mean the `id` and `state` properties could be removed from the named events and supplied as another object as well?

**Comment by roblabla** [comment]
Yup, that's the idea. Makes the whole system more flexible. That'd be a breaking change, although i'm not too sure many people depend on this behavior so I guess that's fine.

@rom1504 @wtfaremyinitials what do you guys think ?

**Comment by rom1504** [comment]
@roblabla I'm okay with changing the "packet" event, I just checked mineflayer doesn't use that event at all (I didn't even know it existed)
Mineflayer doesn't use packet.id and packet.state either.
Changing this is fine too imho.

**Comment by rom1504** [comment]
this is done right ?

**Comment by roblabla** [comment]
Yuup.

**Comment by trumank** [comment]
:+1:
