### ISSUE TITLE
Make client.write sync or add it a callback

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#168]
client.write is sync except if it needs to use zlib.deflate

It would be possible to either : 
* making it sync by using https://nodejs.org/api/zlib.html#zlib_zlib_deflatesync_buf_options
* adding a callback to client.write so user don't assume that client.write is sync

**Comment by rom1504** [comment]
Also there's a (kind of related) bug here : https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/protocol.js#L142 (buffer instead of buf)
that we probably never noticed because we're not sending stuff bigger than the compression threshold.

We can fix it once we make a choice about this issue.

**Comment by roblabla** [comment]
Sync is out of question. CB is the way to go. This doesn't fix #167 btw, as the packets are still being decoded out of order. I am unsure of the correct way to fix out-of-order packets still :(

**Comment by rom1504** [comment]
Yeah sure it doesn't fix #167 but mineflayer assumes everywhere that write is sync.
