### ISSUE TITLE
Splitting the README.md

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#183]
The README is a bit fat, wouldn't it be better to split it like in mineflayer ? Into 
* doc/api.md
* doc/history.md

**Comment by roblabla** [comment]
Yup, but I'd put HISTORY.md on the top-level, and instead of doc/api.md, have doc/README.md.

**Comment by rom1504** [comment]
okay, I can do that, but it would be better that #182 was merged before ;)
