### ISSUE TITLE
Document SOCKS and HTTP proxying mechanism

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#185]
The current way to add proxying into node-mc-proto : 

``` js
var mc = require("minecraft-protocol");
var Http = require("http");
var proxy = { address: '192.168.1.1', port: 80 };
mc.Client.connect = function(port, host) {
  var self = this;
  var req = Http.request({
    host: proxy.address,
    port: proxy.port,
    method: 'CONNECT',
    path: host + ":" + port
  });
  req.on('connect', function(res, socket, head) {
    this.setSocket(socket);
  });
  req.end();
};
```

A better way to do this would be nice

**Comment by rom1504** [comment]
A better way might be adding a Client.proxyConnect that would do that. And add an option in createClient to pass a proxy.

**Comment by roblabla** [comment]
i thought about having createClient take a socket. So we just bypass the connect and just call setSocket with the given socket. Then it's the user's responsibility to create the socket connection.

**Comment by rom1504** [comment]
As discussed in gitter, that'd work provided that the socket is optional (let's not break createClient and break everything built on top of nmp) and that we would create the socket as currently done if the socket isn't passed.

**Comment by roblabla** [comment]
Thought about this a bit more. What we need to do is separate createClient into two function : 

- handshakeClient(client), which does all the necessary steps to transition from HANDSHAKE to PLAY states
- createClient(), which creates a TCP connection and passes it to handshakeClient.

This way, people who want to use any other kind of stream (a File stream for protocol analysis, or a proxy stream) are able to do so without difficulty.

**Comment by rom1504** [comment]
https://github.com/mattcg/socks5-client would probably do for a socks5 proxy

**Comment by roblabla** [comment]
This is now easily possible thanks to #320. We just need to document the mechanism to do so. 

The following code is untested, use at your own risk.

## Sample code for HTTP proxy 

```javascript
var Http = require("http");
var minecraft = { host: "the.minecraft.server.host.com", port: 25565 };
var proxy = { host: '192.168.1.1', port: 80 };
var req = Http.request({
  host: proxy.host,
  port: proxy.port,
  method: 'CONNECT',
  path: minecraft.host + ":" + minecraft.port
});
req.on("connect", function(res, stream, head) {
  require("minecraft-protocol").createClient({
    stream: stream,
    username: "bleh",
    password: "bleh"
  });
});
```

## Sample code for Socks Proxy

```javascript
var Socks  = require("socks5-client");
var minecraft = { host: "the.minecraft.server.host.com", port: 25565 };
var proxy = { host: '192.168.1.1', port: 1080 };
require("minecraft-protocol").createClient({
  stream: Socks.createConnection({
    host: minecraft.host,
    port: minecraft.port,
    socksHost: proxy.host,
    socksPort: proxy.port
  }),
  username: "bleh",
  password: "bleh"
});
```

**Comment by rom1504** [comment]
for anyone coming here, https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js is the up to date example
