### ISSUE TITLE
Deprecate and remove the parser for nbt, return a simple buffer instead

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#186]
NBT parser is too opinionated currently, which bugs me immensely. It'd be much better if nbt was just a simple buffer, with a special reader that can figure out the size by doing a minimal amount of parsing.

**Comment by rom1504** [comment]
So about this: do we really want to do this ? I think it's more useful to have a json object for this like prismarine-nbt provide. And it's not like chunks that should be stored internally as buffers.

**Comment by rom1504** [comment]
So, c9290e664bae562fcccbabe3f8ffb403d71c64e3 and d25c4a20170a13a0dda53746d075ad796caac797 get us decent nbt parsing in all packets.
I think this solves this issue.
