### ISSUE TITLE
The optional ursa dependency isn't optional.

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/node-minecraft-protocol#189]
For a hour and some I am trying to figure out how to make use of the one-line install instructions for this project.

When I try to `npm install minecraft-protocol` I unfortunatelly get this error:

    c:\users\jakub\node_modules\minecraft-protocol\node_modules\ursa\src\ursaNative.h(13): fatal error C1083: Cannot open include file: 'openssl/rsa.h': No such file or directory (..\
    src\ursaNative.cc) [C:\Users\Jakub\node_modules\minecraft-protocol\node_modules\ursa\build\ursaNative.vcxproj]

I suppose this is the optional dependency that's, according to the readme.md, *somewhat complicated to install*. I see that. Can I get the framework to work without it?

**Comment by roblabla** [comment]
@Darker The dep is optional. It might blow up with an error, but that shouldn't be a problem. Try using the dep, it _should_ work. If it doesn't, could you please paste the whole npm error log ?

**Comment by roblabla** [comment]
Closing. Please reopen if you still have an issue, with more details.

**Comment by Darker** [comment]
Yeah sorry, it works as you said. I just got scared by the error.
