### ISSUE TITLE
How server send a chunk?

### ISSUE THREAD

**Issue by PKuebler** [PrismarineJS/node-minecraft-protocol#192]
Hey,

I have a server with `createServer` created and can connect with the normal Minecraft client.

with `client.write` I send even packages to the client.

Which package do I need to send a chunk/the map?

I try it currently with `map_chunk`. Here I ask myself but what I need to send in `bitmap`? at `chunkData` I have of `prismarine-chunk` the function `.dump ()` pass.

Could you possibly add a small example?

greets

**Comment by wtfaremyinitials** [comment]
It's been a long time since I've touched that code, but if I remember correctly, the bit mask should be set to `1111111111111111`

**Comment by roblabla** [comment]
Using prismarine-chunk, https://github.com/mhsjlw/node-minecraft-server/blob/def7426fc58d3ff21714f068a39028ea4a0b94ba/app.js#L16-L24 creates the world, https://github.com/mhsjlw/node-minecraft-server/blob/def7426fc58d3ff21714f068a39028ea4a0b94ba/app.js#L61-L68 sends it to the client.
