### ISSUE TITLE
"pings the server" test fails randomly with ECONNREFUSED

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#194]
Needs to investigate the random ECONNREFUSED bugs in that test, they're annoying and confusing.

**Comment by rom1504** [comment]
Here are some of these bugs in the test instances : 
* https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/101
* https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/85
* https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/70


```
 ✖ 1 of 124 tests failed:

  1) client pings the server:
     connect ECONNREFUSED
```

https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/test.js#L318


check https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/ping.js

**Comment by rom1504** [comment]
I think the problem is the startServer function is failing.
It would be interesting to start cleaning test.js by putting startServer.js (https://github.com/andrewrk/mineflayer/blob/master/test/lib/start_server.js) in a separate npm package (maybe along with download_server.js).

**Comment by rom1504** [comment]
Also test.js doesn't always check if the cb of startServer has an error, that should be fixed (see https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/test.js#L322 )

**Comment by rom1504** [comment]
any chance the port is already taken in circle ci ?
if so a simple solution would be to start the server with a different port when that happens.

**Comment by rom1504** [comment]
I'm not 100% sure this is solved ;)

**Comment by rom1504** [comment]
ah lol, I think it auto-closed it because I put "[...] fix #194" in my commit
better reopen this

**Comment by rom1504** [comment]
More info into that problem there https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/189

Seems related to the server dir not being created for some reason (see https://github.com/rom1504/node-minecraft-wrap/blob/master/lib/wrap.js#L101 )

**Comment by rom1504** [comment]
Pretty sure this is fixed now.

**Comment by roblabla** [comment]
Closing.
