### ISSUE TITLE
Use 'chat' instead of 0x03?

### ISSUE THREAD

**Issue by izy521** [PrismarineJS/node-minecraft-protocol#195]
Hello, I'm not sure if my problem is isolated or not but I'll explain anyway.

I had a few issues trying to get my bot to say things. My friend assured me that they weren't using the 'Spigot' server (I searched and it seemed someone else was having the same issues with them), but the messages I was receiving from server to client looked like Spigot's.

This just being an example, first one doesn't work, the second one does: 

```javascript
client.on('chat', function(packet) {
	client.write(0x03, {
		message: "Hello world"
	});
});
/***************************************/
client.on('chat', function(packet) {
	client.write('chat', {
		message:"Hello world"
	});
});
```

I found this out on a previous example, the 'chat' event was replaced by 0x03, but now it's 'chat'. So I tried it with the write method and it worked. I don't know if the second would also work for anyone using a non-spigot server, but if it does would it make sense to change the examples?

**Comment by rom1504** [comment]
Yeah that's related with #154 
Really nothing should be using the numeric codes, so if you see an example using them, it's probably outdated/broken.
We should fix that !
Feel free to make a PR ;)
