### ISSUE TITLE
Make it possible to choose what to answer on the ping response

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#206]
It's currently hardcoded (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L87) displaying nothing because no players.

**Comment by rom1504** [comment]
It's actually already possible : see beforePing option (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L27)
but it should be documented there https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/doc#mccreateserveroptions

**Comment by roblabla** [comment]
I'm planning on changing this anyway, what with the modularization of NMP's createServer. So let's not document this yet, since I'll probably be breaking it soon.

**Comment by rom1504** [comment]
depends on #210
