### ISSUE TITLE
Prevent client with the wrong version to connect to the server

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#209]
Currently makes the script crash
see http://wiki.vg/Protocol#Clientbound

**Comment by roblabla** [comment]
could you post the crash stacktrace ?

**Comment by rom1504** [comment]
Well, actually it probably only crashes with my snapshot-1.9 branch which have throw instead of return {error:} and these throw will go away.
So it crashed on a 1.8 packet it tried to recognize as a 1.9 one.
With current code it might not have crashed but instead just ignored the packets, but that's not much better.
I think we should check what version the client is on, and in the case it's wrong disconnect it (since that's part of the handshake phase, the backend server in a proxy won't do that for exemple : handshake is handled in createServer)

**Comment by roblabla** [comment]
it actually is somewhat better to ignore the packet. Since packets are length-prefixed, it gives us some wiggle room to support mods that have custom packets.

We should probably add an event though, something like 'unknown_packet', that the client can listen on and chose what to do.
