### ISSUE TITLE
Ways to phase out entityMetadata and slot datatypes

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#225]
Those two are the last datatypes that are very minecraft-specific, and could, with a bit of magic, be generalized. The problem is, they both need a new datatype.

- Slot requires some kind of `peek` dataType, that acts like switch, but compares to a value in the stream without consuming it.
- EntityMetadata requires some kind of `loop` dataType.

**Comment by rom1504** [comment]
what about uuid ?

**Comment by roblabla** [comment]
UUID is read as 4 ints, and then stringified into a dashed hex. I hardly see how we could ever represent that in the protocol ^^'.

**Comment by rom1504** [comment]
hmm, maybe it's standard enough to be not minecraft specific though ?

**Comment by rom1504** [comment]
From @roblabla : 
```js
function readEntityMetadata(buffer, offset, typeArgs, context) {
  var cursor = offset;
  var metadata = [];
  var item, key, type, results, reader, typeName, dataType;
  while(true) {
    item = buffer.readUInt8(cursor);
    if(item === typeArgs.endVal) {
      return {
        value: metadata,
        size: cursor - offset,
      };
    }
    results = this.read(buffer, cursor, "entityMetadataKeyType");
    cursor += results.size;
    ({ key, type } = results.value);
    var results = this.read(buffer, cursor, ["entityMetadataItem", { "compareTo": "type" }], { type });
    metadata.push({
      key,
      type,
      value: results.value,
    });
    cursor += results.size;
  }
}
```
```json
 "entityMetadata": ["entityMetadataLoop", { "val": 256 }],
"entityMetadataKeyType": ["bittrick"],
"entityMetadataItem: "we already have that"
```
and entityMetadataLoop is the native type
this is the flexible cross-version way
so we can change every part of the algorithm without issue

```json
"position": ["bittrick", [
  { "name": "x", "size": 26 },
  { "name": "y", "size": 12 },
  { "name": "z", "size": 26 }
]]
```

```json
"entityMetadataKeyType": ["bitfields", [
  { "name": "type", "size": 3 },
  { "name": "key", "size": 5 }
]]
```
I think
and for 1.9
```json
 "entityMetadataKeyType": ["container", [
  { "name": "key", "type": "ubyte" },
  { "name": "type", "type": "ubyte" }
]]
```

So it doesn't get lost in the gitter backlog.

**Comment by rom1504** [comment]
entity metadata is done.

Any chance the new 'anon' thing can work for slot ?

**Comment by roblabla** [comment]
Nah, anon doesn't have much to do with it. I mean, it does allow us to have a sane object structure instead of nesting to doom, but it doesn't have any on-wire functionality.

What we need for slot is still the same as before : a `peek` datatype. I'm very reluctant to add it though, because its semantic are not obvious at all. It's fairly obvious how all the current datatypes need to be written, peek is just downright wierd.

**Comment by rom1504** [comment]
I think slot can be implemented without peek, it's just that nbtData will potentially be 0 which makes sense. I'll try to do that.

**Comment by rom1504** [comment]
So I took the same route than entityMetadata did : I defined manually a (simple) optionalNbt, that is used directly in some packets now and I used it to define slot.
Once that's merged (see https://github.com/PrismarineJS/node-minecraft-protocol/pull/304) then this issue will be mostly done (see https://github.com/roblabla/ProtoDef/issues/31 for some remaining stuff to remove from minecraft.js + maybe in the future we could make optionalNbt and entityMetadataLoop more general)

**Comment by rom1504** [comment]
ok, done
