### ISSUE TITLE
Stop using numerical ids everywhere in nmp

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#232]
All PLAY ids changed in 1.9, so we should just use the names.
Example of use in PLAY state : 
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/benchmark.js#L8
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/test.js#L411
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/proxy/proxy.js#L130
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createClient.js#L48
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/server.js#L29

Example of use in other states : 
* https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createClient.js#L49

(numerical ids currently break tests in 1.9, see https://circleci.com/gh/rom1504/node-minecraft-protocol/115 )

**Comment by rom1504** [comment]
Play state packet ids are now not used in nmp ( #233 )
The same can be done for the other states.

**Comment by roblabla** [comment]
Done everywhere except in tests by #243

**Comment by rom1504** [comment]
It's done in tests actually.
Only thing remaining here is the example proxy.

**Comment by rom1504** [comment]
done
