### ISSUE TITLE
Update examples in the readme

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#254]
These 2 examples are currently outdated
Two possibilities : 
1. copy [client_echo.js](https://github.com/PrismarineJS/node-minecraftprotocol/blob/master/examples/client_echo/client_echo.js) and 
[server_helloworld.js](https://github.com/PrismarineJS/node-minecraftprotocol/blob/master/examples/server_helloworld/server_helloworld.js) to the readme (that's what the current outdated examples of the readme come from)
2. just replace the examples in the readme by links

**Comment by roblabla** [comment]
Done
