### ISSUE TITLE
Fix player_info serialization

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#280]
For some reason (I think the uuid change), nmp server 0.15.0 (and master) doesn't  accept more than one connection.
In the proxy, I get
```
Connection error by server (127.0.0.1)  Invalid credentials.
undefined
```

**Comment by rom1504** [comment]
(I don't get that problem with a basic server like server helloworld though)

**Comment by rom1504** [comment]
![mc-uuid-bug](https://cloud.githubusercontent.com/assets/2346494/10382402/e0136e70-6e23-11e5-9e81-0f092633b631.png)

That happens when sending player_info with flying-squid. I dont quite understand what this is about.

**Comment by roblabla** [comment]
This means our packet definition is wrong. By a lot. What parameters are you sending in flying-squid ?

**Comment by rom1504** [comment]
https://github.com/mhsjlw/flying-squid/blob/master/src/lib/playerPlugins/login.js#L168

https://github.com/mhsjlw/flying-squid/commit/587ce76f271eaf550a5ecdcaa08d3b748f954224#diff-1c9edbd9eef90509dd2175205a3bb7fc

It all seems correct when printing the values so idk...

**Comment by roblabla** [comment]
@rom1504 did you try using github MASTER ? There was a bug with UUIDs fixed that hasn't made it to NPM yet

**Comment by rom1504** [comment]
No, I'll try.

**Comment by rom1504** [comment]
Ok, just tried, I got a slightly different error.
![mc-uuid-bug2](https://cloud.githubusercontent.com/assets/2346494/10391069/b422247e-6e7c-11e5-9b39-e4d52fbbd785.png)

**Comment by rom1504** [comment]
That's a data sent with player_info:
```json
{
  "action": 0,
  "data": [
    {
      "UUID": "ed1d1941-20b6-401c-a214-1e2a4e031799",
      "name": "rom1504",
      "properties": [],
      "gamemode": 1,
      "ping": 1,
      "hasDisplayName": true,
      "displayName": "rom1504"
    },
    {
      "UUID": "a711f533-fcd1-4585-bed9-d35622b6ad9a",
      "name": "rom15042",
      "properties": [],
      "gamemode": 1,
      "ping": 1,
      "hasDisplayName": true,
      "displayName": "rom15042"
    }
  ]
}
```

I don't think anything is wrong with it. It works fine for the first player (with just one entry)

**Comment by rom1504** [comment]
Well I bypassed it temporarily in flying-squid by sending multiple player_info but that should be fixed. (and we have nothing testing multiple clients in the tests afaik)

**Comment by rom1504** [comment]
Could be something wrong with https://github.com/PrismarineJS/minecraft-data/blob/1.8/enums/protocol.json#L1678

**Comment by rom1504** [comment]
Add
```js
client.write('player_info',{
    "action": 0,
    "data": [
      {
        "UUID": "ed1d1941-20b6-401c-a214-1e2a4e031799",
        "name": "rom1504",
        "properties": [],
        "gamemode": 1,
        "ping": 1,
        "hasDisplayName": true,
        "displayName": "rom1504"
      },
      {
        "UUID": "a711f533-fcd1-4585-bed9-d35622b6ad9a",
        "name": "rom15042",
        "properties": [],
        "gamemode": 1,
        "ping": 1,
        "hasDisplayName": true,
        "displayName": "rom15042"
      }
    ]
  });
```
at https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/server_helloworld/server_helloworld.js#L36 to get the same error.

**Comment by rom1504** [comment]
https://gist.github.com/rom1504/f38d9cd6151c791052d3 : the produced buffer is definitely different

**Comment by rom1504** [comment]
Alright I found the problem: displayName is not sent by the vanilla server in that packet, and is probably supported by the vanilla client only in some specific format, not sending it give the same result and works well.

This works fine:
```js
client.write('player_info',{
    "action": 0,
    "data": [
      {
        "UUID": "ed1d1941-20b6-401c-a214-1e2a4e031799",
        "name": "rom1504",
        "properties": [],
        "gamemode": 1,
        "ping": 1
      },
      {
        "UUID": "a711f533-fcd1-4585-bed9-d35622b6ad9a",
        "name": "rom15042",
        "properties": [],
        "gamemode": 1,
        "ping": 1
      }
    ]
  });
```
