### ISSUE TITLE
Read error for ping_start : Packet data not entirely read

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#290]
Linked to mhsjlw/flying-squid#85

**Comment by rom1504** [comment]
I get that error very regularly, at all hours, always from the same ip, so I think this is coming from a bot.
A bot that probably serialize things wrong.

So I think there is nothing to do nmp side. I think I'll either add a check in flying-squid to display a less verbose error, or simply ban that ip from my server.

**Comment by rom1504** [comment]
this can be closed ;)
