### ISSUE TITLE
Always ping server before initiating connection?

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#327]
`ping(options, cb)` performs a [Server List Ping](http://wiki.vg/Server_List_Ping) using the `STATUS` protocol, returning a bunch of useful information, example:

```json
{
    "version": {
        "name": "1.8.7",
        "protocol": 47
    },
    "players": {
        "max": 100,
        "online": 5,
        "sample": [
            {
                "name": "thinkofdeath",
                "id": "4566e69f-c907-48ee-8d71-d7ba5aa00d20"
            }
        ]
    },	
    "description": {
        "text": "Hello world"
    },
    "favicon": "data:image/png;base64,<data>"
}
```

The version/protocol field could be useful for https://github.com/PrismarineJS/node-minecraft-protocol/issues/234 Cross-version protocol support. Before initiating the connection, perform a ping to get the version and use it accordingly. `description`, `favicon`, and other fields could also be saved for consultation later.

FML/Forge servers https://github.com/PrismarineJS/node-minecraft-protocol/issues/114 https://github.com/PrismarineJS/node-minecraft-protocol/pull/326 additionally contain more information:

```json
  "modinfo": {
    "type": "FML",
    "modList": [
      {
        "modid": "mcp",
        "version": "9.18"
      },
      {
        "modid": "FML",
        "version": "8.0.99.99"
      },
      {
        "modid": "Forge",
        "version": "11.15.0.1715"
      },
      {
        "modid": "IronChest",
        "version": "6.0.121.768"
      }
    ]
  }
```

(modinfo.type is also returned on [Glowstone++](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/f95fd32b34388bbe789db2ce82edba6278286d35), 'BUKKIT' is a recognized type, to show the Bukkit logo in FML's server list screen. 'VANILLA' as well but not clear if anyone sends it.).

`modList` is particularly useful because it gives the list of mods you must have in order to connect to the server. The FML|HS handshake protocol sends this list in the ModList packet, and if it doesn't match the server will kick the client, so the client would have to know it *a priori* unless retrieved from the Server List Ping. 

`createClient()` already does perform one pre-connect action: resolving DNS srv (_minecraft._tcp) records. ping.js doesn't do this, but it probably should (bug? anyone want to test?). Server List Ping would be another reasonable pre-connect step to perform, imho. Real clients usually show a server list before the player connects, so this would more closely match vanilla behavior as well.

Therefore here's the changes I suggest:

* Refactor DNS SRV resolution out of createClient.js, so ping() can use it standalone as well
* Enhance createClient() to ping() (including DNS SRV) before connecting, by default
* Optionally allow createClient() to skip pinging (option `ping: false`?), if desired; probably ought to also have `dns_srv: false` option to skip the pre-connect DNS resolution step. Some clients may want to skip these steps (and forgo the added benefits - no server description, automatic protocol negotiation, automatic Forge mod support), but I'd imagine most will want the useful default functionality

**Comment by deathcap** [comment]
Made this change in examples/client_forge: https://github.com/PrismarineJS/node-minecraft-protocol/commit/283b75d6946fcf1999beb1a29dc0d6cf4d09edae - but I think it'd be useful generically

**Comment by roblabla** [comment]
ping not doing DNS SRV is a bug.

The ability to disable the SRV request isn't super useful in the 99.9999% scenario. The notchian client makes an SRV DNS request, we're just matching that. If someone wants to bypass it, he can just provide an already-created TCP stream to NMP (when we support that).

IMO, createClient shouldn't call ping. The notchian client doesn't do that, for one. For two, some servers don't reply to pings. What you describe is a hack specific for the forge client, and I think should only belong to a future "nmp-forge" module. The overhead isn't negligeable (initiate a connection, handshake, ping, close connection) for something that people not connecting to forge (which should be most people) don't need at all.

**Comment by rom1504** [comment]
"ping not doing DNS SRV is a bug." Actually it does, connect is defined in
createClient and ping is only used in files including createClient (in
test.js). That means ping doesn't work if you require only ping.js but that
shouldn't happen since users require the whole nmp. That design is a bit
confusing though, could be improved.

**Comment by rom1504** [comment]
Pinging before connecting could be an option in createClient, because it's
indeed useful to support dynamic cross version. We could have a timeout for
it so that if it timeout something appropriate could be done (defaulting to
the current version for dynamic cross version or trying normal login for
forge (or a default list of mods)

**Comment by deathcap** [comment]
If a server does not respond to Server List Ping, then how will it appear in the server list? Example of server that doesn't respond?

**Comment by deathcap** [comment]
Relevant: https://github.com/Dinnerbone/mcstatus

**Comment by roblabla** [comment]
I've seen some custom servers do that to put a server in some sort of
"maintenance mode"

**Comment by deathcap** [comment]
Here's a working prototype along the lines of what I had in mind:

https://github.com/deathcap/node-minecraft-protocol-auto

Uses a ping to get the protocol version, enables Forge with mod list if server type='FML', and also automatically sets the client protocol version to match the server version. Works in testing a 1.9 snapshot, 1.8.9, some third-party 1.8 server software, and a Forge 1.8.9 server, but has some rough edges:

* Hardcodes knowledge of release versions and protocol versions, would be nice to get this from minecraft-data instead (protocolVersions.json added in https://github.com/deathcap/node-minecraft-protocol-forge)
* Uses only the major release version (1.8, 1.9..), but client/server may have mismatched protocol versions, PR to NMP to allow specifying protocolVersion directly: https://github.com/PrismarineJS/node-minecraft-protocol/pull/330
* Ping timeouts: not handled well, could fallback to a normal server connection if an error is received, but if the server is up but ignoring the ping then it'll wait indefinitely, separate bug https://github.com/PrismarineJS/node-minecraft-protocol/issues/329
* Had to change the API of the wrapper, not compatible with `client = createClient()` because of the ping packet, made it async `createClientAsync(options, function(err, client)`
* Forge support uses [node-minecraft-protocol-forge](https://github.com/deathcap/node-minecraft-protocol-forge), TBD how this support will fit in https://github.com/PrismarineJS/node-minecraft-protocol/pull/326

I haven't published node-minecraft-protocol-auto to NPM, I still think it would be a worthwhile addition to node-minecraft-protocol itself. Maybe not in `createClient()`, but it could be a separate API available as an opt-in feature.

**Comment by deathcap** [comment]
This issue is well-covered by https://github.com/PrismarineJS/node-minecraft-protocol/issues/234 so I'll close it, still would like to see this though =)
