### ISSUE TITLE
Use ES6 let/const everywhere instead of var

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#335]
With node-minecraft-protocol embracing ES6 (https://github.com/PrismarineJS/node-minecraft-protocol/pull/322 et. al.), I think it is worth considering updating the variable declarations to use the new block-scoped `let` and `const` keywords, instead of the function-scoped `var`. Current status:

```
node-minecraft-protocol $ grep -r 'var ' src/|wc -l
     175
node-minecraft-protocol $ grep -r 'let ' src/|wc -l
       3
node-minecraft-protocol $ grep -r 'const ' src/|wc -l
       0
```

Many of the `var`s could be updated to `const`s (if assigned only once), and the others to `let`s. `let` avoids some of the pitfalls of `var`'s scoping rules.

New code can use let/const, but it feels odd to have a mix of let/const/var, so a comprehensive conversion could make sense. Should be a fairly easy change to make, but results in a large diff and will cause merge conflicts so I've put it off for now.

**Comment by rom1504** [comment]
:+1:
