### ISSUE TITLE
increase client timeout timeout to 30s

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#341]
@hansihe says vanilla timeout is 30s

(is there any good source for that info ?)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client/keepalive.js#L5

**Comment by rom1504** [comment]
> 20:31 < hansihe> client dcs if there is over 20sec since a keepalive
> 20:32 < hansihe> server kicks if there is over 30sec since a response

**Comment by hansihe** [comment]
My source for this was [wiki.vg](http://wiki.vg/Protocol#Keep_Alive). I don't have any sources except that, however I could do some tests to verify it.
