### ISSUE TITLE
[autoVersion] Protocol version 5 shared between "1.8" (snapshot 14w02a) and 1.7 major versions

### ISSUE THREAD

**Issue by deathcap** [PrismarineJS/node-minecraft-protocol#345]
http://wiki.vg/Protocol_version_numbers

<img width="404" alt="screen shot 2016-02-14 at 1 03 31 pm" src="https://cloud.githubusercontent.com/assets/5897956/13036409/7b0f1b02-d31b-11e5-965e-e7dc2ae717df.png">

This breaks the autoVersion plugin on 1.7, because it gets protocolVersion == 5 from the server ping packet, and translates this to the "major" version from minecraft-data, using the latest: 14w02a, which is a 1.8 snapshot not 1.7. Will need to rethink how to handle major/protocol versions in autoVersion...

Not currently a problem, but would be if minecraft-data supports 1.7: https://github.com/PrismarineJS/minecraft-data/pull/104

**Comment by roblabla** [comment]
One potential solution is to NOT consider snapshots to be qssociated with versions :|

I still find the idea that 14w02a is somehow "1.8" silly.

**Comment by rom1504** [comment]
Using the last non snapshot version would work (without breaking 1.9).

**Comment by rom1504** [comment]
I mean, using the last non snapshot version except if there is none, in that case use the last supported snapshot

**Comment by rom1504** [comment]
Not considering snapshots to be "1.9" would mean renaming the 1.9 folder at each update (or having a 1.9-snapshot which is not that much better that 1.9)

**Comment by roblabla** [comment]
@rom1504 tbh, I'm actually _for_ creating copies for each snapshot updates. No, growing a huge number of files is not a real issue.

**Comment by rom1504** [comment]
That means most data would be incorrect.

It's not practical to update every data files for each version, except maybe if we got a fully automatic extractor from the jar. (For every data file)

Also I'm not sure how this is not a problem to make mcdata 100 MB. It's something that could be solved by making several npm packages, but I think we should do that kind of thing only if we really have good data for all these versions. Also I'm not really convinced there's a point to having the data of every of the 80 1.9 snapshots.

**Comment by roblabla** [comment]
Having some metrics about how heavy a single version is would be interesting. I very much doubt we'd get anywhere close to 100MB. If bloat is a problem, multiple packages isn't very hard to deploy

There is a point to having that data : we're able to keep a history of what happened in each minecraft version, which might give some insight into the direction mojang is going. It's interesting for historical purposes, and it's useful for developers targetting a specific version for whatever reason (They need to connect to a specific snapshot some server is hosting).

Besides, the snapshot data is currently either very old or incorrect already ^^'.

**Comment by rom1504** [comment]
So, would we duplicate the current 1.8 protocol.json in several 1.8.x folders ?
And change every copy if we notice some error?

**Comment by rom1504** [comment]
About 100MB, I don't actually know, but last time I browserified nmd it was a few MB and I'm pretty sure it was the json files taking the room.

**Comment by deathcap** [comment]
Yeah the [minecraft-data](https://github.com/PrismarineJS/minecraft-data) files do take up a fair amount of space, also much of it is not used by node-minecraft-protocol (blocks, items, etc.; only the protocol) — not much of a problem for desktop apps, but when targeting the browser it is included in the bundle in the absence of [tree shaking](https://github.com/voxel/issues/issues/6#issuecomment-183177193). A larger problem, not sure how to solve it.

But for this specific issue, maybe we should eliminate the notion of "major versions", and let the protocol data refer to a *range* of versions, in this case 1.7.10-10.17.6, but also 14w02a.

If the protocols are similar enough to be defined by the same spec, then the same file in minecraft-data could cover multiple protocol versions (for example, if protocol 5 and 6 are similar enough (just an example, idk if they are in this case), wouldn't be duplicated), reducing maintenance costs and duplication. But if there are enough differences, then we would split them out.

**Comment by rom1504** [comment]
@deathcap what is broken by this issue currently ? I'd though it would just work since the protocol version is just used to go to "1.7" which then leads to the version.json which gives 1.7.10

**Comment by rom1504** [comment]
( https://github.com/deathcap/minecraft-data/blob/mc17/data/1.7/version.json )

**Comment by deathcap** [comment]
src/client/autoVersion looks at the `version.protocol` field of the ping response (5 in this case). I was going to use `version.name` originally ("1.7.10" on vanilla), but 3rd party server software changes this field (observed "Spigot 1.7.10" and "Glowstone++ 1.7.10"), so it would require parsing to strip off the server software name, I suppose I could, figured `version.protocol` was more precise but maybe it's better to switch to `version.name`..

**Comment by deathcap** [comment]
I'm thinking using `version.name` (parsed to remove server software brand) is a good idea, for snapshots it is the snapshot name (15w40b), which if https://github.com/PrismarineJS/minecraft-data/pull/109 https://github.com/PrismarineJS/node-minecraft-data/pull/17 are merged, will work with `require('minecraft-data')('15w40b')`, and 1.8.9 will work with `require('minecraft-data')('1.8.9')`, 1.7.10 with `require('minecraft-data')('1.7.10'` after https://github.com/PrismarineJS/minecraft-data/pull/104.

**Comment by deathcap** [comment]
`version.name` works well, better than I originally expected, and it should also avoid the problem of pre/post Netty protocol ambiguity (e.g. 78 is overloaded to be both 1.6.4 and 15w41b).Opened a pull request: https://github.com/PrismarineJS/node-minecraft-protocol/pull/347

**Comment by rom1504** [comment]
This specific issue (auto version) was fixed by #347 but the discussion about "major version vs range of version vs all the versions" is still open, we'll see how it goes.
