### ISSUE TITLE
tab_complete gives error.

### ISSUE THREAD

**Issue by annoyingcalc** [PrismarineJS/node-minecraft-protocol#368]
For a proxy, when a client sends the tab_complete packet, the proxy errors and kicks them, even when the user code only writes to the server what the client sends.

In the console, this error is written: { [Error: Deserialization error for play.toServer : Read error for name : 64 is not in the mappings value] field: 'play.toServer' }

**Comment by rom1504** [comment]
waiting for more info on tab complete change in http://wiki.vg/Pre-release_protocol from #mcdevs

**Comment by rom1504** [comment]
@annoyingcalc you are using the mc client and server 15w05b right ?
