### ISSUE TITLE
Can't install minecraft-protocol

### ISSUE THREAD

**Issue by nikhiljha** [PrismarineJS/node-minecraft-protocol#375]
On windows, I'm trying to 

`node install minecraft-protocol`

Get this error: http://hastebin.com/eqogixaqek.tex

**Comment by rom1504** [comment]
http://hastebin.com/cavawukobi.tex

we should probably remove ursa altogether.

**Comment by nikhiljha** [comment]
Was using very old version - disregard.

**Comment by roblabla** [comment]
ursa is an optional dependency anyway @rom1504. It's a good idea to keep it ^^. Besides, I think npm3 has much less scary errors surrounding optional deps.
