### ISSUE TITLE
Add README and/or npm publish proxy example

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#380]
The proxy is pretty useful to know more about the protocol, being able to npm install -g minecraft-proxy (or something) might be nice.

**Comment by mhsjlw** [comment]
Unfortunately, https://www.npmjs.com/package/minecraft-proxy is not available 😭 

:+1: for separate packaging, here are some ideas for names (they're kind of lame, I know):
- prismarine-proxy
- mc-proto-proxy
- minecraft-watch

**Comment by rom1504** [comment]
proxy FAQ : 
* https://github.com/PrismarineJS/node-minecraft-protocol/issues/380
* https://github.com/PrismarineJS/node-minecraft-protocol/issues/454

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/185#issuecomment-254785390

**Comment by rom1504** [comment]
added a readme.
I think instead of putting it in an other repo or package, we could just add it as a minecraft-protocol binary so if you global install it you can use minecraft-proxy binary

**Comment by rom1504** [comment]
https://github.com/wvffle/minecraft-packet-debugger solves this
