### ISSUE TITLE
error for server, client and minecraft protocol version 1.9

### ISSUE THREAD

**Issue by lastuniverse** [PrismarineJS/node-minecraft-protocol#381]
server version 1.9
the client version 1.9
the Protocol version in proxy.js 1.9
when using proxy.js folder with example throws the following error.
error occurs when updating the server list in the client.

![screenshot](https://img-fotki.yandex.ru/get/68326/196117532.1/0_130820_347cdda8_orig.png)

**Comment by lastuniverse** [comment]
when you try to connect the server through the proxy, the client swears to the Protocol version
![screenshot](https://img-fotki.yandex.ru/get/67221/196117532.1/0_130821_57715b10_orig.png)

**Comment by rom1504** [comment]
It looks like you are running it through electron or something, did you try to run it directly?
I'm not getting any errors so I don't get why you do.

**Comment by rom1504** [comment]
"when you try to connect the server through the proxy, the client swears to the Protocol version" ah here we go. That means you are not running the last version.

**Comment by rom1504** [comment]
Oh, you indeed changed the version option to "1.9" and not "15w40b" ?

**Comment by lastuniverse** [comment]
how to see I have or not "15w40b"?

**Comment by lastuniverse** [comment]
![client version](https://img-fotki.yandex.ru/get/71764/196117532.1/0_13082d_c3160979_orig.png)

**Comment by lastuniverse** [comment]
if run it directly (without electron)
```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Deserialization error for handshaking.toServer : Read error for name : 122 is not in the mappings value
    at ProtoDef.readMapper (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/datatypes/utils.js:40:34)
    at ProtoDef.read (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/protodef.js:102:31)
    at /home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/datatypes/structures.js:115:32
    at tryCatch (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/utils.js:33:12)
    at tryDoc (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/utils.js:40:10)
    at /home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/datatypes/structures.js:114:5
    at Array.forEach (native)
    at ProtoDef.readContainer (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/datatypes/structures.js:109:12)
    at ProtoDef.read (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/protodef.js:46:25)
    at ProtoDef.read (/home/roman/work/electron/apps/minecraft.proxy.bot/src/node_modules/protodef/dist/protodef.js:102:31)
```

**Comment by rom1504** [comment]
I mean in the createServer (and createClient) option, you need to put version: "1.9"

**Comment by rom1504** [comment]
If you use the nmp proxy you need to give it 1.9 as a CLI arg

**Comment by lastuniverse** [comment]
var srv = mc.createServer({
  'online-mode': false,
  port: 25568,
  keepAlive: false,
  version: "1.9"
});
...
  var targetClient = mc.createClient({
    host: "game.real-world.pw",
    port: 25566,
    username: "kapa6a3er@gmail.com",
    password: ".....",
    keepAlive:false,
    version: "1.9"
  });

**Comment by rom1504** [comment]
> 21:59 < rom1504> okay let's try one last thing
> 21:59 < rom1504> I'm going to make a clean clone
> 21:59 < rom1504> and try again
> 22:00 < rom1504> cd /tmp/ ; git clone git@github.com:PrismarineJS/node-minecraft-protocol.git
> 22:00 < rom1504> cd node-minecraft-protocol ; npm install
> 22:01 < rom1504> cd examples/proxy ; node proxy.js localhost 1.9
> 22:01 < rom1504> started a local offline server
> 22:01 < rom1504> and the 1.9 client
> 22:01 < rom1504> connected to the proxy
> 22:02 < rom1504> no error

**Comment by lastuniverse** [comment]
perhaps the owner of the server clever with protocols.
the list shows the server version 1.9.
try to run your server vanilla 1.9 and will connect through the proxy to it.
according to the results accomplish your goal.

**Comment by rom1504** [comment]
I cannot connect to game.real-world.pw, even directly.

**Comment by lastuniverse** [comment]
i have `npm install minecraft-protocol` version

**Comment by lastuniverse** [comment]
in game.real-world.pw ativate whitelist

**Comment by rom1504** [comment]
how to I "activate whitelist" ? the server just kicks me (with a direct connection)

**Comment by lastuniverse** [comment]
my account for test in you mail romain.rom1@gmail.com

**Comment by rom1504** [comment]
Alright I'm getting the same errors.
I believe this is not a vanilla 1.9 server. Is it ?

**Comment by lastuniverse** [comment]
The owner of the server says that the server is pure vanilla. But to say I won't. Put your server and all will keep checking back.

**Comment by lastuniverse** [comment]
the password for my account until I will not change.

**Comment by rom1504** [comment]
okay I confirmed there is an error with entity effect.

Checking the other errors

**Comment by lastuniverse** [comment]
yesterday the server worked on 1.8.7
today the owner of the server updated to release 1.9.
it is possible that the Protocol for release of 1.9 and a Protocol for 1.9-pre4 slightly different causing this error

**Comment by rom1504** [comment]
yes indeed.

**Comment by rom1504** [comment]
fixed and published as 0.19.2

**Comment by lastuniverse** [comment]
thank you very much.

**Comment by lastuniverse** [comment]
bug translator :) I asked do you need the source code that the proxy bot

**Comment by lastuniverse** [comment]
https://github.com/lastuniverse/minecraft.proxy.bot.gui

**Comment by rom1504** [comment]
@lastuniverse that's cool, I'll try it.
