### ISSUE TITLE
1.8 vanilla client that ping crash the 1.9 nmp server

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#382]
`Error: Deserialization error for handshaking.toServer : Read error for name : 122 is not in the mappings value`

@annoyingcalc got this error.

(not necessarily crash but there are errors)

Not sure how to solve this.

What does the vanilla 1.9 server do ?

**Comment by rom1504** [comment]
Actually I don't understand why.

http://prismarinejs.github.io/minecraft-data/?v=1.9&d=protocol handshake is the same as http://prismarinejs.github.io/minecraft-data/?d=protocol

**Comment by ZudoMC** [comment]
Any further with this? I'm connecting with 1.9.4

**Comment by roblabla** [comment]
Attaching an error handler to the client should avoid the crashing. Does it ?

**Comment by rom1504** [comment]
yeah it does avoid crashing

**Comment by rom1504** [comment]
this is solved now
