### ISSUE TITLE
typo line 49 /minecraft-protocol/node_modules/prismarine-nbt/nbt.js

### ISSUE THREAD

**Issue by xbenng** [PrismarineJS/node-minecraft-protocol#393]
after npm install and and attempting to run proxy.js example, the following error:

/node_modules/minecraft-protocol/node_modules/prismarine-nbt/nbt.js:49
      return value.value.map(v => transform(v,value.type));
                                ^
SyntaxError: Unexpected token >
....
....
....

putting the '>' character before the '=' character fixed the issue.

**Comment by Gjum** [comment]
that is fixed in this patch: https://github.com/PrismarineJS/prismarine-nbt/commit/0c5d2bc6869a2ea2c19bbf4dde7f6028c945a3d1
updating your node modules should fix this

**Comment by rom1504** [comment]
Yeah just run npm install @xbenng 
Using a recent node version would solve that problem too ;)
