### ISSUE TITLE
Decrypt packets directly from a pcap stream, no proxy.

### ISSUE THREAD

**Issue by standayweb** [PrismarineJS/node-minecraft-protocol#401]
I am trying to decrypt packets directly from a pcap stream without using a proxy but having trouble managing to get them to decrypt properly. As you can see I have managed to decrypt them partially, but didn't manage to get much further than this.
```javascript
import pcap from 'pcap2';

const pcapSession = new pcap.Session('en0', {
  filter: 'port 25565',
});

pcapSession.on('packet', (rawPacket) => {
  console.log(rawPacket);
  // PacketWithHeader {
  //   buf: <Buffer 3c 15 c2 d8 35 f8 44 e9 dd 51 30 ea 08 00 45 78 00 39 9a f9 40 00 33 06 f9 68 ad ec 43 0d c0 a8 01 43 63 dd f9 db 86 93 fc 2c 03 4a 0a bd 80 18 00 36 ... >,
  //   header: <Buffer b6 a9 1b 57 a2 16 08 00 48 00 00 00 48 00 00 00>,
  //   link_type: 'LINKTYPE_ETHERNET' }
  console.log(pcap.decode.packet(rawPacket));
  // PcapPacket {
  //   link_type: 'LINKTYPE_ETHERNET',
  //     pcap_header: PcapHeader { tv_sec: 1461430710, tv_usec: 530082, caplen: 72, len: 72 },
  //   payload:
  //     EthernetPacket {
  //     emitter: undefined,
  //       dhost: EthernetAddr { addr: [Object] },
  //     shost: EthernetAddr { addr: [Object] },
  //     ethertype: 2048,
  //       vlan: null,
  //       payload:
  //     IPv4 {
  //       emitter: undefined,
  //         version: 4,
  //         headerLength: 20,
  //         diffserv: 120,
  //         length: 57,
  //         identification: 39673,
  //         flags: [Object],
  //         fragmentOffset: 0,
  //         ttl: 51,
  //         protocol: 6,
  //         headerChecksum: 63848,
  //         saddr: [Object],
  //         daddr: [Object],
  //         protocolName: undefined,
  //         payload: [Object] } },
  //   emitter: undefined }
});
```

**Comment by roblabla** [comment]
Thing is, packets are crypted using AES cipher. You'll need the key to decode them. Simply replaying the stream won't do.

**Comment by standayweb** [comment]
I take it the key is generated on authentication within the minecraft client itself?

**Comment by hansihe** [comment]
Yep, when the server is in online mode a key is generated in the login phase.

There are more details on the authentication and encryption [here](http://wiki.vg/Protocol_Encryption).

**Comment by standayweb** [comment]
Ahh ok thanks, I guess I'll have to use a proxy in some from then unless there is any sort of alternative you can think of?

**Comment by hansihe** [comment]
If you turn the server to offline mode, there will be no encryption.

If that is no doable, a proxy is pretty much your only option.

**Comment by roblabla** [comment]
I'm pretty sure even offline-mode servers use encryption ? At least it used to be that way.

The best way is to get the key from the minecraft client by installing a mod. You may be able to make it show up in the minecraft console without mods by starting minecraft with debug flags, but I'm not 100% sure.

Failing that, proxy is the way to go. Just put the auth at the proxy level. What i've seen people do is make the proxy just do a small bit of loading to get the user in a chatbox, and have them type their username:password || accessToken (if they even know what that is). Then you can use those to log the proxy in.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L180 offline mode servers don't use encryption.
