### ISSUE TITLE
Not compatible with version 1.9.4 

### ISSUE THREAD

**Issue by vincss** [PrismarineJS/node-minecraft-protocol#408]
Hi,
I can't make version 1.9.4 works. I think the protocol need an update.

Thanks for your help.

**Comment by rom1504** [comment]
It is compatible with version 1.9.4. Just write "version":"1.9.4" in the options (of the client or the server)

**Comment by vincss** [comment]
I've tried to do that, it launches an exception when it tries to create the server.

**Comment by rom1504** [comment]
@vincss are your dependencies up to date ? try running npm update

**Comment by vincss** [comment]
Yes, I've run it just before posting the ticket. When I run it with 1.9.2 as version it works ok.

**Comment by roblabla** [comment]
Please give us a stacktrace or the code necessary to reproduce the issue.
Also, the node version would help.
On May 26, 2016 5:47 PM, "Vincs" <notifications@github.com> wrote:

Yes, I've run it just before posting the ticket. When I run it with 1.9.2
as version it works ok.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/PrismarineJS/node-minecraft-protocol/issues/408#issuecomment-221911172>

**Comment by vincss** [comment]
Node Version v5.11.1
My dependencies :
`  "dependencies": {
    "connect": "^3.4.1",
    "dateformat": "^1.0.12",
    "js-yaml": "^3.5.3",
    "minecraft-protocol": "^0.19.4",
    "serve-static": "^1.10.2",
    "winston": "^2.2.0"
  },
  "devDependencies": {
    "node-inspector": "^0.12.5"
  },`

A simple sample like this can reproduce the problem I'm having : 
`var mc = require('minecraft-protocol');

console.log("Begin");

process.on('uncaughtException', function(err) {
	console.log('Caught uncaughtException: ' + JSON.stringify(err));
 });

	var mcServer = mc.createServer({
		'online-mode' : true,
		encryption : false,
		host : '0.0.0.0',
		motd : 'Sample',
		port : '6666',
		version : "1.9.4"});

   
   
console.log("End");   `

When I put 1.9.2, the server is created and listening, when I put 1.9.4 I got :
Caught uncaughtException: {}

**Comment by rom1504** [comment]
I just tried running that exact code with minecraft-protocol 0.19.4 and it works.

**Comment by rom1504** [comment]
it looks like some other part of your code is emiting some error.

**Comment by vincss** [comment]
I've deleted my folder node_modules and reinstalled with version 0.19.6. And now it's working.
