### ISSUE TITLE
Use node's `crypto` module for RSA

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#409]
It seems like nodejs added RSA capabilities to its crypto modules at some point. https://nodejs.org/api/crypto.html#crypto_crypto_privatedecrypt_private_key_buffer .

Using this would avoid people the painful install process. It looks like the browserify folks have a purejs shim for it too. Sadly it doesn't seem to use a vetted library for RSA :(.

**Comment by rom1504** [comment]
Apparently it's there since 0.12 https://nodejs.org/dist/latest-v0.12.x/docs/api/crypto.html
(it's not there in 0.10 https://nodejs.org/dist/latest-v0.10.x/docs/api/crypto.html)
So indeed we could use that.
Could that replace ursa completely ?

**Comment by roblabla** [comment]
Yup. We just need publicEncrypt/privateDecrypt. Only thing is, we'd have to write a bit of code to generate the keys (I don't think node's crypto comes with a key generator) but surely someone already has a module out there to do just that.
