### ISSUE TITLE
Streams don't appear to function properly

### ISSUE THREAD

**Issue by Plazmaz** [PrismarineJS/node-minecraft-protocol#410]
I'm attempting to run mineflayer through a SOCKS proxy by passing the 'stream' option as a raw socket on initializing the bot, and it doesn't appear to work properly. In tcp_dns, the call to client.setSocket does get executed, but the client does not send data past that point, and appears to hang. Here's the code I'm using:
    

```js
var socks = require('socksv5');
var client = socks.connect({
    host: "localhost",
    port: 25565,
    proxyHost: host,
    proxyPort: port,
    auths: [ socks.auth.None() ]
  }, function(socket) {
    console.log("Got socket."); //Is executed.
    callback(socket);
});
function callback(socket) {
  opts.stream = socket;
  bot = mineflayer.createBot(opts);
  bot.on("login", function() {
    console.log("Logged in!"); //Never executed
    })
  bot.on("spawn", function() {
    console.log("Spawned"); //Never executed
  })
  console.log("Called back!"); //Is executed
}
```

**Comment by rom1504** [comment]
I assume you have a proxy socks server running on localhost ?
Can you try enabling debug with `DEBUG="minecraft-protocol"` and see if it displays anything more ?

**Comment by Plazmaz** [comment]
@rom1504 I'm unsure how this can be done on windows machines unfortunately.

**Comment by Plazmaz** [comment]
@rom1504 can you reproduce this?

**Comment by rom1504** [comment]
You didn't answer to 
> I assume you have a proxy socks server running on localhost ?

Is your proxy on the same network as your server ?

**Comment by Plazmaz** [comment]
Oh sorry, yes, the proxy is running on localhost. I've attempted logging into both local servers and external servers, as well as local/external proxies

**Comment by Plazmaz** [comment]
Just realized this is pretty closely related to #185.

**Comment by Plazmaz** [comment]
Found the cause of this issue. The proxy socket never emits a 'connect' event, and thus I needed to force send the login data once the proxy socket callback was triggered. I'll try to make a PR for proxy support in the next few days :smile:
