### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by polkovnikov-ph** [PrismarineJS/node-minecraft-protocol#412]
It still requires `ursa`, unlike `master`.

**Comment by rom1504** [comment]
No it doesn't. Ursa has been an optional dependency for a while and nothing has changed about that since the last npm release.

**Comment by polkovnikov-ph** [comment]
Oh, sorry, didn't expect `npm` to install the version from `package.json` while doing `npm install mineflayer`. That's a [reported problem](https://github.com/Darthfett/helperbot/issues/42) of `helperbot`.
