### ISSUE TITLE
How does the proxy work?

### ISSUE THREAD

**Issue by DigitalSniperz** [PrismarineJS/node-minecraft-protocol#414]
I want to have something like bungeecord but for online servers, I have the players access token which I believe makes it so I can connect to another online server from a online server.

Any clue how to do this?

**Comment by rom1504** [comment]
You can start from the proxy example (https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/proxy/proxy.js) and pass the token there https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/proxy/proxy.js#L98 (see https://github.com/PrismarineJS/node-minecraft-protocol/tree/master/doc#mccreateclientoptions)

**Comment by DigitalSniperz** [comment]
I used your proxy.js and whenever I try to connect to it, I'm getting this,
```
Incoming connection (94.1.13.187)
Connection closed by server (94.1.13.187)
Connection closed by client (94.1.13.187)
```

Command: node proxy.js play.hypixel.net 1.10

**Comment by DigitalSniperz** [comment]
Also regarding the players access token, I'm on the server with my normal minecraft client and I want to be able to send me to a different "ONLINE" server using my access token. Do you know if thats possible?

**Comment by roblabla** [comment]
If the server has the token then yup, that's possible. You'll have to do a lot of work though when switching server.
