### ISSUE TITLE
I USED THIS AND IT CHANGED MY MINECRAFT PASSWORD

### ISSUE THREAD

**Issue by averysumner** [PrismarineJS/node-minecraft-protocol#415]
I used this API and then tried to log into minecraft. It changed my minecraft PASSWORD!!! Luckily I was able to get it back by resetting my password.

**Comment by rom1504** [comment]
It is possible you logged in multiple times using node-minecraft-protocol and mojang decided it was suspicious and decided to reset your password.
Node-minecraft-protocol certainly doesn't change your password !

**Comment by averysumner** [comment]
Possibly...
Sorry about that.
