### ISSUE TITLE
Real IP Proxy

### ISSUE THREAD

**Issue by Papilla-Hitlers** [PrismarineJS/node-minecraft-protocol#431]
How to set real ip for players, that entered via proxy.js proxy?

**Comment by rom1504** [comment]
Where are ips displayed ?

**Comment by Papilla-Hitlers** [comment]
On the game server spigot/craftbukkit. All players have IP proxy server address.

**Comment by roblabla** [comment]
You're going to need to activate bungee cord support in the spigot
configuration and simulate the ip spoofing in proxy.js

**Comment by Papilla-Hitlers** [comment]
`simulate the ip spoofing in proxy.js`
How?

**Comment by roblabla** [comment]
you're going to have to pretty much read the bungeecord source code to figure out how they do it. https://github.com/SpigotMC/BungeeCord/blob/0581e49d49aa3622b1fea1623eb512ab95989e41/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L89

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/CraftBukkit-Patches/0046-BungeeCord-Support.patch

**Comment by Papilla-Hitlers** [comment]
You can help me with this?

**Comment by Papilla-Hitlers** [comment]
And how i can redirect player to another server after connect to first server?

**Comment by roblabla** [comment]
This is a pretty complicated project and I don't really have the time to work on it. I believe there already exists a few attempts at it.

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/302

**Comment by rom1504** [comment]
that's not really a nmp issue
