### ISSUE TITLE
Connecting bot through public socks proxy

### ISSUE THREAD

**Issue by hisdudeness1** [PrismarineJS/node-minecraft-protocol#435]
So, i already looked at node.js docs about stream, sockets and stuff, minecraft protocol docs, issues #410 #320 #312 #185 - and still i dunno how dafuq can i do this. Any examples, links, clues will help. Peace.

**Comment by roblabla** [comment]
For an Http proxy (experimental code, didn't actually try it) :

```
var Http = require("http");
var host = "the.minecraft.server.host.com";
var port = 25565;
var proxy = { address: '192.168.1.1', port: 80 };
var req = Http.request({
  host: proxy.address,
  port: proxy.port,
  method: 'CONNECT',
  path: host + ":" + port
});
req.on("connect", function(res, stream, head) {
  require("minecraft-protocol").createClient({
    stream: stream,
    username: "bleh",
    password: "bleh"
  });
});
```

**Comment by roblabla** [comment]
for a socks proxy (again experimental, didn't try it) : 

```
var Socks = require("socks5-client");
var proxyOpts = { host: '192.168.1.1', port: 7777 };
require("minecraft-protocol").createClient({
  stream: Socks.createConnection(proxyOpts),
  username: "bleh",
  password: "bleh"
});
```

**Comment by roblabla** [comment]
Closing in favor of #185 .

**Comment by rom1504** [comment]
for anyone coming here, https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js is the up to date example
