### ISSUE TITLE
Doesnt work on 1.10 servers

### ISSUE THREAD

**Issue by DaAwesomeRazor** [PrismarineJS/node-minecraft-protocol#443]
was testing it out and it didnt work on any of the 1.10 servers

**Comment by ReduxRedstone** [comment]
You may wan't to provide some more information. Things like your setup and any errors. Because I can confirm this does work with 1.10 servers, as I have made a chat client using it for 1.10 servers. By default I believe it defaults all clients to 1.8, so you have to manually set the version.
```javascript
var client = mc.createClient({
    username: "email",
    password: "password",
    host: "localhost",
    port: 25565,
    version: "1.10.2"
});```

**Comment by rom1504** [comment]
reopen if you have more information

**Comment by DaAwesomeRazor** [comment]
@ReduxRedstone I added the 1.10.2, and im still getting problems. The client is not receiving or sending chat

**Comment by ReduxRedstone** [comment]
@DaAwesomeRazor could you provide some of your code maybe? Like I said I know for a 100% fact that this works on 1.10 servers, so it must be something wrong in your code.
