### ISSUE TITLE
Does not work with minecraft 1.11

### ISSUE THREAD

**Issue by Quezler** [PrismarineJS/node-minecraft-protocol#446]
![screen shot 2016-11-14 at 17 03 06](https://cloud.githubusercontent.com/assets/3179271/20271806/40fdcba4-aa8c-11e6-80a4-725966e3298e.png)

**Comment by roblabla** [comment]
The update was released a few hoursr ago XD.

We need to reverse engineer the new protocol, update the documentation, implement the changes in `minecraft-data` and maybe modify nmp to take into account any big protocol changes that occured. Depending on how many changes this update contains, it might take some time (from hours to months :D).

**Comment by Quezler** [comment]
I know, but someone had to make the issue sooner or later 😄

**Comment by rom1504** [comment]
http://wiki.vg/index.php?title=Pre-release_protocol&oldid=8249

**Comment by rom1504** [comment]
and done (proved by https://circleci.com/gh/PrismarineJS/node-minecraft-protocol/687), just run npm update.
