### ISSUE TITLE
Keep getting kicked

### ISSUE THREAD

**Issue by Draem** [PrismarineJS/node-minecraft-protocol#447]
Whenever I join a server, my account only stays on for a minute, then gets disconnected.

**Comment by roblabla** [comment]
What server version, what server software, and if it's a public server, can you give us the IP so we can test ?

**Comment by ReduxRedstone** [comment]
This sounds like a similar issue to the one I was having. I fixed it by using this fork https://github.com/roblabla/node-minecraft-protocol/tree/8c02735af1fbe2b9b98e56824f838871ab2eb678 Of the protocol

**Comment by rom1504** [comment]
now fixed in 1.1.1
