### ISSUE TITLE
Application stops dead in its tracks (On Spigot)

### ISSUE THREAD

**Issue by MilesAmadeusPrower** [PrismarineJS/node-minecraft-protocol#450]
I'll explain myself in clear detail. I found the application runs on any server which is purely vanilla. However, it's no help to me, because I'm not on vanilla servers. Naturally, I dissected every packet my application gets before leaving by calling `client.on('packet',readPacket(packet));`

In a nutshell, readPacket performs a "for (key in packet)" loop to display every detail in console.log

The startup packets come up, and then the application stops dead in its tracks after the 5th packet, reading:
`At packet [object Object] => {`
`  channel=REGISTER`
`  data=WECUI Bungeecord`
`}`

I performed a test run on a pure vanilla server, and the same channel packet passed, spamming hundreds of lines of in-game packets, reading the server's entities. This is the packet I found after lots of scrolling:
`At packet [object Object] => {`
`  channel=REGISTER`
`  data=vanilla`
`}`

I looked everywhere in the module, and found the registerChannel function. It was quite vague and lacked any way to explain why it crashed. I learned it does the same thing when adding minecraft-protocol-forge.

Is there a method to fix this problem, or has the fix yet to be found?

**Comment by rom1504** [comment]
Can you try with the last commit from master and see if it fixes the problem (thanks to #434) ?

**Comment by MilesAmadeusPrower** [comment]
After copying the new module onto the old module, and running app.js again, the error still persists.
I will look into the source of the problem some more.

**Comment by rom1504** [comment]
you need to run npm install in the "new module"

**Comment by MilesAmadeusPrower** [comment]
After some trial and error on learning how to install a module on my computer, it seems like some new things came up. It has indeed passed the registerChannel packet.

**Comment by rom1504** [comment]
fix released in 1.1.1
