### ISSUE TITLE
Movement (writing position) not working in 1.10

### ISSUE THREAD

**Issue by ReduxRedstone** [PrismarineJS/node-minecraft-protocol#451]
I have been trying for several days to get the client to move in 1.10 and simply cannot get it to work, and after some testing it looks like something to do with 1.9/1.10. The "position" packet doesn't seem to be written correctly in the newer versions. Even using the code found [here](https://github.com/PrismarineJS/node-minecraft-protocol/wiki/Walking-in-straight-line), line for line exactly the same, the client does not move in 1.10 (I have not tested in 1.9). I went down to 1.8 and tested the same exact code, no changes, and the client moves as expected.

The code doesn't seem to be wrong, since no errors are thrown and using `.on` it still logs that the packet was sent. The client just refuses to move in newer versions.

Any ideas as to why? Did something change?

**Comment by KingLycosa** [comment]
I am pretty sure it has something to do with the chunk changes they did in 1.9

Try it with 1.9 and see if you still can't move, if you can then its something 1.10 added and you should check the protocol changes

**Comment by ReduxRedstone** [comment]
@KingLycosa I just tested it in 1.9, no movement at all. Same issue as running the script in 1.10

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/wiki/Walking-in-straight-line is very old (last update in 2014, probably around minecraft 1.7)
Try running the proxy to see how to move in mc >=1.9

**Comment by rom1504** [comment]
That works fine in mineflayer (which uses nmp between 1.9 and 1.11)
