### ISSUE TITLE
Fix online auth

### ISSUE THREAD

**Issue by eaaliprantis** [PrismarineJS/node-minecraft-protocol#452]
Would you be able to assist, because i keep getting this error when my credentials are correct, 1.11 isn't fully working yet :/

events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Invalid credentials. Invalid username or password.)
    at Client.emit (events.js:163:17)
    at cb (/home/eaaliprantis/node_modules/minecraft-protocol/dist/client/caseCorrect.js:16:18)
    at /home/eaaliprantis/node_modules/yggdrasil/lib/index.js:59:7
    at Request._callback (/home/eaaliprantis/node_modules/yggdrasil/lib/index.js:30:9)
    at Request.self.callback (/home/eaaliprantis/node_modules/yggdrasil/node_modules/request/request.js:121:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/eaaliprantis/node_modules/yggdrasil/node_modules/request/request.js:978:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)

**Comment by rom1504** [comment]
Do you get that error every time or does it work sometimes ?

**Comment by eaaliprantis** [comment]
I was never able to get it to work.  This is only returned when i remove the password:

Successfully connected to 104.131.168.129:41735
disconnected: {"text":"Outdated client! Please use 1.11"}

**Comment by rom1504** [comment]
Did you put "version":"1.11" in the createClient options ?

**Comment by eaaliprantis** [comment]
So i added the "version": "1.11" in the createClient and it returned the following:
Successfully connected to 104.131.168.129:41735
disconnected: {"text":"Failed to verify username!"} - - my username is correct

**Comment by rom1504** [comment]
Confirmed. I guess this is due to yggdrasil 0.2.0, I didn't check after upgrading it. Will fix.

**Comment by rom1504** [comment]
Actually no, it works for me. I tested with the wrong password.

Did you try to connect many time with that account ?

**Comment by eaaliprantis** [comment]
Yeah, i tried with that particular account.  I can connect fine with it via the regular Minecraft client.

**Comment by rom1504** [comment]
I just published a new release (1.1.1) with the last commits from master, @eaaliprantis can you check whether it fixes your problem ?

**Comment by eaaliprantis** [comment]
It keeps weirdly invalidating for me.  I don't understand why.  I just bought a recently new account as well and can log in fine to my server via the Desktop Client but not through the nodejs one :(

**Comment by eaaliprantis** [comment]
So i just bought a new account (and the game), the password had 1 uppercase letter and the rest numbers and letters, but still it keeps denying it on the same server as where the server is being hosted.

**Comment by eaaliprantis** [comment]
So what i'm understanding is that the email (username) needs to be less than 16 characters since the max length is longer than the maximum allowed (username: eaaliprantis6959@gmail.com) - - the email is 26 characters long (26 > 16), which is returned by the io.netty.handle.codec.DecoderException.  Are you able to assist or help me debug?

**Comment by rom1504** [comment]
My email is 28 character long so I can confirm there is no 16 characters limit.

Are you sure you are using the last version of nmp ? (try to remove the node_modules dir and run npm install again)

**Comment by rom1504** [comment]
Also, could you try a different server ?
And maybe come in gitter (see the readme) if you can to talk about it ;)

**Comment by eaaliprantis** [comment]
I mean if you have a test server that i can connect to, that would be great. Otherwise, i am thinking that the problem lies within the .jar file
The latest version that i have (npm install minecraft-protocol) is: 1.1.1
I can join gitter soon :)

**Comment by eaaliprantis** [comment]
Closed to due possible IP banned on VPS server
