### ISSUE TITLE
Specify required nodejs version

### ISSUE THREAD

**Issue by ooxi** [PrismarineJS/node-minecraft-protocol#453]
When running the [`echo.js`](https://github.com/PrismarineJS/mineflayer/blob/master/examples/echo.js) demo I got the following exception

```
$ nodejs echo.js localhost 25565

.../node_modules/minecraft-protocol/dist/transforms/framing.js:112
          } else throw e;
                       ^
TypeError: Object REGISTER,UNREGISTER,MC|TrSel,MC|TrList has no method 'find'
    at Client.onCustomPayload (.../node_modules/minecraft-protocol/dist/client/pluginChannels.js:45:28)
    at Client.EventEmitter.emit (events.js:98:17)
    at Parser.<anonymous> (.../node_modules/minecraft-protocol/dist/client.js:101:16)
    at Parser.EventEmitter.emit (events.js:95:17)
    at readableAddChunk (.../node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at Parser.Readable.push (.../node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at Parser.Transform.push (.../node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at Parser._transform (.../node_modules/protodef/dist/serializer.js:88:14)
    at Parser.Transform._read (.../node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Parser.Transform._write (.../node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

The [code in question](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client/pluginChannels.js#L46) calls `find` on an `channels` which happens to be an array. Thus the desired function is [Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), not available in my nodejs version.

Updating nodejs did solve the problem:

 * Version not working: v0.10.25
 * Version working: v4.2.6

Please specify the required nodejs version or use an ES6 shim in order to avoid such confusion :)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/package.json#L27

**Comment by rom1504** [comment]
But, we are using babel.
So I'm surprised it didn't add that shim automatically, I guess we should do something about it.

**Comment by ooxi** [comment]
Wow, you're fast :+1: 

I actually saw that line, but maybe we should use [`engine-strict`](https://docs.npmjs.com/files/package.json#enginestrict) instead, since the could does not run without an older version of nodejs?

**Comment by roblabla** [comment]
Problem with engine-strict is that it'd require us to actually test engines, or to arbitrarely set engines as incompatible without testing support. I always test stuff on the latest LTS at the very least, but anything before that is up to luck, mostly. I expect everyone to at least use latest LTS, anything before that doesn't exist to my eyes.

And debian deserves a slow painful death for still packaging nodejs 0.10.

**Comment by ooxi** [comment]
I personally do not see a problem with such an approach since technologies like docker enable access to the latest software on almost any platform. Nevertheless since `node-minecraft-protocol` is a fairly low level library it should not dictate a stricter environment than really necessary.

Maybe we should execute the tests on multiple node versions and strictly require the lowest passing engine?

**Comment by roblabla** [comment]
Currently, the tests are being run on nodejs 4 according to [circle.yml](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/circle.yml#L5).

I guess we could set engine-strict to whatever is the lowest we have in circle.yml at any point in time.

**Comment by rom1504** [comment]
the way we specify it is the correct way (https://docs.npmjs.com/files/package.json#engines) engineStrict is depreciated since npm 3
