### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by KaidenP** [PrismarineJS/node-minecraft-protocol#454]
I've ben working on my own project, a proxy that allows plugins on vanilla servers, But I am faced with an issue, Skins don't seem to show using the proxy.

**Comment by rom1504** [comment]
Yeah there are some stuff to do to make a proxy working properly.
Including rewriting between online and offline uuids that way
https://github.com/rom1504/node-minecraft-proxies/blob/master/proxy.js#L127
I guess we should put this in a FAQ or something (or finally do that proxy
lib (?))

**Comment by KaidenP** [comment]
Thanks! will try l8ter. Just to note for myself, this is important too: https://github.com/rom1504/node-minecraft-proxies/blob/master/proxy.js#L105
