### ISSUE TITLE
[in some servers] unexpected end of file

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#462]
same as https://github.com/PrismarineJS/mineflayer/issues/431

reproductible using client_echo.js on `mc.desiredcraft.net`
There might be something specific about this server.

**Comment by mcparadip** [comment]
Has this been fixed?

**Comment by rom1504** [comment]
The issue is still open, so no.
If you have more information on what kind of server it happens in, please provide it, it might be useful ;)

**Comment by mcparadip** [comment]
It happens in

    play.cascademc.net
    mc.momentonetwork.net

I don't know if this is related, but on these servers, it gives me `Killed`:

    mc.hypixel.net
    play.luckyprison.com
    mineagon.com
    play.primemc.org

**Comment by rom1504** [comment]
So there error is from https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/compression.js#L64

If I just ignore that chunk (return cb() instead of return cb(err)) everything else seems to work.

I don't really understand why these servers send us malformed compressed packet and I don't know what we should do about it...

**Comment by rom1504** [comment]
Or maybe we are doing something wrong in some edge cases in the splitter ?

**Comment by johnpyp** [comment]
Getting the same error with multiple different servers. The main one I am on is pvp.desteria.net

**Comment by roblabla** [comment]
Unexpected EOF means the packet was not complete when passed to `zlib.inflate` (it's missing data). It's very very odd, and I'm not sure it's a good idea to ignore it. Maybe we should log the length of the chunk being passed in https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/compression.js#L21 to make sure the splitter doesn't fk up and send something the wrong size (maybe node streams split the packet or something ?)

**Comment by codingJWilliams** [comment]
I'm getting this error with this code:
```
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "pvp.thearchon.net", // optional
  port: 25565,       // optional
  version: "1.10.2",
  username: "[REDACTED]", // email and password are required only for
  password: "[REDACTED]",          // online-mode=true servers
});
bot.on("kicked", (reason, a) => { console.log(reason) })
```

**Comment by roblabla** [comment]
🤔 I really should take a look at bungeecord when I have some time. I'll try to find some time to get some TCP dumps over the week-end.

**Comment by codingJWilliams** [comment]
Thanks mate :-)

**Comment by rom1504** [comment]
can be reproduced on pvp.thearchon.net too

would be nice to fix it

**Comment by rom1504** [comment]
Ok I ignored the packet and logged the error.
I believe some servers do send wrong packets and the bug is their's.

Let's continue track weird servers in #532 and consider this particular ticket as done.
