### ISSUE TITLE
Allow a server to support multiple minecraft versions

### ISSUE THREAD

**Issue by CapitaineGloomy** [PrismarineJS/node-minecraft-protocol#480]
Hello,

Can we accept all versions of minecraft?
I want to create an identity verification server for my site

**Comment by rom1504** [comment]
What do you mean by identify verification server ? 

You might be interested by https://github.com/deathcap/node-minecraft-ping

**Comment by FavreNicolas** [comment]
The user logs on to the server to retrieve a code that he must enter on the site to link are minecraft account on are account site !!

**Comment by rom1504** [comment]
Ok. How is this related to node-minecraft-protocol ?

**Comment by roblabla** [comment]
@rom1504 he wants the user to connect to an NMP server on which the user would be asked to send a code via chat message. The server would then be able to link a forum user to a mojang user.

@FavreNicolas it's theorically possible to make a minecraft server that accepts all supported minecraft version (which is all stable versions between 1.7 and 1.12 AFAIK). Unfortunately, it is not supported yet and requires some changes to the NMP library.

The server component is in a major need of some refactoring, similar to what we did to the client component. I'll try to see if I can do something about it.

**Comment by FavreNicolas** [comment]
@roblabla Yes code send on chat for link on website

**Comment by rom1504** [comment]
tracked at #234 (server cross version support)
