### ISSUE TITLE
 Add proxy support to the auth requests

### ISSUE THREAD

**Issue by luluwebmaster** [PrismarineJS/node-minecraft-protocol#481]
It would be nice to add proxy support to the auth requests, avoiding mojang's stupid IP bans. This requires making changes to node-yggdrasil.

Original comment :

> Hello,
> 
> I want to createClient ( Connect a client to the Auth Mojang API ) with a proxy, but I don't knowhow to do it :-/
> 
> I have test differents code found in Google, but none work :-/
> 
> Can you help me ?
> 
> ( Sorry for my bad English, I'm French ;) ) 
> 
> Thank you !

**Comment by roblabla** [comment]
Hey, nous aussi on est francais :)

Tu peux voir des solutions de code ici : https://github.com/PrismarineJS/node-minecraft-protocol/issues/435

T'as des examples de code concret qui ne fonctionnent pas ?

**Comment by luluwebmaster** [comment]
Ha cool ça ha ha 👍 

Du coup je réexplique le problème en Français, car je ne suis pas trop sur de mon Anglais xD

En gros, j'aimerais exécuter la requête d'Auth ( API Mojang ) ( createClient ) sous un proxy.
Car ( Je ne sais pas pourquoi ), je n'arrive plus à me connecter à n'importe quel compte MC sur l'IP de mon VPS ( Surement IP bloqué ou je ne sais quoi ).

Du coup est-ce que c'est possible ça ? ^^

J'ai déjà pu voir / tester le lien que tu m'a donnée, mais sans succès :-/

Merci à toi ;)

**Comment by rom1504** [comment]
Sans succès c'est à dire ? Qu'est-ce que tu as comme erreurs ?

**Comment by luluwebmaster** [comment]
Erreur Mojang : 

https://i.luwe.fr/13196086.png

( Les identifiants sont bon ;) )

**Comment by rom1504** [comment]
Ah oui on utilise https://github.com/zekesonxx/node-yggdrasil pour l'authentification. Il faudrait ajouter le support du proxy pour ça.

**Comment by luluwebmaster** [comment]
Ce serait génial parce-que pour le moment, j'ai un super service, mais que je ne peux pas lancer étant donné que l'Auth ne fonctionne pas 😂

**Comment by luluwebmaster** [comment]
Bonsoir,

Du  coup actuellement ce n'est pas possible de faire comme ça ? ^^

**Comment by rom1504** [comment]
Si il suffit d'ajouter la fonctionnalité à la librairie.

**Comment by luluwebmaster** [comment]
Hum, modifier directement le code du module "yggdrasil" ?

**Comment by roblabla** [comment]
So I thought about this. NMP side, we already have a few things in place (although documentation seems to be lacking). We have two ways to connect with NMP : 

- Username/password combo. In this case, we make a simple connection with the node-yggdrasil library [here](https://github.com/PrismarineJS/node-minecraft-protocol/blob/35dcd922342a982a4aa7a418719ed77bccdec3c5/src/client/caseCorrect.js#L33-L37)
- Session object. This is the object that is given to us by node-yggdrasil. With this system, you can handle and customize the auth process. NMP still does API calls to yggdrasil to validate and refresh the token if necessary. [here](https://github.com/PrismarineJS/node-minecraft-protocol/blob/35dcd922342a982a4aa7a418719ed77bccdec3c5/src/client/caseCorrect.js#L24-L31).

I don't know if those APIs are IP-banned as well. I would guess not, but it's just a guess. If they are banned as well, we'll have to create a `skipValidate` flag to the createClient options, that allows using a session object without doing any validation on them.

So what needs to be done is adding proxy support to node-yggdrasil. That should be an easy task, node-yggdrasil uses [`request`](https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/utils.js#L16), which supports proxies [(ici)](https://github.com/request/request#proxies).

Then, you could use the code all the way at the bottom of this post.

------------------------------

Bon alors j'ai reflechis un peu a ca. En gros, cote NMP, on a deja quelques trucs en place (quoique mal documente). On a deux manieres de se connecter avec NMP : 

- Combo username/password. Auquel cas, on fait une simple connection avec la bibliotheque node-yggdrasil [ici](https://github.com/PrismarineJS/node-minecraft-protocol/blob/35dcd922342a982a4aa7a418719ed77bccdec3c5/src/client/caseCorrect.js#L33-L37)
- Objet session. En gros, c'est l'objet qui est renvoye par node-yggdrasil. Ca permet de gerer et customiser soi-meme l'auth. On fait quand meme des appels a l'API yggdrasil pour verifier que le token soi bon, et le rafraichir si ce n'est pas le cas. [ici](https://github.com/PrismarineJS/node-minecraft-protocol/blob/35dcd922342a982a4aa7a418719ed77bccdec3c5/src/client/caseCorrect.js#L24-L31)

Je ne sais pas si ces APIs sont bloques aussi par les addresses IP. Je suppose que non, mais c'est une supposition. Si c'est le cas, il faudrait creer un flag "skipValidate" qui utilise directement la session sans la valider/rafraichir.

Du coup, ce qu'il faut faire, c'est ajouter le support proxy a node-yggdrasil. C'est relativement facile, node-yggdrasil utilise [`request`](https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/utils.js#L16) qui supporte les proxy [(ici)](https://github.com/request/request#proxies).

Ensuite, tu pourrais faire un truc de ce style : 

```javascript
var ygg = require('yggdrasil')({});
ygg.auth({
    user: 'whatev',
    password: 'whatev',
    proxy: 'somethingsomething'
}, function(err, session) {
    if (err) throw err;
    nmp.createClient({ session: session, /* everything else */ });
});
```

**Comment by luluwebmaster** [comment]
Hello,

Hum je viens de tester d'ajouter le proxy directement comme ça : 
`  var request = require('request').defaults({
    headers: {
		'proxy':'52.187.214.235:8888',
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });`

Ça ne fonctionne pas :-/

**Comment by luluwebmaster** [comment]
Hello,

Hum bon après beaucoup de tests, je n'arrive pas à faire fonctionner un proxy avec le module Request :-/

Voici mon dernier test en date : 
```
  var request = require('request').defaults({
	 proxy: 'http://user:password@211.79.61.8:3128',
    headers: {
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });
```

J'ai récupéré l'IP du proxy [ici](http://freeproxylists.net/fr/?s=u).

Et qui me donne cette erreur : 

`Error: tunneling socket could not be established, statusCode=403`

Je ne sais plus trop ou aller ( Tester ) là :-/

**Comment by roblabla** [comment]
Tes proxy sont down. Essais-en d'autres, host tes propres proxy pour etre sur qu'ils fonctionnent, ou utilise des proxy payants.

**Comment by luluwebmaster** [comment]
Pas d'après le site pourtant :o

J'ai essayé de faire mon propre proxy ( Sur une autre machine du coup ), avec node et [ce](https://github.com/rse/node-http-proxy-simple) module, la aucune erreur du coté de mon app, mais une erreur du coté de du serveur proxy : 

`HTTP error: CONNECT method not supported`

**Comment by roblabla** [comment]
Ca c'est un proxy d'interception, ils fonctionnent pas vraiment parreil. Y'a 3 types de proxy : 

- CONNECT proxy
- HTTP proxy
- SOCKS proxy

Le module que tu as utilsie est un proxy HTTP. Request a essaye de se connecte comme si c'etais un proxy CONNECT. Je cherche voir comment il fonctionne.

**Comment by luluwebmaster** [comment]
Ha d'accord pardon ^^

D'accord merci 👍

**Comment by roblabla** [comment]
Je dois y aller, mais je chercherais du cote de node-http-proxy. Ca a l'air d'etre le standard de facto pour les proxy.

**Comment by luluwebmaster** [comment]
Ok ok, pas de problème, je continu de cherche de mon coté ( On ne sait jamais ).

Merci à toi ;)

**Comment by roblabla** [comment]
Re. Try this : https://github.com/TooTallNate/proxy. Or just use squid or privoxy as a proxy server (that's what most public proxies use out there).

**Comment by luluwebmaster** [comment]
Hum, ok,

Et au niveau du module Request je dois mettre quoi du coup ?

Parce-que la j'ai essayé avec le code précédent, ça ne fonctionne pas :-/

**Comment by roblabla** [comment]
En theorie :

```
  var request = require('request').defaults({
	 proxy: {
		 hostname: 'ip',
		 port: 3128
	 },
    headers: {
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });
```

**Comment by luluwebmaster** [comment]
Hum, ok donc après tests l'Auth fonctionne correctement ! 👍 

Maintenant nouveau problème, la connexion au serveur ne fonctionne plus lol.

**Comment by luluwebmaster** [comment]
Hum après avoir encore testé beaucoup de choses, je viens de me rendre compte que la méthode 
https://github.com/PrismarineJS/node-minecraft-protocol/issues/435 retourne une erreur au bout de 20 à 30 secondes que voici : 

```
Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by roblabla** [comment]
Je pense que c'est encore ton proxy qui deconne. Il doit abandonner les connections de longue duree. T'as besoin d'utiliser un proxy pour la connection au serveur ?

**Comment by luluwebmaster** [comment]
Bah si le fait de ne pas avoir la même IP à l'authentification et à la connexion au serveur, alors non ^^

Mais le truc c'est que même sans passer par le proxy, la connexion au serveur ne fonctionne pas :-/

**Comment by luluwebmaster** [comment]
Donc oui, le problème vient bien du fait que je ne suis pas authentifié avec l'IP de la machine ( Pas le proxy ), voila le retour du paket reçus avant la fin de l'instance : 

```
{ serverId: '38b99614d2997146',
  publicKey: <Buffer 30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 b6 25 d4 a8 fd 3e f9 57 e1 5d 6f d0 29 cb 8f da 5c 9b 09 f0 86 ... >,
  verifyToken: <Buffer 56 64 6a db> }
{ reason: '{"extra":["Not authenticated with ",{"clickEvent":{"action":"open_url","value":"http://Minecraft.net"},"text":"Minecraft.net"}],"text":""}' }
```

**Comment by roblabla** [comment]
Ca m'etonne vraiment. Le serveur ne fait aucune verification par IP. Suffit de voir l'API de mojang : http://wiki.vg/Protocol_Encryption#Authentication , elle ne donne aucune information sur l'IP qui a fait l'appel a authenticate. Et quant a validate/refresh, j'ai deja fais des test ou je passais mes tokens d'une machine a l'autre, ca fonctionne.

Je pense que tu dois merder quelque part plutot :P. Tu pourais me detailler ton setup et me filer le code que tu utilises pour que je puisse tester ?

**Comment by luluwebmaster** [comment]
Voila un résumé de mon code : 

app.js ( Installer minecraft-protocol ) : 

```
//Minecraft protocol
mc = require('minecraft-protocol');

//Minecraft instances
minecraftInstances = {};

//Start instance
minecraftInstances['{user-uuid}'] = mc.createClient({
	host: "mc.hypixel.net",
	version: 1.9,
	port: 25565,
	username: '{mail}',
	password: '{password}'
});

//End of instance
minecraftInstances['{user-uuid}'].on('end', function() {

	//Log
	console.log('> End of instance !');
});

//Log
console.log('> Serveur started !');
```
Dans le fichier "~yggdrasil/lib/index.js", ajouter aux deux "var request = require('request').defaults" le proxy : 

```
	var request = require('request').defaults({
		proxy: {
			hostname: '192.168.1.2',
			port: 8000
		},
		headers: {
			'User-Agent' : 'node-yggdrasil/' + version,
			'Content-Type' : 'application/json'
		}
	});
```

Et voila ;)

**Comment by roblabla** [comment]
Et tu utilise quel logiciel pour faire le proxy ? TooTallNate/proxy ?

**Comment by luluwebmaster** [comment]
Le module que tu m'avais link : 

```
var http = require('http');
var setup = require('proxy');

var server = setup(http.createServer());
server.listen(8000, function () {
  var port = server.address().port;
  console.log('HTTP(s) proxy server listening on port %d', port);
});
```

**Comment by luluwebmaster** [comment]
Hello,

Du coup pas d'idées ? :-/

**Comment by luluwebmaster** [comment]
Du coté de Mojang, il ne peuvent rien faire pour débloquer mon IP :-/

**Comment by roblabla** [comment]
DSL, je suis un peu occupe en ce moment. J'essaierai de regarder ce we.

**Comment by luluwebmaster** [comment]
Ok ok, pas de soucis, merci à toi !

**Comment by luluwebmaster** [comment]
Bonjour,

Hum du coup ? :p

( Désolé si j'embête ^^ )

**Comment by luluwebmaster** [comment]
Hello,

Problème toujours d'actualité ^^

**Comment by luluwebmaster** [comment]
Bonsoir,

Je remonte, le problème est toujours d'actualité :-/

**Comment by rom1504** [comment]
@luluwebmaster tu peux essayer de régler le problème ;)
Par exemple essaye avec un serveur vanilla en local

**Comment by luluwebmaster** [comment]
Hum, tu pense que le problème pourrait venir du serveur ?
Parce-que la l'erreur nous dit que je ne suis pas connecté ^^

**Comment by rom1504** [comment]
@luluwebmaster c'est possible.
Ce que je veux dire c'est que si tu essayes avec des conditions plus simples, tu as plus de chances de trouver le problème.

**Comment by luluwebmaster** [comment]
Je comprend bien, mais ça me parait étrange que ça vienne du serveur, étant donné que le serveur en question c'est Hypixel ^^

**Comment by rom1504** [comment]
Oui justement ce serveur n'est pas du tout standard il me semble, et a peut être des protections contre les proxy.
Bref, si tu essayes dans des conditions simples, tu peux trouver le problème.

**Comment by luluwebmaster** [comment]
Ok ok, je vais voir ce que je peux faire, mais j'ai peur de ne pas pouvoir trouver la solution ( Je ne suis pas un expert sur le fonctionnement technique de Minecraft ( Java ) ^^

**Comment by luluwebmaster** [comment]
@rom1504 Hum, j'vais essayer de repartir sur un truc propre.

Il y'a besoin de quel type de proxy normalement ?

**Comment by rom1504** [comment]
http ou socks
https://github.com/PrismarineJS/node-minecraft-protocol/issues/185#issuecomment-254785390

**Comment by luluwebmaster** [comment]
Bon j'en peux plus là xD

J'essais de faire tourner un serveur [Socks5](https://github.com/mscdex/socksv5), impossible de me connecter dessus, je pense que je vais laisser tomber tout ça parce-que la c'est trop le bordel :-/

**Comment by luluwebmaster** [comment]
@rom1504 Bon après encore quelques heures passées, on avance x)

Du coup la j'ai un proxy qui tourne bien en Socks5 ( Testé ), mais du coup maintenant, en suivant le lien que tu ma link, j'ai toujours l'erreur "Error: Invalid credentials. Invalid username or password." ( Toutes les informations entrées sont valides et fonctionnent ;)


```
var Socks  = require("socks5-client");

//Start instance
minecraftInstances[clientUUID] = mc.createClient({
	stream: Socks.createConnection({
		host: serverIp,
		port: 25565,
		socksHost: proxySettings.hostname,
			socksPort: proxySettings.port
		}),
		version: minecraftVersion,
		username: id,
	password: password
});
```

**Comment by luluwebmaster** [comment]
@rom1504 Hum, je remonte ^^

**Comment by rom1504** [comment]
l'identification avec proxy marche sans problème quand tu utilises directement https://github.com/zekesonxx/node-yggdrasil ?

**Comment by luluwebmaster** [comment]
Yop,

J'ai testé ça : 

```
//Authenticate a user
var Socks  = require("socks5-client");
ygg.auth({
	stream: Socks.createConnection({
		host: serverIp,
		port: 25565,
		socksHost: proxySettings.hostname,
		socksPort: proxySettings.port
	}),
  agent: 'Minecraft', //Agent name. Defaults to 'Minecraft'
  version: 1, //Agent version. Defaults to 1
  user: '', //Username
  pass: '' //Password
}, function(err, data){

	console.log(err);
	console.log(data);
});
```

Même erreur ^^

**Comment by luluwebmaster** [comment]
Ha mince, autant pour moi, du coup nouveaux tests : 

```
//Authenticate a user
var Socks  = require("socks5-client");
ygg.auth({
	proxy: {
		host: proxySettings.hostname,
		port: proxySettings.port
	},
  agent: 'Minecraft', //Agent name. Defaults to 'Minecraft'
  version: 1, //Agent version. Defaults to 1
  user: '', //Username
  pass: '' //Password
}, function(err, data){

	console.log(err);
	console.log(data);
});
```

```
//Authenticate a user
var Socks  = require("socks5-client");
ygg.auth({
	proxy: 'http://user:password@'+proxySettings.hostname+':'+proxySettings.port,
  agent: 'Minecraft', //Agent name. Defaults to 'Minecraft'
  version: 1, //Agent version. Defaults to 1
  user: '', //Username
  pass: '' //Password
}, function(err, data){

	console.log(err);
	console.log(data);
});
```

```
//Authenticate a user
var Socks  = require("socks5-client");
ygg.auth({
	proxy: 'http://'+proxySettings.hostname+':'+proxySettings.port,
  agent: 'Minecraft', //Agent name. Defaults to 'Minecraft'
  version: 1, //Agent version. Defaults to 1
  user: 'lenny1842002@gmail.com', //Username
  pass: 'Motdepasse1.' //Password
}, function(err, data){

	console.log(err);
	console.log(data);
});
```

Ces 3 tests donnent toujours le même résultat :-/

**Comment by rom1504** [comment]
Tu as ajouté le support de l'option proxy dans yggdrasil ?

**Comment by luluwebmaster** [comment]
Ha, décidément ... x)

Nouvelle erreur du coup :')

```
{ Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 1080 1080:80
    at ClientRequest.onError (\node_modules\tunnel-agent\index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

**Comment by luluwebmaster** [comment]
```
 //Proxy settings
proxySettings = '90.50.51.190:1080';
```

yggdrasil/lib/index.js :

```
 var request = require('request').defaults({
	 proxy: proxySettings,
    headers: {
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });
```

**Comment by rom1504** [comment]
Il semble que request (https://github.com/request/request) n'accepte que les proxy http, alors essaye avec un proxy http pour request

**Comment by luluwebmaster** [comment]
Ha ! Donc là ça fonctionne ( Au niveau de "yggdrasil" ), c'est déjà ça ! 👍 

Mais du coup, j'ai encore [mon ancien problème](#issuecomment-294324385) :-/

**Comment by luluwebmaster** [comment]
Tu me confirme que ce proxy fonctionne bien en http : http://90.50.51.190:8000 ?

**Comment by luluwebmaster** [comment]
@rom1504 @roblabla Pas d'idées du coup ? ^^

**Comment by rom1504** [comment]
@luluwebmaster est ce que tu peux mettre ton code entier dans un https://gist.github.com/ pour que ce soit facile à tester ?
(et faire une branche et une PR sur yggdrasil ajoutant la fonctionnalité de proxy)

**Comment by luluwebmaster** [comment]
Hum je ne gère pas trop GitHub, et je ne souhaite pas publique le contenu de mon application ;)

Cependant, le l'utilisation code au niveau même de Minecraft Protocol est des plus simple ( L’application fonctionne sur une IP non bloqué par Mojang )  : 

```
//Proxy settings
proxySettings = 'http://{ip}:{port}';

//Minecraft version
minecraftVersion = 1.9;

//Minecraft protocol
mc = require('minecraft-protocol');

//Minecraft instance
minecraftInstances = mc.createClient({
	host: "mc.hypixel.net",
	port: 25565,
	version: minecraftVersion,
	username: {user},
	password: {pass}
});
```

Et coté yggdrasil j'ai juste fais une intégration à "l'arrache" :

```
/* jshint node: true */
'use strict';
var crypto = require('crypto');
var assert = require('assert');
var request = require('request');
var uuid = require('uuid');
var version = require('../package.json').version;

var k = function Yggdrasil (con) {
  var config = {
    host : con.host || 'https://authserver.mojang.com' //Allow for a custom auth server
  };

  var request = require('request').defaults({
	 proxy: proxySettings,
    headers: {
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });

  var r = {};
  r._call = function (path, data, cb) {
    request({
      method: 'POST',
      uri: config.host + '/' + path,
      json: data
    }, function (err, resp, body) {
      if (body && body.error) {
        cb(new Error(body.errorMessage));
      } else {
        cb(err, body);
      }
    });
  };

  /**
   * Attempts to authenticate a user.
   * @param  {Object}   options Config object
   * @param  {Function} cb      Callback
   */
  r.auth = function (options, cb) {
    if (options.token === null) {
      delete options.token;
    } else {
      options.token = options.token || uuid.v4();
    }

    options.agent = options.agent || 'Minecraft';
    r._call('authenticate', {
      agent : {
        name: options.agent,
        version : options.agent === 'Minecraft' ? 1 : options.version
      },
      username: options.user,
      password: options.pass,
      clientToken: options.token
    }, function (err, data) {
      cb(err, data);
    });
  };

  /**
   * Refreshes a accessToken.
   * @param  {String}   access Old Access Token
   * @param  {String}   client Client Token
   * @param  {Function} cb     (err, new token, full response body)
   */
  r.refresh = function (access, client, cb) {
    r._call('refresh', {
      accessToken: access,
      clientToken: client
    }, function (err, data) {
      if (err) cb(err);
      if (data && data.clientToken !== client) {
        cb(new Error('clientToken assertion failed'));
      } else {
        cb(err, data ? data.accessToken : null, data);
      }
    });
  };

  /**
   * Validates an access token
   * @param  {String}   token Token to validate
   * @param  {Function} cb    (error)
   */
  r.validate = function (token, cb) {
    r._call('validate', {
      accessToken: token
    }, function (err, data) {
      cb(err);
    });
  };
  /**
   * Invalidates all access tokens.
   * @param  {String}   user User's user
   * @param  {String}   pass User's pass
   * @param  {Function} cb   (error)
   */
  r.signout = function (user, pass, cb) {
    r._call('signout', {
      username: user,
      password: pass
    }, function (err, data) {
      cb(err);
    });
  };

  return r;
};


k.server = function Server(con) {
  var config = {
    host : con.host || 'https://sessionserver.mojang.com' //Allow for a custom auth server
  };

  var request = require('request').defaults({
	 proxy: proxySettings,
    headers: {
      'User-Agent' : 'node-yggdrasil/' + version,
      'Content-Type' : 'application/json'
    }
  });

  var r = {};
  r._call = function (path, data, cb) {
    request({
      method: 'POST',
      uri: config.host + '/' + path,
      json: data
    }, function (err, resp, body) {
      if (body && body.error) {
        cb(new Error(body.errorMessage));
      } else {
        cb(err, body);
      }
    });
  };


  /**
   * Java's annoying hashing method.
   * All credit to andrewrk
   * https://gist.github.com/andrewrk/4425843
   */
  function performTwosCompliment(buffer) {
    var carry = true;
    var i, newByte, value;
    for (i = buffer.length - 1; i >= 0; --i) {
      value = buffer.readUInt8(i);
      newByte = ~value & 0xff;
      if (carry) {
        carry = newByte === 0xff;
        buffer.writeUInt8(newByte + 1, i);
      } else {
        buffer.writeUInt8(newByte, i);
      }
    }
  }


  /**
   * Java's stupid hashing method
   * @param  {Buffer|String} hash     The hash data to stupidify
   * @param  {String} encoding Optional, passed to Buffer() if hash is a string
   * @return {String}          Stupidified hash
   */
  r.mcHexDigest = function mcHexDigest(hash, encoding) {
    if (!(hash instanceof Buffer))
      hash = new Buffer(hash, encoding);
    // check for negative hashes
    var negative = hash.readInt8(0) < 0;
    if (negative) performTwosCompliment(hash);
    var digest = hash.toString('hex');
    // trim leading zeroes
    digest = digest.replace(/^0+/g, '');
    if (negative) digest = '-' + digest;
    return digest;
  };

  /**
   * Client's Mojang handshake call
   * See http://wiki.vg/Protocol_Encryption#Client
   * @param  {String}   token        Client's accessToken
   * @param  {String}   profile      Client's selectedProfile
   * @param  {String}   serverid     ASCII encoding of the server ID
   * @param  {String}   sharedsecret Server's secret string
   * @param  {String}   serverkey    Server's encoded public key
   * @param  {Function} cb           (is okay, data returned by server)
   * @async
   */
  r.join = function (token, profile, serverid, sharedsecret, serverkey, cb) {
    r._call('session/minecraft/join', {
      'accessToken': token,
      'selectedProfile': profile,
      'serverId': r.mcHexDigest(crypto.createHash('sha1').update(serverid).update(sharedsecret).update(serverkey).digest())
    }, function(err, data) {
      cb(err, data);
    });
  };

  /**
   * Server's Mojang handshake call
   * @param  {String}   username     Client's username, case-sensitive
   * @param  {String}   serverid     ASCII encoding of the server ID
   * @param  {String}   sharedsecret Server's secret string
   * @param  {String}   serverkey    Server's encoded public key
   * @param  {Function} cb           (is okay, client info)
   * @async
   */
  r.hasJoined = function (username, serverid, sharedsecret, serverkey, cb) {
    var hash = r.mcHexDigest(crypto.createHash('sha1').update(serverid).update(sharedsecret).update(serverkey).digest());
    request({
      method: 'GET',
      uri: config.host + '/session/minecraft/hasJoined?username='+username+'&serverId='+hash,
      json: true
    }, function (err, resp, body) {
      if (err) { // Error
        cb(err, body);
      } else if (body && body.hasOwnProperty('id')) { // Success
        cb(err, body);
      } else {
        cb(new Error('Failed to verify username!'));
      }
    });
  };


  return r;
};

module.exports = k;
```

**Comment by rom1504** [comment]
Ok.
Est ce que tu as le même résultat si tu testes sur un autre serveur ? (par exemple un serveur vanilla que tu ferais tourner en local)

**Comment by luluwebmaster** [comment]
Hum, nop pas vraiment, voila ce que j'ai : 

Sur la console node : 

`{ serverId: '', publicKey: <Buffer 30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 a0 5e 91 cd 6c d3 fa c2 71 26 56 cb 7b 21 94 17 43 6b ac 10 52 ... >, verifyToken: <Buffer 49 56 82 63> }`

Et dans la console Minecraft : 

`com.mojang.authlib.GameProfile@6994365e[id=<null>,name=Lennaft,properties={},legacy=false] (/{ip}:62957) lost connection: Disconnected`

**Comment by luluwebmaster** [comment]
@rom1504 Hum du coup, une idée ? ^^

**Comment by luluwebmaster** [comment]
@rom1504 @roblabla Hello, je remonte ^^

**Comment by rom1504** [comment]
so if you use the skipValidation flag, it should work ;)
