### ISSUE TITLE
Tried the client_echo.js example, got this error: ECONNRESET

### ISSUE THREAD

**Issue by GnaspGames** [PrismarineJS/node-minecraft-protocol#482]
I've tried running the example in `/examples/client_echo/client_echo.js` and this is what I get:

```
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
connected
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
```

I'm really interested in using a headless client on my project (https://github.com/GnaspGames/Smelt). 

I've been adding RCON support for servers, but for Singleplayer Worlds on LAN and Realms, it would be awesome to be able to use a secondary MC account to connect and fire commands. 

But I can't get passed this error. Any thoughts?

**Comment by rom1504** [comment]
try putting version:'1.11.2' in createClient options ?

ps: @roblabla should we make 1.11.2 the default ? https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/version.js#L4

also I why is the displayed error so useless... there's even a test about this, I don't understand

**Comment by GnaspGames** [comment]
That worked! Thank you 👍 

I won't close so that @roblabla can answer your question.

**Comment by roblabla** [comment]
We should just make whatever is the latest stable minecraft version the default automatically. Maybe we should add a 'latest' "symlink" in minecraft-data ?

**Comment by rom1504** [comment]
now we default to automatically guessing the version, hopefully that will reduce the number of version issues.
