### ISSUE TITLE
[Add Rcon to README] How to send commands and read response

### ISSUE THREAD

**Issue by GnaspGames** [PrismarineJS/node-minecraft-protocol#483]
Following my previous issue, I would like to know how can I send commands via a connected client and also read the response of commands?

To send a command I've tried `client.write('chat', {message: "/summon minecraft:pig"});` but it didn't work.

This is for my project (https://github.com/GnaspGames/Smelt).

**Comment by RedDuckss** [comment]
From what I know, you cannot get the response from commands sent by the bot client. For example, take this small snippet:

```
var mcproto  = require('minecraft-protocol'),
	_console = require('readline').createInterface({
	    input: process.stdin,
	    output: process.stdout
	});


var client = mcproto.createClient({
    username: "username/email",
    password: "password",
    host: "localhost",
    port: 25565,
    version: "1.11.2"
});

client.on('success', function(player, status) {
    console.log("Minecraft client logged in.");
});
client.on('login', function(player, status) {
    console.log("Minecraft client joined server");
});
client.on('chat', function(packet) {
    var json = JSON.parse(packet.message);
    console.log(json);
    if (json.translate.startsWith("commands")) {
    	console.log("Is command feedback");
    }
});

_console.on('line', function(input) {
    client.write("chat", { message: input, position: 0 });
});
```
If you now send a message via the console, it outputs the response from it. If you send a command, the responses translate key starts with `commands`, so it's easy to detect it. However it _only_ returns the translate key, no other response (not even the chat message sent in chat). Whether or not this is a bug, I do not know. But you might be better off using rcon, since it returns everything as expected and does not require the use of a physical account.

**Comment by wtfaremyinitials** [comment]
+1 for rcon

Specifically [pushrax/node-rcon](https://github.com/pushrax/node-rcon)

**Comment by roblabla** [comment]
Maybe we should add node-rcon to our README ?

**Comment by GnaspGames** [comment]
Yeah i have already started implementing RCON into Smelt. That's was made me start looking into this. I was hoping it might be an RCON alternative for those using Realms. Of course they'd need a second account, but even with that it doesn't sound like it's going to work. 

I would be very surprised if there's no way to get the command responses, since they are obviously sent to the client somehow. 

But this isn't a priority for me, rather just an idea I wanted to investigate. I'll finish my RCON implementation and maybe take another look at this in the future.

**Comment by GnaspGames** [comment]
Thanks for indulging me with this. I appreciate your feedback.

**Comment by rom1504** [comment]
if you get the translation key, you can use translation data to get responses https://github.com/PrismarineJS/minecraft-data/issues/17#issuecomment-217668471
