### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by WindBlades** [PrismarineJS/node-minecraft-protocol#486]
Hi I tried to install node-minecraft-protocol but when installing it makes me a mistake I have already done some research but nothing works

C:\Windows\system32>npm install minecraft-protocol
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> ursa@0.9.4 install C:\Windows\system32\node_modules\ursa
> node-gyp rebuild

C:\Windows\system32\node_modules\ursa>if not defined npm_config_node_gyp (node "
C:\Users\WindBlade\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: binding.gyp not found (cwd: C:\Windows\system32\node_modules\ursa) while tr
ying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\WindBlade\AppData\Roaming\
npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\WindBlade\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js
" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\ursa
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
bottest@1.0.0 C:\Windows\system32
`-- (empty)

npm WARN discord.js@10.0.1 requires a peer of node-opus@^0.2.1 but none was inst
alled.
npm WARN bottest@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp re
build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

-----

Os: Windows 7-64bits
node version:6.10.2
npm version: 4.5.0

**Comment by rom1504** [comment]
That error is ok, ursa is optional. So it installed properly.
What do you mean by "nothing works" ?

**Comment by WindBlades** [comment]
147/5000
What I mean is that I do not find it in my C:\Program Files\nodejs\node_modules so I guess it was wrong to install

**Comment by rom1504** [comment]
the node_modules dir will be where you run npm install minecraft-protocol

**Comment by WindBlades** [comment]
Uh no I meant that I can not install mineflayer and so I thought it was node-minecraft-protocol that had mal installed

**Comment by rom1504** [comment]
what do you mean by "I cannot install mineflayer" ?

**Comment by roblabla** [comment]
This failure is expected and non-fatal. Here's a little snippet of code for you

```
$ mkdir some_project
$ cd some_project
$ npm i minecraft-protocol
$ node
> require("minecraft-protocol")
```

If this works, then minecraft-protocol installed properly. If it doesn't, then please report back on the error.

**Comment by WindBlades** [comment]
No I tried to test the robot of rom1504 but it made me a can not find module '.grammar / grammar' I try to do a npm install grammar but it did not work.

**Comment by rom1504** [comment]
Did you run npm install

**Comment by WindBlades** [comment]
On file?

**Comment by rom1504** [comment]
On no file

**Comment by WindBlades** [comment]
yea

**Comment by WindBlades** [comment]
where i can find all module ?

**Comment by rom1504** [comment]
npmjs.com

**Comment by WindBlades** [comment]
ok is good thank all (this issue is now closed)
