### ISSUE TITLE
Consider reusing the vanilla server instances between tests

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#497]
It would considerably speed up the tests, because starting/stopping the server is what takes the most time (and it doesn't work 100% of the time so it causes random failures)

Not possible to share offline and online server instances, but apart from that there's no difference in the configs between tests.

**Comment by rom1504** [comment]
done, 1 minute gained.
Tests for 1.7 -> 1.12 (6 versions) for online and offline mode now run in 3:40 minutes.

**Comment by roblabla** [comment]
Isn't it possible to share offline/online instances by modifying the config and using /reload ? I haven't touched minecraft in a while, but I'd find it weird if that wasn't possible.

**Comment by rom1504** [comment]
It seems /reload cannot reload this setting
https://www.akliz.net/manage/knowledgebase/30/How-to-Enable-OnlineorOffline-Mode-on-a-Minecraft-Server.html
 http://minecraft.gamepedia.com/Commands#reload
