### ISSUE TITLE
Switch from uuid-1345 to uuid

### ISSUE THREAD

**Issue by javacoolme** [PrismarineJS/node-minecraft-protocol#515]
Switch from [`uuid-1345`](https://www.npmjs.com/package/uuid-1345) to [`uuid`](https://www.npmjs.com/package/uuid). Not only is [`uuid`](https://www.npmjs.com/package/uuid) more popular, but it will also reduce the number of dependencies in [`flying-squid`](https://www.npmjs.com/package/flying-squid), which will help [this](https://github.com/PrismarineJS/flying-squid/issues/212) issue.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/pull/324/files

I think I remember I chose uuid-1345 because it's the only one that has uuid3 and we need it

**Comment by javacoolme** [comment]
Got it! Thanks.
