### ISSUE TITLE
add an option to store and use auth token directly in nmp

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#519]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%242%20Funded-%2300A156.svg" />](https://issuehunt.io/r/PrismarineJS/node-minecraft-protocol/issues/519)

see https://github.com/pqml/prismarine-tokens and https://github.com/PrismarineJS/node-minecraft-wrap/blob/master/lib/wrap_client.js#L37

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $2.00)

- [<img src='https://avatars1.githubusercontent.com/u/2346494?v=4' alt='rom1504' width=24 height=24> rom1504](https://issuehunt.io/u/rom1504) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PrismarineJS/node-minecraft-protocol/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by plexigras** [comment]
like a `sessionCacheFile` option?

**Comment by rom1504** [comment]
I think it would be better to just integrate https://github.com/PrismarineJS/node-minecraft-wrap/blob/master/lib/wrap_client.js#L37
What it does is simply create/use/update the launcher_profile.json
when it's used in servers where there is no .minecraft, it will create it
when it's used in desktop pc, it will just reuse the tokens people already created with their vanilla client

**Comment by rom1504** [comment]
this is one of the more asked question. Would be nice to fix

**Comment by rom1504** [comment]
thanks @ph0t0shop
