### ISSUE TITLE
Client error Deserialization error for play.toClient : Read error for name : 960204 is not in the mappings value

### ISSUE THREAD

**Issue by CodingCreeperDude96** [PrismarineJS/node-minecraft-protocol#522]
Hi,
I am trying to connect to a server and it gives me this error, resulting is my script stopping.
Can I fix this? or ignore it somehow?

**Comment by rom1504** [comment]
Which server is it ?
Version, spigot ?

**Comment by CodingCreeperDude96** [comment]
Hypixel, they use their own stuff I guess

**Comment by rom1504** [comment]
please report more details in https://github.com/PrismarineJS/node-minecraft-protocol/issues/532
