### ISSUE TITLE
Generating and Sending Chunk To The Player

### ISSUE THREAD

**Issue by oscartbeaumont** [PrismarineJS/node-minecraft-protocol#524]
I have been trying to make a very basic Minecraft server using this module. I have got the server and the player connecting (like in the examples) but I can't work out how to generate and send a chunk to the player. I have been trying the code from https://github.com/PrismarineJS/node-minecraft-protocol/issues/49 but everything I try and connect Minecraft says the server failed to connect because undefined and the server console does not display any error messages. Any help would be appreciated. Thanks

**Comment by roblabla** [comment]
This is some super super super old code from 2013. Things have changed **a lot** since then. You have to use prismarine-chunk nowadays.

**Comment by oscartbeaumont** [comment]
I am using the code I attached below and Minecraft says
'Connection Lost
undefined'
What have I done wrong?

`const mc = require('minecraft-protocol');
const Chunk = require('prismarine-chunk')("1.12.1");
var server = mc.createServer({
  'online-mode': true,
  encryption: true,
  host: '0.0.0.0',
  port: 25565,
});

var chunk = new Chunk();
chunk.setBlockType(0, 0, 0, 2); //Create Grass At Block 0, 0, 0

server.on('login', function(client) {
  client.write('login', {
    entityId: client.id,
    levelType: 'default',
    gameMode: 0,
    dimension: 0,
    difficulty: 2,
    maxPlayers: server.maxPlayers,
    reducedDebugInfo: false
  });
  client.write('position', {
    x: 0,
    y: 10,
    z: 0,
    yaw: 0,
    pitch: 0,
    flags: 0x00
  });
  client.write('map_chunk', {
    x: 0,
    z: 0,
    groundUp: true,
    bitMap: 255,
    chunkData: chunk.dump()
  });
});`

**Comment by rom1504** [comment]
map_chunk packet has other arguments for 1.12.
Have a look at flying-squid 1.9 branch or the packet doc

**Comment by oscartbeaumont** [comment]
I have spent some time looking through the flying-squid 1.11.2 branch and the only difference to sending the original chunk is that they use the bitMap of 0xffff. What am I missing that I also need to change.

**Comment by plexigras** [comment]
https://prismarinejs.github.io/minecraft-data/?d=protocol#toClient_map_chunk

**Comment by oscartbeaumont** [comment]
If any of you have any free time can you write/send me an example because I have been googling and trying all day but I have not been able to get it to work. Everything I have tried has resulted in the user being kicked with an 'undefined error'.

**Comment by plexigras** [comment]
this works i tested it in 1.9.4
```js
client.write('map_chunk', {
  x: 0,
  z: 0,
  groundUp: true,
  bitMap: 0xffff,
  chunkData: chunk.dump(),
  blockEntities: []
})
```

**Comment by oscartbeaumont** [comment]
I got it working. Thanks for you help. Also thanks for developing this awesome nodejs module.
