### ISSUE TITLE
My client script doesn't want to run.

### ISSUE THREAD

**Issue by NitrateOrigins** [PrismarineJS/node-minecraft-protocol#526]
I get this error:
`const [readVarInt, writeVarInt, sizeOfVarInt] = require("protodef").types.varint;
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/path/to/folder/node_modules/minecraft-protocol/src/client.js:5:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`

when I run this script (called Daemon.js):
`var mc = require('minecraft-protocol');
var client = mc.createClient({
  host: "localhost",   // optional
  port: 25567,         // optional
});
client.on('chat', function(packet) {
  var jsonMsg = JSON.parse(packet.message);
  if(jsonMsg.translate == 'chat.type.admin' || jsonMsg.translate == 'chat.type.text') {
  }
});`

Any help would be greatly appreciated.

**Comment by rom1504** [comment]
you need node >=6

**Comment by NitrateOrigins** [comment]
I updated my node version, and it still gives me the same error message.

**Comment by plexigras** [comment]
you need node >=6

**Comment by NitrateOrigins** [comment]
I have 9.2.0

**Comment by rom1504** [comment]
how do you run the script ?

**Comment by NitrateOrigins** [comment]
node Daemon.js

**Comment by NitrateOrigins** [comment]
Also, can you guys update soon? Or is this your final version?

**Comment by rom1504** [comment]
@NitrateOrigins what does node --version say ?

update what ? do you mean to mc 1.12.2 ?

**Comment by NitrateOrigins** [comment]
Update the node-minecraft-protocol. To MC 1.12.2.
It says v9.2.0.

**Comment by rom1504** [comment]
Yeah I'll update it soon.

About your error, it definitely means you are not running version 9.2.0, so check you are really running this one for the script.

I bet you have 2 versions installed.

Either use the full path instead of just "node" or uninstall the old version.
