### ISSUE TITLE
There's no officially documented way to access internal TCP server of Server instance.

### ISSUE THREAD

**Issue by ethanent** [PrismarineJS/node-minecraft-protocol#531]
Exactly what title says! :)

**Comment by rom1504** [comment]
That's true. How is that an issue ?
The purpose of node minecraft protocol is to hide such implementation details under a (a little bit more) high level api.

**Comment by ethanent** [comment]
@rom1504 Ok, interesting stance. I suppose the main purpose of being to access the internal `net.Server` instance would be to utilize its events and properties which aren't exposed officially by a `require('minecraft-protocol').createServer()` instance. (For example, to use the `listening` event.)

**Comment by rom1504** [comment]
For example you can use the listening event emitted by nmp server
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/server/server.js#L52

If we were to expose the internal node server then we could make no
guaranty on the stability of the API, especially given the fact there are
new
major (ie breaking) node version so very often (nmp started at node 0.8 I
think, and now node is already at 9.x I believe)

**Comment by rom1504** [comment]
An additional benefit of abstracting the underlying network is you can
actually use not only tcp but it's also possible to provide your own stream
provider to for example use websocket instead.

**Comment by ethanent** [comment]
Ok, I didn't realize that the NMP server instances reimplemented these events from `net.Server`. Thanks! :)
