### ISSUE TITLE
Server.beforePing callback doesn't seem to function properly

### ISSUE THREAD

**Issue by ethanent** [PrismarineJS/node-minecraft-protocol#536]
Code:

```js
const server = mc.createServer({
	'port': 25565,
	'host': 'localhost',
	'online-mode': true,
	'beforePing': (res, client, reply) => {
		console.log(res)
		reply(res)
	},
	'version': false,
	'keepAlive': false
})
```

When this server is pinged through the multiplayer server list, the client experiences some type of connection failure.

![image](https://user-images.githubusercontent.com/14060354/34920101-0e70bfbc-f922-11e7-9877-2ee9d8994cb7.png)

**Comment by rom1504** [comment]
you need to call the callback, you called it "cb" not "reply".

**Comment by ethanent** [comment]
@rom1504 Sorry, that was my bad. (I had changed it for the issue from my production code and slipped up!)

The issue does still occur though when the callback method is being called properly!

**Comment by rom1504** [comment]
Ah and in node.js the convention is to pass the error as first argument of the callback. In case there is no error it should be null.
so you should do `reply(null,res)`

**Comment by ethanent** [comment]
@rom1504 Oh, ok. Thanks. I might make a PR to help improve that part of the docs when I've got time to. 👍 

Also, what is the purpose of the error argument? (In which cases would an error be passed to the callback?)

**Comment by rom1504** [comment]
yes the beforePing doc def needs to be improved.

well if you have an error in your code and as a consequence you can't answer to ping you can pass an error there.

For example let's say you are reading part of the ping answer in a file, and the file has been deleted for some reason, so you'll have an error when trying to read the file, and you can propagate that back to beforePing callback.
