### ISSUE TITLE
Ping response: favicon null vs undefined

### ISSUE THREAD

**Issue by ethanent** [PrismarineJS/node-minecraft-protocol#537]
When responding to a ping, setting the favicon property to `null` causes the ping response to fail. 

(`null` is generally preferred to represent the voiding of a property in JS. See [this StackOverflow answer](https://stackoverflow.com/a/37980662/4160422) for more details about that.)

**Comment by rom1504** [comment]
http://wiki.vg/Server_List_Ping that's the format of ping.
I believe favicon should be an empty string (or maybe undefined) to not have one.

Mojang is defining that json format, we're just transmitting that to them.

node-minecraft-protocol doesn't try to abstract mojang stuff, we just provide access to them here.

libs like https://github.com/PrismarineJS/mineflayer or https://github.com/PrismarineJS/flying-squid abstract node-minecraft-protocol api under an higher-level api

**Comment by ethanent** [comment]
@rom1504 Ok, got it. Thanks!
