### ISSUE TITLE
Working with Spigot's UUID (& IP) forwarding features

### ISSUE THREAD

**Issue by ethanent** [PrismarineJS/node-minecraft-protocol#540]
I'm interested in knowing if it'd be possible to send UUID forwarding information to Spigot servers like BungeeCord does through NMP. (Info about forwarding over [here](https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/).)

I found this interesting commit to BungeeCord which may be helpful in learning about UUID forwarding packet changes:
[Rewrite the spawn player packet's uuid to support skins on non ip-fowarded servers (commit: cd51869) — thinkofdeath](https://github.com/SpigotMC/BungeeCord/commit/cd518690fd692350c40e93e9c1c57d6e50f8e79e)

**Comment by ethanent** [comment]
Update: Worked directly with BungeeCord developers to find this info!

**Comment by rom1504** [comment]
So you figured it out ?
That's interesting, if you can document what you can find about bungeecord special network things somewhere, it will be useful to many people (just do a search on bungeecord on the issues on this repo to see how many people want to do stuff about that)
Do you have a repo on github where you do something with that ?

**Comment by ethanent** [comment]
@rom1504 Yep! @bdsomer and I conducted research to implement IP and UUID forwarding in my Onticord proxy server! (Specifically here: https://github.com/ethanent/onticord/blob/master/OnticordServer.js#L86)

I'll probably fully document the changes BungeeCord makes to the `set_protocol` packet later for everyone to use. 💯
