### ISSUE TITLE
Onclose/disconnect event

### ISSUE THREAD

**Issue by MrSonicMaster** [PrismarineJS/node-minecraft-protocol#546]
Is there ANY WAY at ALL to detect disconnect/error/close events - I have tried EVERYTHING and NOTHING logs at all to tell me why it's failing to connect or really just any helpful information at all.

(code snippet, not full script)
```
const bot = mc.createClient({
	host: 'mc.hypixel.net',
	port: 25565,
	username: username,
	password: password,
	version: '1.8.9'
});

bot.on('end', reason => {
	console.error(`${realName} has been ended (${reason})!`);
});

bot.on('error', error => {
	console.error(`${realName} connection error (${error})!`);
});

bot.on('close', close => {
	console.error(`${realName} connection close (${close})!`);
});

bot.on('timeout', timeout => {
	console.error(`${realName} connection timeout (${timeout})!`);
});
```

Nothing logs (no errors, nothing at all), node script just terminates most of the time. I've gotten around a  1% success rate where it actually connects/logs it's connected and does what it's supposed to (with no modification from where it fails). What's wrong?

**Comment by rom1504** [comment]
Try to enable the debug information so see what packet are transmitted (
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/README.md#debugging
)
About the reason it is failing to connect, I would say probably you're
trying to connect to a server that is not vanilla and not compatible, see
https://github.com/PrismarineJS/node-minecraft-protocol/issues/532
Node Minecraft protocol mainly supports vanilla (in all the versions
written in the readme) but we are trying to support more non vanilla
servers in that issue.
If you can report there what server failed, we can try to reproduce the
problem and fix it.

**Comment by rom1504** [comment]
Ah I didn't read you were trying to connect to hypixel.
Hypixel is highly non vanilla (it uses bungee cord and a bunch of other stuff) so I believe there are still some stuff to fix for it to work properly, but look at that issue, I think some people managed to connect a bit.

**Comment by MrSonicMaster** [comment]
Yeah, it does connect some of the time, but the times it fails it refuses to log a single bit of information no matter how many events I add (including disconnect and kick_disconnect as well as the others I listed above) when it fails to connect which makes it a lot harder to debug, and a lot harder to tell it to reconnect on fail/disconnect - right now I just have a 20 second timeout start right as I set connect, and it clears the timeout after it succeeds connecting. This way, if it takes too long connecting, it will attempt a re-connect assuming it fails - but obviously this could cause it to try connecting 2 times and uses up some time we could have saved by re-connecting right on fail. That being said, you can close this issue if you want (as I have a functional solution for now) but I'm pretty sure it might still be a bug with node-minecraft-protocol.
