### ISSUE TITLE
Port to java?

### ISSUE THREAD

**Issue by VRCube** [PrismarineJS/node-minecraft-protocol#547]
Would you mind porting this to java? Because game itself is java and it would be more useful. current minecraft protocol in java supports only latest version

**Comment by rom1504** [comment]
See https://github.com/ProtoDef-io/ProtoDef/blob/master/README.md and
related projects. Some people have tried to convert our protocol.json to
java.

Although there is no benefit in creating a client or server from zero in
java.

But if you feel like it try it.

**Comment by roblabla** [comment]
There already exists **plenty** of minecraft protocol implementations in java, starting with minecraft.jar itself :eyes:. Why not reuse one of those ? My understanding is that https://github.com/Steveice10/MCProtocolLib is pretty good.

**Comment by VRCube** [comment]
@roblabla That lib supports only 1.12
