### ISSUE TITLE
Luminati SOCKS5 Proxying issue

### ISSUE THREAD

**Issue by NGTmeaty** [PrismarineJS/node-minecraft-protocol#567]
Hi guys. I've been trying to debug this issue on Gitter a little bit, but when using a Luminati SOCKS 5 Proxy, the proxy IP is not the IP which connects to the server. This is not an authentication proxy issue, this is 100% server based, rather than Mojang authentication.  I have some more information and proof if you contact me in Gitter.

**Comment by rom1504** [comment]
so I investigated with him and it was just a proxy config problem
