### ISSUE TITLE
Have ping return the callback

### ISSUE THREAD

**Issue by ShayBox** [PrismarineJS/node-minecraft-protocol#570]
Ping should return the result of the callback so you can do stuff like this
```js
const stats = ping({
	host: 'mineplex.com',
	port: 25565,
}, (error, results) => {
	if (error) throw error;
	return results;
});
```
rather than having to wrap all your code in the callback or define a variable and redefine it in the callback

**Comment by rom1504** [comment]
That is not how callbacks work.
Ping is an async function, it cannot be transformed to a sync function.
However you can make a promise out of it and await on the result in an
async function.
If you don't know about callbacks, promises and async/await I suggest you
first read a tutorial about them. You will need them whatever you do in
node.

**Comment by ShayBox** [comment]
Ping is not an async function, and even if it was, you can still return in an async function, you just have to .then or await it, so the code would be
```js
const stats = await ping({
	host: 'mineplex.com',
	port: 25565,
}, (error, results) => {
	if (error) throw error;
	return results;
});
```
But again, ping is not async.
And it works fine if I change it locally, return the callback in the ping function at the end, simple.

**Comment by rom1504** [comment]
Ping is absolutely async, look at the code https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/ping.js

If you don't know about the node way of using callbacks to do async function, read up on it.

Returning the callback doesn't make any sense.
