### ISSUE TITLE
JsonReader error

### ISSUE THREAD

**Issue by log4b0at** [PrismarineJS/node-minecraft-protocol#573]
When you use client.write(), in some cases in the minecraft client you will be kick from the server with the message "...MalformedJsonExpection... at line 1 column 1 path $" and others Java errors, to reproduce use this code:

```Javascript
client.write('title', {action:0, text:'Hello in the title!'});
```

**Comment by rom1504** [comment]
The server is saying that you didn't send json and indeed you didn't. So
you need to send json.
