### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by lluiscab** [PrismarineJS/node-minecraft-protocol#576]
Here we go again.

So, I'm trying to `createServer` for 1.13 to use it as a proxy (See [this comment](https://github.com/PrismarineJS/mineflayer/issues/315#issuecomment-343660526)).

My server starts but errors as soon as a client tries to ping it on the server list. Each time I ping the server, this error appears on the console, even tho I have no error event handlers.

`Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
`

I've tried with `1.12` as version but with my client being `1.12.2` and this also happens, whereas if I change the server version to `1.12.2`, it doesn't happen anymore so I'm guessing that this error is caused by some kind of version mismatch.

My current code can be seen [here](https://pastebin.com/raw/njQmW4n5)
I'd really appreciate some help figuring this out.

**Comment by rom1504** [comment]
1.13 is not supported yet so don't even try it.

What you are showing is not an error but a warning, it has no consequences.
What happens next ?

**Comment by lluiscab** [comment]
My client won't connect to the server. List appears as "Can't connect to server" and any attempts to connect to the server will just automatically end in "Disconnected"

See screenshots [here](https://imgur.com/a/CeAeilZ)

**Comment by rom1504** [comment]
1.13 support is tracked in https://github.com/PrismarineJS/minecraft-data/issues/200

**Comment by rom1504** [comment]
the rest of the issues are unrelated to 1.13, and already tracked elsewhere

**Comment by AnthonyTsang** [comment]
1.13 is updating the plugin channels, some of them are using dedicated packet now. This repo needs to be updated as well.

**Comment by AnthonyTsang** [comment]
Things to do, 
Update these changes
https://wiki.vg/index.php?title=Pre-release_protocol&oldid=14150#Plugin_Channels
For the channels renamed, it is just a find all and replace. e.g. `minecraft:register`
But some of them is replaced by packet. e.g. `MC|PickItem`

**Comment by lluiscab** [comment]
The only two channels that I see are used by NMP are [here](https://github.com/PrismarineJS/node-minecraft-protocol/blob/e3e0a26dfe477d14cae4274ae0a92615bcb200da/src/client/pluginChannels.js) so it should just be a simple rename right? The channels that have been replaced by a packet aren't really used here AFAIK so I guess we don't do anything with them and handle them later in mineflayer?

**Comment by rom1504** [comment]
It might be a good opportunity to move the definition of these channels to Minecraft data. That would remove some completely from nmp and mineflayer and make keeping multi version support simpler. I think there is a dedicated issue for that in Minecraft data.

**Comment by lluiscab** [comment]
Woldn't that mean that we'd need to update all the `protocol.json` files in minecraft data with the channel definitions?

**Comment by rom1504** [comment]
It would probably go in a channels.json file but yes it might mean that.
This file could be the same everywhere though (that's what nmp currently do
since we use the same definition for all versions)

**Comment by lluiscab** [comment]
I actually made a fork and added a version check to change the channel names but couldn't really figure out how to test that with my own minecraft-data.

**Comment by rom1504** [comment]
You'd need to update node-minecraft-data too and base your nmp fork on your branch of nmd.
But otherwise just wait a bit, I'll try to review this asap so you can move forward
