### ISSUE TITLE
Parse / deserialize individual packets

### ISSUE THREAD

**Issue by lluiscab** [PrismarineJS/node-minecraft-protocol#577]
I'm working on a proxy which means I only listed for `raw` events on the nmp server so I can then send them to my real server. The only problem that I'm having is that sometimes I might want to read what's inside of a packet but I only have a buffer available, some packets are easy to read (chat for example) but others just throw a bunch of random symbols when I try to read them.

Here's an example of the `player_info` buffer that I'm trying to read (in hex)
`2e0001e60a5aaebbfa3f5aa173820e0391d4db086c6c75697363616200000000`

Trying to read this as a normal string outputs 
`.æ
Z®»ú?Z¡sÔÛlluiscab`

Does NMP expose any function that I could call to manually parse a buffer?

**Comment by plexigras** [comment]
I'm just guessing but you could try something like this.

```js
client.deserializer.parsePacketBuffer(buffer)
```

https://github.com/ProtoDef-io/node-protodef/blob/HEAD/doc/api.md#parserprotomaintype

https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/client.js#L38

https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/serializer.js#L29-L31

**Comment by roblabla** [comment]
If all you want is to deserialize an individual (raw) packet, you might be better served using protodef directly. Which is what the above snippet does.

**Comment by lluiscab** [comment]
@plexigras reply works perfect. Thanks for your help!

**Comment by lluiscab** [comment]
I'm not really sure this is working correctly, I'm getting some very strange outputs.

This is the parsed buffer from a `set_slot` package
```{ size: 10, name: 'set_slot', state: 'play' } { data: 
   { name: 'steer_vehicle',
     params: 
      { sideways: 1.3633232759416145e-41,
        forward: 2.369355800876173e-38,
        jump: 0 } },
  metadata: { size: 10 },
  buffer: <Buffer 16 00 00 26 01 01 01 00 00 00> }
```
  generated by this code

`console.log(metadata, client.deserializer.parsePacketBuffer(buffer))	`
