### ISSUE TITLE
Client not able to join server

### ISSUE THREAD

**Issue by nagoL2015** [PrismarineJS/node-minecraft-protocol#596]
As title says. It is warning this: 
`Chunk size is 51 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400157f00070030002e0030002e0030002e0030000063dd`

**Comment by rom1504** [comment]
What do you observe besides that warning ?

**Comment by nagoL2015** [comment]
Nothing. https://i.imgur.com/l9T0WHc.png. All it shows is that and my client eventually times out. I'm just trying to make a proxy. Here is the server start code.

const proxyServer = createServer({
  'online-mode': false,
  'max-players': 1,
  host: '0.0.0.0',
  port: '25565',
  motd: '2B2T Queue',
  keepAlive: true,
  version: '1.12.2',
});

**Comment by nagoL2015** [comment]
Wait sorry. I was using a modified client and that gave me that warning. Then I switched to vanilla and I don't have the warning but the server is still stuck on logging in.

**Comment by rom1504** [comment]
What is your whole code ?

**Comment by nagoL2015** [comment]
Sorry for late reply: https://hastebin.com/idijavoxeq.coffeescript

**Comment by plexigras** [comment]
i recommending you use use the raw data and `writeRaw` to reduce lag whenever you can.

and regarding your issue you should try and see if you can get it to work on a vanilla server.

**Comment by rom1504** [comment]
the zlib error is now fixed.
