### ISSUE TITLE
How to build the color buffer in the map packet ?

### ISSUE THREAD

**Issue by Sceat** [PrismarineJS/node-minecraft-protocol#605]
I'm trying to send a [map packet](http://minecraft-data.prismarine.js.org/?v=1.12.1&d=protocol#toClient_map) but still trying to figure out what kind of data i'd need to provide :disappointed: 

```js
this.client.write('map', {
    itemDamage: 0,
    scale: 4,
    trackingPosition: false,
    icons: [],
    columns: 127,
    rows: 127,
    x: 0,
    y: 0,
    data: ?,
})
```
---
![](https://i.imgur.com/pSzHrDM.png)

The original wiki is not so clear either 

![](https://i.imgur.com/qmd4QRm.png)
---
Do i need to use `prismarine-nbt` and build a nbt representation of the map format ? it doesn't seems the right anwser at all so it's a dead end for my weak breain :disappointed_relieved: 

![](https://user-images.githubusercontent.com/11330271/49773156-98c5f800-fcf8-11e8-9a99-ace4a5466c3e.png)

**Comment by rom1504** [comment]
Read this issue https://github.com/PrismarineJS/mineflayer/issues/583
I think it would be great to add a feature to so that either in mineflayer
or an independent package. If you feel like doing that once you got this
working, it would be useful to other people ;)

**Comment by Sceat** [comment]
Annnw okay it's just a dumb array lol thx mate! going to work on it but at least i managed to show something on the map :smile: !

for whoever wanting a quick working stuff see below

```js
const buffer = []
let size = 128
const r = 89
const g = 125
const b = 39
for (let x = 0; x < size; x++) {
	for (let y = 0; y < size; y++) {
		buffer[x + y * size] = ((r & 255) << 16) + ((g & 255) << 8) + (b & 255)
	}
}

this.client.write('map', {
	itemDamage: 0,
	scale: 4,
	trackingPosition: false,
	icons: [],
	columns: --size,
	rows: size,
	x: 0,
	y: 0,
	data: Buffer.from(buffer),
})
```

![image](https://user-images.githubusercontent.com/11330271/49802579-efadea80-fd55-11e8-9808-e10ffeebcb2a.png)

Interesting result with every pixels set at `0xFFFFFF` i got in game render of some part of my desktop lmao wtf, everytime i restart the server i get a different result, also tried to move some windows around to see if it impacted the render but dunno

![image](https://user-images.githubusercontent.com/11330271/49803346-30a6fe80-fd58-11e8-8dd7-e7750787b405.png)

**Comment by Sceat** [comment]
Still i get wrong colors dunno why

![image](https://user-images.githubusercontent.com/11330271/49804494-5681d280-fd5b-11e8-86e2-4fb845f44c6c.png)

![image](https://user-images.githubusercontent.com/11330271/49804459-44079900-fd5b-11e8-9803-136307d8eef6.png)

**Comment by Sceat** [comment]
# Problem solved

it was not a `hex` value but simply the corresponding id in the minecraft wiki table !

### Contribution
I made an utility here [aresrpg-map-colors](https://github.com/AresRPG/aresrpg-map-colors) ! it's <kbd>MIT</kbd> so feel free to use it if some want to make an official implementation in prismarine (the color table is only compatible `1.12` and higher)

### Use with prismarine

```js
import MapColor from '@aresrpg/aresrpg-map-colors'

const buffer = []
const size = 128
const { id } = MapColor.nearestMatch(49, 27, 146)
for (let x = 0; x < size; x++) for (let y = 0; y < size; y++) buffer.push(id)

this.client.write('map', {
	itemDamage: 0,
	scale: 4,
	trackingPosition: false,
	icons: [],
	columns: size - 1,
	rows: size - 1,
	x: 0,
	y: 0,
	data: Buffer.from(buffer),
})
```

**Comment by Sceat** [comment]
I can also make a PR if someone tell me in which way it should be implemented

**Comment by rom1504** [comment]
hmm no would still like to have that in the readme

**Comment by rom1504** [comment]
nevermind, it's already the case https://github.com/PrismarineJS/node-minecraft-protocol/commit/4cd893607c0c66277eb3982635bcfb5d567c85de
