### ISSUE TITLE
Sending block_change in others dimensions results in a weird behavior

### ISSUE THREAD

**Issue by Sceat** [PrismarineJS/node-minecraft-protocol#607]
## dead simple Code
> i'm in `1.12.1`

```js
this.client.write('block_change', {
    location: new Vec3(15, 70, 0),
    type: (1 << 4) | 0,
})
```

## problem

Everything work as expected when i spawn the client in the overworld

```js
this.client.write('login', {
    entityId: this.client.id,
    levelType: 'default',
    gameMode: 1,
    dimension: 0,
    difficulty: 2,
    maxPlayers: 1,
    reducedDebugInfo: false,
})
```

![image](https://user-images.githubusercontent.com/11330271/50029225-d11c4d80-fffa-11e8-88a5-57a302dcbdbf.png)

but when i only change the dimension id either in the end or in the nether, i got a whole chunk __(not a column just a chunk)__ filled with my block

```js
this.client.write('login', {
    entityId: this.client.id,
    levelType: 'default',
    gameMode: 1,
    dimension: 1,
    difficulty: 2,
    maxPlayers: 1,
    reducedDebugInfo: false,
})
```

![image](https://user-images.githubusercontent.com/11330271/50029385-36703e80-fffb-11e8-90c1-eff1b3299acc.png)

It's the same with `multi_block_change` , any idea ? @rom1504 

even with the chunk initialization it only work in overworld

```js
const chunk = new Chunk()
chunk.initialize((x, y, z) => {
    chunk.setSkyLight(new Vec3(x, y, z), 15)
    return y === 65 ? new Block(1) : new Block(0)
})
```
![image](https://user-images.githubusercontent.com/11330271/50029767-88fe2a80-fffc-11e8-889b-746dcfb3caa0.png)
![image](https://user-images.githubusercontent.com/11330271/50029795-b054f780-fffc-11e8-891b-015ea0e89a5d.png)

**Comment by plexigras** [comment]
i have no idea what is causing this but there is this big disclaimer in the protocol documentation so you might want to check if loading the chunk first is changing anything.

https://wiki.vg/Protocol#Block_Change

> Changing a block in a chunk that is not loaded is not a stable action. The Notchian client currently uses a shared empty chunk which is modified for all block changes in unloaded chunks; while in 1.9 this chunk never renders in older versions the changed block will appear in all copies of the empty chunk. Servers should avoid sending block changes in unloaded chunks and clients should ignore such packets.

**Comment by Sceat** [comment]
yep i make sure of that :

i tried to :
- **load every chunks arounds** = block in overworld, not in dimensions
- **spawn a block in the chunk `1,0` while spawning in `0,0` and loading only `1,0`** = block in overworld, not in dimensions (and fun fact we don't see the player as the chunk is not loaded, the item in hand is also glitched)
![image](https://user-images.githubusercontent.com/11330271/50033418-16dc1480-0001-11e9-82e4-58a9efcdc56f.png)
- **spawn a block in the chunk `0,0`** = same result block is only in overworld
- **don't load the chunk where i spawn the block** = no block at all even i overworld

**Comment by Sceat** [comment]
@plexigras few tests later :

- Works everywhere in <kbd>1.8</kbd>
- Works in overworld but no block at all in dimensions in <kbd>1.9</kbd>
- From <kbd>1.10</kbd> till <kbd>1.12</kbd> it send a block in overworld but full chunk in dimensions as i described
- Can't test <kbd>1.13</kbd> as prismarine is not ready

**Comment by rom1504** [comment]
prismarine-chunk is ready for 1.13

**Comment by Sceat** [comment]
Yeep sorry i didn't saw the update

**Comment by rom1504** [comment]
Can you provide the code you used to make these tests ?

**Comment by Sceat** [comment]
The code is a bit messy as it's a test repo but i pushed it here https://github.com/Sceat/mc-tests
just 
```
git clone git@github.com:Sceat/mc-tests.git
```
```
npm run start
```
#### testing versions
in `src/constant.js`
![image](https://user-images.githubusercontent.com/11330271/50034555-172ade80-0006-11e9-8c0f-0d1cbe488370.png)

#### changing dimensions
just change the dimension id here
![image](https://user-images.githubusercontent.com/11330271/50034607-683ad280-0006-11e9-8b94-8b472a0c8ff0.png)

**Comment by Sceat** [comment]
I had planks cuz i wasn't aware of "the flatenning" update, it's fixed on the test repo!

few things i saw

### 1.13.2

- My game crash with [Tesselating block model](https://ghostbin.com/paste/uh4ep) when i send a block with id 9 (which is the non snowy grass block) 
    ```js
    this.client.write('block_change', {
         location: new Vec3(x, y, z),
         type: 9,
	})
    ```
- I got an error when i try to set an item in a slot (same code work well in below `1.13`)
    ```
    Client error [Error: Serialization error for play.toClient.set_slot.item.unknown : SizeOf error for params.set_slot.item.unknown : undefined has no associated fieldInfo in switch]
    ```
Otherwise still nothing found on the main problem with the chunk

**Comment by rom1504** [comment]
You need to check the doc at
http://minecraft-data.prismarine.js.org/?v=1.13.2&d=blocks and
wiki.vg/Protocol
Node-minecraft-protocol simply reflect the protocol as defined by Mojang.
It changes at every version, both the serialisation format and the
semantics of packet.
If you want something stable you can use mineflayer or flying-squid.
If you use node-minecraft-protocol directly, you need to deal yourself with
the instability of the protocol.

You can check sample of packets exchange between the minecraft client and
Minecraft server using the node-minecraft-protocol proxy example.

The field of the packets change at every version, what you put in them also
change.

But more importantly the order of packets may change.

**Comment by rom1504** [comment]
Every time you report an error, please provide some minimal amount of code
to reproduce it.

For your more general chunk population problem in a server, I advise you
look at flying-squid code, and I bet your problem is you are not sending
packets in the right order.

For other dimension, you can also check what's the exchange of packets
between the vanilla client and server using the proxy and compare that to
what you are sending (use the debug mode to display that, see the readme)

**Comment by Sceat** [comment]
Okay thanks for your reply ! i'm going to finally setup a complete environnement with a client and a proxy to stop running into weird problem like thoses, i will solve all issues and report back here to help new users

**Comment by Sceat** [comment]
Concerning the item problem i solved it by using
```js
this.client.write('set_slot', {
    windowId: 0,
    slot: 36,
    item: {
        present: true,
        itemId: 608,
        itemCount: 1,
    },
})
```
instead of `prismarineItem.toNotch(item)` so i guess the module is not `1.13.2` ready yet

**Comment by rom1504** [comment]
Indeed prismarine-item is not ready yet

**Comment by rom1504** [comment]
interesting issue,but not a nmp issue, open in relevant modules if still needed

**Comment by Sceat** [comment]
for people running into the issue, follow up here [prismarine-chunk#57](https://github.com/PrismarineJS/prismarine-chunk/issues/57)
