### ISSUE TITLE
1.13.2 map_chunk packet crash the game

### ISSUE THREAD

**Issue by Sceat** [PrismarineJS/node-minecraft-protocol#608]
After updating libs with `npm update` i can't load chunks anymore, the client show loading terrain, then a brief saving world, then shutdown with [this unexpected error](https://ghostbin.com/paste/br46b)

#### Reproduce with 

```js
const mc = require('minecraft-protocol')
const Chunk = require('prismarine-chunk')('1.13.2')
const Block = require('prismarine-block')('1.13.2')
const Vec3 = require('vec3')
var server = mc.createServer({
	'online-mode': false,
	encryption: true,
	host: '0.0.0.0',
	port: 25565,
	version: '1.13.2',
})

var chunk = new Chunk()

// const BIOME_PLAINS = 1
// const BLOCK_GRASS = 8

// chunk.initialize((x, y, z) => {
// 	chunk.setSkyLight(new Vec3(x, y, z), 15)
// 	return new Block(BLOCK_GRASS, BIOME_PLAINS)
// })

for (var x = 0; x < 16; x++) {
	for (var z = 0; z < 16; z++) {
		chunk.setBlockType(new Vec3(x, 5, z), 1)
		for (var y = 0; y < 256; y++) {
			chunk.setSkyLight(new Vec3(x, y, z), 15)
		}
	}
}

server.on('login', function(client) {
	client.write('login', {
		entityId: client.id,
		levelType: 'default',
		gameMode: 0,
		dimension: 0,
		difficulty: 2,
		maxPlayers: server.maxPlayers,
		reducedDebugInfo: false,
	})
	client.write('map_chunk', {
		x: 0,
		z: 0,
		groundUp: true,
		bitMap: 0xffff,
		chunkData: chunk.dump(),
		blockEntities: [],
	})
	client.write('position', {
		x: 15,
		y: 10,
		z: 15,
		yaw: 137,
		pitch: 0,
		flags: 0x00,
	})
})
```

**Comment by rom1504** [comment]
Ok, maybe dump still has some bugs in prismarine-chunk 1.13
@lefela4 any progress on your version of chunk 1.13 ?

**Comment by rom1504** [comment]
This is a bug for prismarine-chunk though, not for node-minecraft-protocol ;)

**Comment by rom1504** [comment]
no it's ok

**Comment by Sceat** [comment]
prismarine-chunks also seems to only use global palette instead of optimized section palettes w variable `bitsPerBlock` 
_see [#47 (comment)](https://github.com/PrismarineJS/prismarine-chunk/pull/47#issuecomment-443559893)_

I'm reading on chunks format to help on this but it really seems too complex for my experience, i'll see what i can do though

**Comment by Sceat** [comment]
@DeltaEvo could u take a look into the chunk implementation see if u find something :)

**Comment by rom1504** [comment]
not a nmp issue
