### ISSUE TITLE
bug useing proxy (example code form github)

### ISSUE THREAD

**Issue by sbh1311** [PrismarineJS/node-minecraft-protocol#620]
i got that bug when i try to join a server useing a proxy and its just wont login , is it the problem with the proxy or maybe the server itself ?
this is the code i used [https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_http_proxy/client_http_proxy.js](url)
or just look down

![image](https://user-images.githubusercontent.com/16293954/53956150-7ff49500-40e3-11e9-9775-563e5d14d614.png)

const mc = require('minecraft-protocol')
const Http = require('http')

if (process.argv.length < 6 || process.argv.length > 8) {
  console.log('Usage : node client_http_proxy.js <host> <port> <proxyHost> <proxyPort> [<name>] [<password>]')
  process.exit(1)
}

const proxyHost = process.argv[4]
const proxyPort = process.argv[5]

const client = mc.createClient({
  connect: (client) => {
    const req = Http.request({
      host: proxyHost,
      port: proxyPort,
      method: 'CONNECT',
      path: process.argv[2] + ':' + parseInt(process.argv[3])
    })
    req.end()

    req.on('connect', function (res, stream) {
      client.setSocket(stream)
      client.emit('connect')
    })
  },
  username: process.argv[6] ? process.argv[6] : 'echo',
  password: process.argv[7]
})

client.on('connect', function () {
  console.info('connected')
})
client.on('disconnect', function (packet) {
  console.log('disconnected: ' + packet.reason)
})
client.on('end', function () {
  console.log('Connection lost')
})
client.on('chat', function (packet) {
  const jsonMsg = JSON.parse(packet.message)
  if (jsonMsg.translate === 'chat.type.announcement' || jsonMsg.translate === 'chat.type.text') {
    const username = jsonMsg.with[0].text
    const msg = jsonMsg.with[1]
    if (username === client.username) return
    client.write('chat', { message: msg })
    console.log(jsonMsg.with[1])
  }
})

**Comment by rom1504** [comment]
What minecraft version ?
The error is saying it's not supported.

**Comment by sbh1311** [comment]
@rom1504 waterfall 1.12.2

**Comment by rom1504** [comment]
Your server is messing with the autoversion detection. Try setting the version in the option.

**Comment by sbh1311** [comment]
@rom1504 how to set it up?

**Comment by rom1504** [comment]
Well in the code of the example you're using there are options, for example the username, add the version at the same location.

**Comment by sbh1311** [comment]
@rom1504 
i tried to put version: "1.12.2", but its now show me difrent error (see pic)
maybe its just the server?
![image](https://user-images.githubusercontent.com/16293954/54028329-543de180-41ad-11e9-9106-e6012b447b78.png)

is it possble to fix?

**Comment by rom1504** [comment]
Yeah that's not what I said you should do. Read again

**Comment by sbh1311** [comment]
@rom1504 ok so i fixed the code so firsts tnx for the help and second 
there a new bug i found and i dont know how to fix it .
when i "read" the msgs its only read player msgs and not msgs sent form the server is there a fix for it?

**Comment by rom1504** [comment]
What is your code ?

**Comment by sbh1311** [comment]
@rom1504 

this is my code its a little change from the exemple code

`client.on('chat', function(packet) {
  // Listen for chat messages and echo them back

  var hello = "hello";
  var bye = "good bye see you soon";  
  var help = "just talk to me for exemple say : hi,bye";
  var kick = "/kick" + username;

  var jsonMsg = JSON.parse(packet.message);
  if(jsonMsg.translate == 'chat.type.announcement' || jsonMsg.translate == 'chat.type.text') {
    var username = jsonMsg.with[0].text;
    var msg = jsonMsg.with[1];
    if(username === client.username) return;

    // in-game commands here

    console.info(jsonMsg.with[1])
  }

  bot.on('message', message => {
    if (message.content === prefix + CMD) {
      message.channel.send(msg);
    }
  });
  });  `

**Comment by rom1504** [comment]
Can you format your code so it's readable (see https://help.github.com/en/articles/creating-and-highlighting-code-blocks) ?

**Comment by rom1504** [comment]
What do you expect to happen and what actually happens ?

**Comment by sbh1311** [comment]
@rom1504 
i expect form the bot to say from exemple
<user> msg
<server> msg
the problem i can only get the <user> work and not the server msg just show undefined

**Comment by rom1504** [comment]
Ok. The server message is probably formatted differently.
Try to `console.log(jsonMsg)` directly

**Comment by sbh1311** [comment]
@rom1504 ok i fixed all the bugs thanks
