### ISSUE TITLE
Read chat from an online-mode=true server, without password?

### ISSUE THREAD

**Issue by DexterHill0** [PrismarineJS/node-minecraft-protocol#624]
I am trying to read the chat from a small server, that I do not host. I believe the server is in online mode. Is it possible, without creating another Minecraft account, to log in as a 'fake player' that _only_ can read messages?
I am testing on my own sever. I have tried just removing the password entirely, but that doesn't work. I get errors like: `[10:50:33 ERROR]: Username 'Reader' tried to join with an invalid session
[10:50:33 INFO]: /<IP> lost connection: Failed to verify username!
` I have also tried using yggdrasil to authenticate a user but that also doesn't work.
I am trying to use just the default chat read example, without the password, on an online 1.13.2 vanilla server.

```var mc = require('minecraft-protocol');
var ygg = require('yggdrasil')({
  //Optional settings object
  host: 'https://authserver.mojang.com' //Optional custom host. No trailing slash.
});
 
//Authenticate a user
ygg.auth({
  token: '', //Optional. Client token.
  agent: '', //Agent name. Defaults to 'Minecraft'
  version: 1, //Agent version. Defaults to 1
  user: 'Reader', //Username
  pass: 'Reader1234' //Password
}, function(err, data){});
 
var mc = require('minecraft-protocol');
var client = mc.createClient({
  host: "<IP>",   // optional
  port: 25565,         // optional
  username: "Reader",
  password: "Reader1234",
});
client.on('chat', function(packet) {
  // Listen for chat messages and echo them back.
  var jsonMsg = JSON.parse(packet.message);
  if(jsonMsg.translate == 'chat.type.announcement' || jsonMsg.translate == 'chat.type.text') {
    var username = jsonMsg.with[0].text;
    var msg = jsonMsg.with[1];
    if(username === client.username) return;
    client.write('chat', {message: msg});
  }
});
 ```
These are the sorts of scripts I am trying out. Most just error with: `Error: Invalid credentials. Invalid username or password.`
So, is it possible to read chat from an online-mode=true server, without entering a password?

Thanks.

EDIT: fixed code mistake, hidden ip

**Comment by rom1504** [comment]
Answer is of course no, authentication is not for nothing.

**Comment by DexterHill0** [comment]
Yeahhh, that's what I thought. I guess it's too much of a security vulnerability.
What do you recommend then? A new Minecraft account for just this?

Thanks again.

**Comment by rom1504** [comment]
Yeah you have to use a minecraft account to connect to online mode servers.
You can either get an account or use offline mode servers.

(One way to get an account could be something like mcleaks but it might not be a good idea, you could get banned)
