### ISSUE TITLE
0xFE ping length is calculated incorrectly (affects BungeeCord/Spigot)

### ISSUE THREAD

**Issue by asiekierka** [PrismarineJS/node-minecraft-protocol#63]
len should be len: 3 + 2*host.length + 4, due to the fact host is reencoded to UTF-16.

**Comment by deathcap** [comment]
0xfe ping is supported by modern the protocol, but not yet fully by node-minecraft-protocol, leaving this here for reference: https://github.com/PrismarineJS/node-minecraft-protocol/issues/332
