### ISSUE TITLE
createServer maxPlayers does nothing

### ISSUE THREAD

**Issue by leumasme** [PrismarineJS/node-minecraft-protocol#632]
I am just testing arround with making a pingable server and so far wrote this
`mc = require("minecraft-protocol")

var serveroptions = {
    "port": 25565,
    "host": "127.0.0.1",
    "kickTimeout": 100000, // Kick after X ms without Keepalive, default 10s
    "checkTimeoutInterval": 4000, // Send Server Keepalive every X seconds, default 4s
    "online-mode": false,
    "beforePing": (response,client)=>{console.log(response); return response}, // Modify Ping
    "motd": "NodeJS Minecraft Server", // MOTD, modifyable in beforePing
    "maxPlayers": 13,
    "keepAlive": true, // Send Keepalive Packets? Default true
    "version": 47, // MOTD only or also connections?
    "customPackets": {}, // ??? not referenced anywhere
    // "errorHandler" function overwrite
    // "stream": ?
    // "connect": relevant if using client through socks/http proxy
    "hideErrors": false
}
mc.createServer(serveroptions)`

Now the problem is that serveroptions.maxPlayers does not seem to do anything, instead stays at the default 20.
When making beforePing log response, it has "players: { max: 20, online: 0, sample: [] }"
When pinging it with a game client, its 20
When logging client.maxPlayers, its undefined.
All other arguments work, for example the serveroptions.motd works as expected.

**Comment by leumasme** [comment]
Note that the "DEBUG="minecraft-protocol" node serverTest.js" wich is mentioned in the issue guide gives an unknown command "DEBUG" not found, as i am on windows.

**Comment by leumasme** [comment]
`var s = mc.createServer(serveroptions)
s.maxPlayers = 13`
Works, but the way with options does not.

**Comment by rom1504** [comment]
it's `max-players`, look at the doc

**Comment by leumasme** [comment]
@rom1504 
`mc.createServer(options)
Returns a Server instance and starts listening. All clients will be automatically logged in and validated against mojang's auth.

options is an object containing the properties :

port : default to 25565
host : default to localhost
kickTimeout : default to 10*1000 (10s), kick client that doesn't answer to keepalive after that time
checkTimeoutInterval : default to 4*1000 (4s), send keepalive packet at that period
online-mode : default to true
beforePing : allow customisation of the answer to ping the server does. It takes a function with argument response and client, response is the default json response, and client is client who sent a ping. It can take as third argument a callback. If the callback is passed, the function should pass its result to the callback, if not it should return.
motd : default to "A Minecraft server"
maxPlayers : default to 20 <-------
keepAlive : send keep alive packets : default to true
version : 1.8 or 1.9 : default to 1.8
customPackets (optional) : an object index by version/state/direction/name, see client_custom_packet for an example
errorHandler : A way to override the default error handler for client errors. A function that takes a Client and an error. The default kicks the client.
stream : a stream to use as connection
connect : a function taking the client as parameter and that should client.setSocket(socket) and client.emit('connect') when appropriate (see the proxy examples for an example of use)
hideErrors : do not display errors, default to false
mc.Server(version,[customPackets])`

The doc very clearly says that its called mayPlayers.
Also; ctrl-f for "max-players" in docs finds nothing.

**Comment by rom1504** [comment]
ok, now fixed, update to 1.9.3
