### ISSUE TITLE
Make it not crash on unknown protocol version

### ISSUE THREAD

**Issue by JuniorJPDJ** [PrismarineJS/node-minecraft-protocol#638]
Hi,
The server is getting crashed when I try to connect with version which is not supported by the library.
It's not the best handling of unknown game version.
I'm trying with 1.14.3, I bet it would be the same with other unsupported version.

```
/usr/bin/node index.js
Server listening on 127.0.0.1:25567
  minecraft-protocol read packet handshaking.set_protocol +0ms
  minecraft-protocol {
  minecraft-protocol   "protocolVersion": 490,
  minecraft-protocol   "serverHost": "localhost",
  minecraft-protocol   "serverPort": 25567,
  minecraft-protocol   "nextState": 2
  minecraft-protocol } +1ms
/home/juniorjpdj/Cloud/dev/JS/AuthServer/node_modules/minecraft-protocol/src/transforms/framing.js:66
          } else { throw e }
                   ^

TypeError: Cannot read property 'protocol' of null
    at createProtocol (node_modules/minecraft-protocol/src/transforms/serializer.js:20:34)
    at createSerializer (node_modules/minecraft-protocol/src/transforms/serializer.js:26:25)
    at Client.setSerializer (node_modules/minecraft-protocol/src/client.js:38:23)
    at Client.set state [as state] (node_modules/minecraft-protocol/src/client.js:104:10)
    at Client.onHandshake (node_modules/minecraft-protocol/src/server/handshake.js:20:20)
    at Object.onceWrapper (events.js:281:20)
    at Client.emit (events.js:193:13)
    at FullPacketParser.deserializer.on (node_modules/minecraft-protocol/src/client.js:82:12)
    at FullPacketParser.emit (events.js:193:13)
    at addChunk (node_modules/readable-stream/lib/_stream_readable.js:297:12)

Process finished with exit code 1
```

**Comment by roblabla** [comment]
Unfortunately, we can't really support unknown versions of the protocols, since the library won't know how to decode the packets. Is there a specific behavior you expect?

**Comment by JuniorJPDJ** [comment]
I expect not to crash whole server but just disconnect the client and show a warning in console.log or something.
I already workarounded this with code like this, but it's not clean solution - I'd like it to be fixed in your code.

```javascript
// Workaround as hell (still better than having crashing server)
server.on('connection', function(client){
    let listeners = client.listeners('set_protocol');
    client.removeAllListeners('set_protocol');
    client.prependOnceListener('set_protocol', function (packet){
        if(packet.protocolVersion > 480){
            client.end("Server is not compatible with your version of game :/");
        } else {
            for(let listener of listeners)
                listener(packet);
        }
    });
});
```

Also It works with clear client, but when I try to connect through bungeecord, the bungee disconnects from the server, but client doesn't disconnect from the bungee, which is weird - but it is not your bug probably.

**Comment by rom1504** [comment]
fixed with https://github.com/PrismarineJS/node-minecraft-protocol/pull/640 and published as 1.9.2, just update.
That bug was only present when you don't set the server version and it does auto version detection.
You may want to specify the version you want to support in createServer version option if you don't want to use that auto version detection feature.

**Comment by JuniorJPDJ** [comment]
@rom1504 Can I specify the list?
I want to support more than one version.

**Comment by JuniorJPDJ** [comment]
Also maybe fixing "auto detection" to allow only known versions of protocol would be nice?

**Comment by rom1504** [comment]
yes that's what https://github.com/PrismarineJS/node-minecraft-protocol/pull/640 does
can't specify a list currently, you can only support all supported versions of the protocol or one

**Comment by rom1504** [comment]
if you really need to support to subset of the supported versions, you can always check client.version and kick the client you don't want to support.
You can open an issue for this if you think that's an useful feature though (what's the use case ?)

**Comment by JuniorJPDJ** [comment]
> yes that's what #640 does
Oh sorry, I misread it, thanks ;)

> if you really need to support a subset of the supported versions, you can always check client.version and kick the client you don't want to support.
> You can open an issue for this if you think that's an useful feature though (what's the use case ?)

Usecase is to support versions which eg. are supported by my other servers (I'm writing AuthServer).
Anyway I'll be just ok with that fix and implement it at my own. Thank you very much for fast fix :)
