### ISSUE TITLE
Incoming Server Query Ping fails unrecoverably if Pinging Client has different Version

### ISSUE THREAD

**Issue by leumasme** [PrismarineJS/node-minecraft-protocol#642]
In my Tests i have used 1.8/47 as the Server Version and an 1.12.2/340 as the Client version, with a vanilla client and a server made with this.

The problem is that any Pings from the client with the wrong version fail completely, logging
`Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd`
into the console.

When pinging from an 1.8 vanilla client (same as server version), everything works as expected.
This behaviour of rejecting pings from a different version is not good. 
I do not want players on the wrong version to think that my server does not even exist.

When adding a beforePing function and logging the second argument, the Client argument, we see that the clients connection is already ended before beforePing ever gets it.
( Client: `{ ... ended: true, _endReason: "{"text":"Wrong protocol version, expected: 47 and you are using: 340"}", ... }` )

This is the Server rejecting the clients connection. When searching for part of the end reason string, it can be found in server\minecraft-protocol\src\server\handshake.js

Please fix this.
Even though my code is pretty much the simplest possible, here it is:

```js
mc = require("minecraft-protocol")

beforePing = (response,client,c)=>{
    console.log(client);
    c(null,response);
    return;
}

var serveroptions = {
    "port": 25565,
    "host": "127.0.0.1",
    "kickTimeout": 100000, // Kick after X ms without Keepalive, default 10s
    "checkTimeoutInterval": 4000, // Send Server Keepalive every X seconds, default 4s
    "online-mode": false,
    "beforePing": beforePing, // Modify Ping
    "motd": "It works.", // MOTD, modifyable in beforePing
    "maxPlayers": 13,
    "keepAlive": true, // Send Keepalive Packets? Default true; Dont proxy keepalive if true
    "version": 47, // protocol version
    "customPackets": {}, // ??? not referenced anywhere
    // "errorHandler" function overwrite
    // "stream": ?
    // "connect": relevant if using client through socks/http proxy
    "hideErrors": false
}
var s = mc.createServer(serveroptions)
s.maxPlayers = -1337
```

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/server/handshake.js#L17

I guess if the client.state is STATUS, we should just short-circuit the version check? STATUS is the same for all protocols since netty rewrite.

**Comment by unixfox** [comment]
I'm also encountering this error when trying to make an authentication system that use Minecraft. My program doesn't care about the protocol version, it just wants to fetch the logged username then kick the player.
