### ISSUE TITLE
JSDoc support

### ISSUE THREAD

**Issue by Saiv46** [PrismarineJS/node-minecraft-protocol#643]
* Why in-code documentation?
It is easier to maintain than filling in missing features in out-of-code documentation.

* Why JSDoc?
JSDoc is built-in in many IDEs, so it comes handy when implementing your own 
Minecraft server/client/proxy.

**Comment by rom1504** [comment]
I think out of doc is better. Better coherence of the doc and in a format
that makes sense for humans (markdown) and that is transformable to
something even better (html)
Jsdoc bloats the code and doesn't provide much information to users, since
they don't look at the code.
