### ISSUE TITLE
You have to add @types/node in the dependencies 

### ISSUE THREAD

**Issue by BRA1L0R** [PrismarineJS/node-minecraft-protocol#644]
I was trying to use ping and it gave me an error, just installed @types/node and it worked

**Comment by rom1504** [comment]
Are you coding in typescript ? What's the error ?
@types/node is definitely not needed in js

**Comment by BRA1L0R** [comment]
Yes i am, since the library supports typescript (i saw the .d.ts) i think adding @types/node to the dependencies is what you should do

The error said that the library events was not installed

**Comment by roblabla** [comment]
NMP does not use typescript (it merely provides types), so adding `@types/node` is definitely **not** what we should do.

I believe we should be including a `types` dependency directive in the .d.ts: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-

See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gulp/v3/index.d.ts#L7

**Comment by rom1504** [comment]
fixed and released
