### ISSUE TITLE
Any way of sending private messages to a user ?

### ISSUE THREAD

**Issue by alexbudin** [PrismarineJS/node-minecraft-protocol#645]
Hi guys,

Is there any way of sending a specific minecraft user a private message at any point, but not when they write first?

Thank you.

**Comment by plexigras** [comment]
> but not when they write first

what does that mean?

**Comment by roblabla** [comment]
Are you writing a server? A client? If a client:

Depending on server/plugin, you need to send a chat message with one of those:

```
/tell roblabla hi
/msg roblabla hi
/whisper roblabla hi
```

**Comment by alexbudin** [comment]
@roblabla From my node app (where im logged in as a client) i need to send a message to a user that is on my minecraft server.

Ive only seen stuff that happens in the "chat" event callback thats triggered when someone writes to my client user, but nothing like:

client.write(USER_IM_SENDING MESSAGE_TO, 'chat', {message: msg});

or an example on how to send a message to a specific user.

are there specific properties i can set in the message object im sending? like user im sending to? type of message (tell, msg, whisper) ?

Does it make sense?

Thank you.

**Comment by roblabla** [comment]
You're supposed to just write a message with the command. E.G. `client.write('chat', { message: '/tell roblabla ' + msg });`

https://wiki.vg/Protocol#Chat_Message_.28serverbound.29

There is no non-command way to send a chat message to another players.

**Comment by alexbudin** [comment]
@roblabla Thank you so much. I did not know about that wiki page. That is extremely useful!
