### ISSUE TITLE
Using The Proxy

### ISSUE THREAD

**Issue by FoamyTheFag** [PrismarineJS/node-minecraft-protocol#647]
So I would like to set up a node-minecraft-protocol proxy so I can identify a packet and implement it into one of my mineflayer bots. I used the proxy.js example code, 0 changes, straight copy pasted. I am doing `node proxy.js localhost 1.8.9` as my start command, and I have a vanilla 1.8.9 server running on my PC.

The problem:
I am not seeing any messages being logged in the console, not even a log in message. All that it shows is the run command, and then a completely empty console. I have tried using my actual IP instead of localhost, as well as another server not run by me, all with the same result of an empty console.

**Comment by rom1504** [comment]
Did you connect to the proxy using your vanilla client ?

**Comment by FoamyTheFag** [comment]
No, how would I go about doing that?

**Comment by rom1504** [comment]
connect to 127.0.0.1:25566

**Comment by rom1504** [comment]
Fixed
