### ISSUE TITLE
Protocol only works on major verions

### ISSUE THREAD

**Issue by dariusc93** [PrismarineJS/node-minecraft-protocol#65]
I notice that the protocol only works on major version of Minecraft. This isnt a major bug or issue, but as a suggestion was to make it where the protocols are stored in different libs and defined in the code with a version so it would look like

var mc = require('minecraft-protocol');
var client = mc.createClient({
  host: "localhost",   // optional
  port: 25565,         // optional
  username: "email@example.com",
  password: "12345678",
  version: "1.6.2",
});

Which could help alot.

I may submit a PR to implement this

**Comment by roblabla** [comment]
Nearly a year later, mc-proto-def exists (though it is called minecraft-data). `node-minecrat-data`, the library we use for it, exposes the multiple versions minecraft-data supports (currently only 1.8 and a pre-1.9, but we can add the older versions as we go). Protocols is slowly approaching completion too, as seen by #162 . We're making progress !

**Comment by wtfaremyinitials** [comment]
:smile:
