### ISSUE TITLE
How can I prevent the bot from getting kicked for afk

### ISSUE THREAD

**Issue by MFDGaming** [PrismarineJS/node-minecraft-protocol#651]
I need some help thank you

**Comment by roblabla** [comment]
Make it move every now and then?

**Comment by MFDGaming** [comment]
How

**Comment by MFDGaming** [comment]
@roblabla

**Comment by rom1504** [comment]
Read the doc and examples

**Comment by MFDGaming** [comment]
Where are examples?

**Comment by MFDGaming** [comment]
@rom1504

**Comment by rom1504** [comment]
See mineflayer readme

**Comment by MFDGaming** [comment]
I am using node-Minecraft-protocol not mineflayer

**Comment by rom1504** [comment]
Ok, so first you need to reimplement mineflayer then you can look at
mineflayer doc to see how to do it

**Comment by rom1504** [comment]
Troll, closing
