### ISSUE TITLE
What JSON does one use to send the TAB playerlist to the client

### ISSUE THREAD

**Issue by Charsy89** [PrismarineJS/node-minecraft-protocol#652]
If you are reporting a bug please report on these points :

* what you want to do (the objective in english)
Send the correctly formatted json for the TAB playerlist to the client
* what you tried (the code)
I tried using the info from the [documentation](http://minecraft-data.prismarine.js.org/?v=1.13.2&d=protocol#toClient_playerlist_header), as stated in the api.md file:
```js
client.write("playerlist_header",{
	header:"test",footer:"test"
});
```
It sends on client connect
* what happened
Client disconnected and reported malformed JSON
* what you expected to happen
Successful connection, seeing the playerlist correctly

In particular it will be useful to provide these informations :

* what happens when using a node-minecraft-protocol example?
Could not find an example with a playerlist implementation
* what minecraft-protocol version?
1.9.4
* what server version?
1.14.4
* which server? (spigot, paper, vanilla, any particular plugins ?)
minecraft-protocol server
* what's the output of DEBUG="minecraft-protocol" node your_script.js ?
https://pastebin.com/rBQ74YNU
* what's the error msg?
Nothing in the console, but here's the client message:
`Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $`
* what script is used (full code)?
I'll reply with it if one absolutely needs it

**Comment by rom1504** [comment]
You need to pass a json in the string.

**Comment by Charsy89** [comment]
What should it look like?

**Comment by Charsy89** [comment]
and that's strange because it says here that it should be a string
![image](https://user-images.githubusercontent.com/28523197/64045313-2adf8c00-cb26-11e9-80d0-8162be94e303.png)

**Comment by rom1504** [comment]
Yes a json is a string.
No idea how it should look like. Use the proxy example to get some usual values. (You can also look if wiki.vg has some example)

**Comment by Charsy89** [comment]
Ok, thanks. Where is this wiki.vg?

**Comment by Charsy89** [comment]
Nevermind, found it. thanks for the help!
