### ISSUE TITLE
Protocol version -1 is not supported

### ISSUE THREAD

**Issue by LXGaming** [PrismarineJS/node-minecraft-protocol#653]
I'm trying to return a custom https://wiki.vg/Server_List_Ping#Response packet to certain clients which are spam pinging our Minecraft network.

As per https://wiki.vg/Server_List_Ping#Handshake the protocol version can be set to -1 if the client is requesting the status from the server. However this is not supported in [handshake.js](https://github.com/PrismarineJS/node-minecraft-protocol/blob/ffaa9f7990d625f2ed7186ecf71888a213cd9d96/src/server/handshake.js)

A fix to this would be to allow the -1 protocol version as long as it's only requesting the server status and not attempting to login.

**Comment by rom1504** [comment]
Handling the error on your side would make more sense.
Reopen if you still think something needs to be done here.
