### ISSUE TITLE
Dependency resolution issue

### ISSUE THREAD

**Issue by themoonisacheese** [PrismarineJS/node-minecraft-protocol#658]
Hi

I wrote 2bored2wait, a proxy that depends on minecraft-protocol. 
About 2 people have contacted me in the last week because they have had problems with lodash not being installed automatically. My code doesn't depend on lodash, but minecraft-protocol does. As far as I can tell, it should be installed correctly, but apparently it's not.

I don't think there's much you can do, but if there is, there's your report.

logs at https://github.com/themoonisacheese/2bored2wait/issues/25

**Comment by rom1504** [comment]
the issue is very likely your package-lock.json. Remove it and add it in
.gitignore

**Comment by themoonisacheese** [comment]
i've done that. hopefully this fixes things, I expect it will.
