### ISSUE TITLE
Client gets disconnected when attacking entity

### ISSUE THREAD

**Issue by Xenorio** [PrismarineJS/node-minecraft-protocol#660]
First of all, i never did anything related to Minecraft server communication until a few hours ago, so this is probably a noob issue.

I am trying to make a bot that basically just stands in one spot and attacks nearby entities. I want to use that to AFK farm mobs from a mobfarm.

I have implemented some entity tracking to see which entities are around the player, and that's working absolutely fine, but as soon as i send a "use_entity" packet to attack one of them the client disconnects. There is no output whatsoever and the script even keeps running, but on the server side there is a disconnect without any apparent reason ("Xenorio lost connection: Disconnected")

Here's the code i wrote: [https://hastebin.com/ekebelixak.js](https://hastebin.com/ekebelixak.js)
I tried making what's doing what as clear as possible using comments.

The server i'm trying this on is 1.14.4 PaperMC

**Comment by rom1504** [comment]
Why don't you use mineflayer ?
If not, you can copy the logic you want here from mineflayer

**Comment by Xenorio** [comment]
As i said, i'm trying to do this on a 1.14.4 server. Mineflayer only supports versions up to 1.12

**Comment by Xenorio** [comment]
I tinkered around for a bit and found out that the reason the client is getting kicked for seems to be this:

```
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(5) + length(1) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 5)
```

I have no clue what that means tho

**Comment by rom1504** [comment]
> If not, you can copy the logic you want here from mineflayer

**Comment by rom1504** [comment]
And about your error it most likely means you are sending the packet wrong

**Comment by Xenorio** [comment]
I have no idea what i'd even need and how to implement it. As i said, i never worked with Minecraft protocol stuff.

And what i'm sending in the packet is an integer that is the entity ID i want to attack (in the code i sent it was a string, but i fixed that. error stays the same tho) in the "target" field and integer 1 in the "type" field (which should mean attacking).

**Comment by rom1504** [comment]
ok, I advise you use mineflayer if you don't want to work with packets
