### ISSUE TITLE
How to determine packet argument names

### ISSUE THREAD

**Issue by The-Box1** [PrismarineJS/node-minecraft-protocol#663]
`client.write('keep_alive', {
      keepAliveId: packet.keepAliveId
    })`

With the keep alive packet usage in keepalive.js the name of the argument is **keepAliveId** followed by the data.

How do I determine what the name of this variable should be for a packet such as **spectate**?

**Comment by plexigras** [comment]
> How do I determine what the name of this variable should be for a packet such as spectate?

you mean `target`?  
http://minecraft-data.prismarine.js.org/?d=protocol#toServer_spectate

**Comment by The-Box1** [comment]
That's it, thank you
