### ISSUE TITLE
unsupported/unknown protocol version: 575

### ISSUE THREAD

**Issue by RubyTheRose** [PrismarineJS/node-minecraft-protocol#667]
If you are reporting a bug please report on these points 👍 

**Java Edition 1.15.1 | 575 | 2227**
using auto version.

* what you want to do (the objective in english) successful login.
* what you tried (the code) attempt connection
* what happened: no connection
* what you expected to happen: a connection

In particular it will be useful to provide these informations :

"minecraft-protocol-forge": "^1.0.0",
"minecraft-protocol": "^1.9.4",

**Comment by rom1504** [comment]
Yeah 1.15 is not supported yet. I'll probably add it in the next days

**Comment by RubyTheRose** [comment]
> Yeah 1.15 is not supported yet. I'll probably add it in the next days
Alright sounds good.

**Comment by Darvinschl** [comment]
When will you add 1.15? I would be really thankful :)

**Comment by rom1504** [comment]
it's done.
Out of curiosity, why do you need it so soon after the update is out ? (any server updated yet ?)

**Comment by Darvinschl** [comment]
Wow, thank you so much!
Iam running a 1.15 survival server and wanted to build an afk bot :)
An yeah, there are less updated servers in general.
