### ISSUE TITLE
Run inside browser

### ISSUE THREAD

**Issue by Darvinschl** [PrismarineJS/node-minecraft-protocol#672]
Is it possible to run it with the Browser through a html file?
I already tried Browserify for the require method but it didn’t work.

**Comment by rom1504** [comment]
Hello,
There is no TCP in the browser, so you cannot connect to a normal
minecraft server in the browser.
However, what you can do is run a websocket proxy (like done in
https://github.com/voxel/voxel-clientmc) and then connect to that in
the browser with minecraft-protocol.
