### ISSUE TITLE
How do I make the bot respawn?

### ISSUE THREAD

**Issue by creepinson** [PrismarineJS/node-minecraft-protocol#677]
If you are reporting a bug please report on these points :

* what you want to do (the objective in english)
* what you tried (the code)
* what happened
* what you expected to happen

In particular it will be useful to provide these informations :

* what happens when using a node-minecraft-protocol example?
* what minecraft-protocol version?
* what server version?
* which server? (spigot, paper, vanilla, any particular plugins ?)
* what's the output of DEBUG="minecraft-protocol" node your_script.js ?
* what's the error msg?
* what script is used (full code)?

Hello there. I am not sure how to get my bot to respawn on my forge server, as it just sits there being invisible and on my minimap after it dies. I can't get it to do anything since it is dead. I tried using the mineflayer code for respawning but it doesn't work either.

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/health.js#L25
your server may have a protection against not full implementation of vanilla
