### ISSUE TITLE
What is the definition of type Position.

### ISSUE THREAD

**Issue by ShirasawaSama** [PrismarineJS/node-minecraft-protocol#678]
I tried to break a block by [block_dig](http://minecraft-data.prismarine.js.org/?d=protocol#toServer_block_dig)

But I don't know what the parameter `Position` is.

So I tried the following code:

```ts
const location = { x: -251, y: 67, z: 152 }
client.write('block_dig', {
  location,
  face: 1,
  status: 0
})
setTimeout(() => {
  client.write('block_dig', {
    location,
    face: 1,
    status: 2
  })
}, 1000)
```

and:

```ts
const encodePosition = (x: number, y: number, z: number) => ((x & 0x3FFFFFF) << 38) | ((z & 0x3FFFFFF) << 12) | (y & 0xFFF)
const location = encodePosition(-251, 67, 152)
client.write('block_dig', {
  location,
  face: 1,
  status: 0
})
setTimeout(() => {
  client.write('block_dig', {
    location,
    face: 1,
    status: 2
  })
}, 1000)
```

I also try to break the block in creative and survival mode, but it doesn't work.

Wiki.vg: [Position](https://wiki.vg/Protocol#Position) and [Player Digging](https://wiki.vg/Protocol#Player_Digging)

- **Server**: Paper-1.14.4-178
- **Nodejs**: 12.11.0
- **minecraft-protocol**: 1.11.0

**Comment by rom1504** [comment]
You need to implement a lot more things if you don't want to use mineflayer.
For example of how to use that packet, look at mineflayer code

**Comment by ShirasawaSama** [comment]
```ts
interface Position {
  x: number // Int
  y: number // Int
  z: number // Int
}
```
