### ISSUE TITLE
Minecraft 1.15.2

### ISSUE THREAD

**Issue by nemtudom345** [PrismarineJS/node-minecraft-protocol#682]
When i try to log into a minecraft 1.15.2 server i get an error:
"Error: unsupported/unknown protocol version: 578"

**Comment by youngchief-btw** [comment]
This is because it 1.15.2 is currently not supported

**Comment by nenad-lab** [comment]
I need this node-minecraft-protocol for [another project](https://github.com/ansonfoong/minecraft-discord-chat-bot) and it will not work w/ current minecraft v1.15.2 it's really a bummer that is not automated build - hope that will someone have a time and will to refresh it for current version of minecraft. Or someone have maybe a solution without?

**Comment by rom1504** [comment]
done
