### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by szadol** [PrismarineJS/node-minecraft-protocol#683]
Upon connecting to a Velocity server, client receives the Login Plugin Request packet. It seems that node-minecraft-protocol has problems processing it, which causes the client to disconnect with a "read timed out" message.

> [21:00:41 INFO]: Booting up Velocity 1.0.6-SNAPSHOT (git-5c6163d8-b195)...
> [21:00:41 INFO]: Connections will use NIO channels, Java compression, Java ciphers
> [21:00:41 INFO]: Proxy is running in offline mode!
> [21:00:41 INFO]: Loading plugins...
> [21:00:41 INFO]: Loaded 0 plugins
> [21:00:41 INFO]: Done (1,32s)!
> [21:00:41 INFO]: Listening on /0:0:0:0:0:0:0:0:25565
> [21:06:14 ERROR]: [initial connection] /127.0.0.1:50376: read timed out
> [21:06:14 INFO]: [initial connection] /127.0.0.1:50376 has disconnected

* what minecraft-protocol version?
Release 1.11.0
* which server? (spigot, paper, vanilla, any particular plugins ?)
Velocity 1.0.6, Paper 1.14.4
* what's the output of DEBUG="minecraft-protocol" node your_script.js ?
* what's the error msg?
no errors appear
* what script is used (full code)?
```javascript
const mc = require("minecraft-protocol");
const client = mc.createClient({ host: "localhost", port: 25565, username: "tester", version: 498 });

client.on("packet", packet => console.log(packet));```

**Comment by rom1504** [comment]
> Login Plugin Request

what is this ? is it a custom packet ? if so try to use the custom packet example

**Comment by szadol** [comment]
It's https://minecraft-data.prismarine.js.org/?v=1.14.4&d=protocol#toClient_login_plugin_request

**Comment by rom1504** [comment]
fixed
