### ISSUE TITLE
software license?

### ISSUE THREAD

**Issue by ConradP** [PrismarineJS/node-minecraft-protocol#689]
This is a really neat project and I would love to use it as a component for one of my projects, but I don't see any licensing information stored in the source code : (   

could you please consider adding a [License](https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository) to your project so I (and other potential contributers) know how we can use this project?

**Comment by roblabla** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/package.json#L29 BSD 3-clause is NMP's license.

We should probably add a LICENSE.txt in the repo with the MIT license text.
