### ISSUE TITLE
Can't click the slot of a ContainerWindow

### ISSUE THREAD

**Issue by cosmypower** [PrismarineJS/node-minecraft-protocol#690]
Hello! I tried to recreate the clickWindow() of mineflayer on node-minecraft-protocol because of the incompatibility of 1.15.2, so I did all of that:

` clientt.on('open_window', (window) => {
          clientt.currentWindow = windows.createWindow(window.windowId, window.inventoryType, window.windowTitle, window.slotCount);
          
          if (!windowItems || clientt.currentWindow.id !== windowItems.windowId) {
            clientt.once(`setWindowItems:${clientt.currentWindow.id}`, () => {

              clientt.emit('windowOpen', clientt.currentWindow);
            })
          } else {
            
            let i;
            let item;
            for (i = 0; i < windowItems.items.length; ++i) {
              item = Item.fromNotch(windowItems.items[i])
              clientt.currentWindow.updateSlot(i, item);
            }

            clientt.emit('windowOpen', clientt.currentWindow);
          }

        });

        clientt.on('window_items', (packet) => {

          const window = clientt.currentWindow
          if (!window || window.id !== packet.windowId) {
            windowItems = packet;
            return;
          }

          let i;
          let item;
          for (i = 0; i < packet.items.length; ++i) {
            item = Item.fromNotch(packet.items[i])
            clientt.currentWindow.updateSlot(i, item)
          }

          clientt.emit(`setWindowItems:${clientt.currentWindow.id}`)
        })

        clientt.on('close_window', (packet) => {
          console.log("Closed Window");
          clientt.currentWindow = null;
        })

        clientt.on('windowOpen', (packet) => {
          actionNumber++;
          console.log("Opened Window");
          

          clientt.write('window_click', {
            windowId: packet.id,
            slot: 12,
            mouseButton: 1,
            action: actionNumber,
            mode: 0,
            item: Item.toNotch(packet.slots[12])
          })

          const click = {
            slot: 12,
            mouseButton: 1,
            mode: 0,
            id: actionNumber,
            windowId: packet.id
          }

          if (!packet.transactionRequiresConfirmation(click)) {
            clientt.currentWindow.acceptClick(click);
            console.log("Transaction confirm called");
          }
          
        })

`

It's bad code because I tried everything for some hours and didn't had any luck founding the "correct solution", I updated the item-prismarine for 1.15.2.

All I know it's that the window opens, I do the slot clicking and it closes immediately, maybe because of that, anyway I can't put any timeout there as it closes faster than usain bolt.

Any help it's welcome, thanks.

**Comment by cosmypower** [comment]
DEBUG log:

   1mminecraft-protocol read packet play.open_window +0ms
  1mminecraft-protocol {
  1mminecraft-protocol   "windowId": 1,
  1mminecraft-protocol   "inventoryType": 5,
  1mminecraft-protocol   "windowTitle": "{\"text\":\"§c§lADDICTED2 MAIN MENU\"}"
  1mminecraft-protocol } +0ms
  1mminecraft-protocol read packet play.window_items +15ms
  1mminecraft-protocol {
  1mminecraft-protocol   windowId: 1,
  1mminecraft-protocol   items: [
  1mminecraft-protocol     { present: true, itemId: 349, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 346, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 345, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: true, itemId: 345, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 346, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 349, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 349, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 345, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: true, itemId: 771, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: true, itemId: 771, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: true, itemId: 345, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 349, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: true, itemId: 349, itemCount: 1, nbtData: [Object] },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: false },
  1mminecraft-protocol     { present: false },
...
  }

Opened Window
  writing packet play.window_click
 {
  windowId: 1,
  slot: 12,
  mouseButton: 1,
  action: 1,
  mode: 0,
  item: {
     present: true,
     itemId: 771,
     itemCount: 1,
     nbtData: { type: 'compound', name: '', value: [Object]m }
   }
 }
Transaction confirm called
  read packet play.set_slot
  {
  "windowId": -1,
  "slot": -1,
  "item": {
  "present": false
 }

**Comment by rom1504** [comment]
Hello, what is your objective, what are you trying to do ?

**Comment by cosmypower** [comment]
Hello, I want to create an bot that clicks the compass from a server lobby (that's using waterfall), and then clicks on the slot ID 12 (that which has the skyblock category), but after I send the window_click packet, nothing happens.
And it seems after the window opens, the packet is been sent, the window closes instantly, so I'm asking if someone can help me of that because I really don't know why the packet isn't being sent / the window closes. 
P.S, If it helps: The bot logins in, waits 5000ms, sends the /login command, waits 1500ms, sets quick bar slot to 4, waits again 1000ms, activates the held item, and then I'm just using window_open and window_items to send the window_click packet, and there's where I am stuck to.

**Comment by rom1504** [comment]
not a nmp issue
