### ISSUE TITLE
Connecting to server not working with rcon password

### ISSUE THREAD

**Issue by TTSKarlsson** [PrismarineJS/node-minecraft-protocol#696]
* what you want to do (the objective in english)
I want to connect to the server on a specific IP-address

* what you tried (the code)
```ts
import { createClient } from 'minecraft-protocol'
const client = createClient({password: 'theactualrconpasswordhere'})
const client.connect(7304, '111:222:111:222')
```

* what happened
It says I need a username

* what you expected to happen
I expect it to use the provided rcon password and connect to the server and then being able to parse packet events from that server, like messages and such, something that node-rcon and similar packages can't do.

* what minecraft-protocol version?
latest provided on npm when posting this.

* what server version?
1.15.2

* which server? (spigot, paper, vanilla, any particular plugins ?)
vanilla

* what's the output of DEBUG="minecraft-protocol" node your_script.js ?
That's not valid command line on Windows.

* what's the error msg?
```
'DEBUG' is not recognized as an internal or external command,
operable program or batch file.
```

* what script is used (full code)?
see above

**Comment by rom1504** [comment]
How are you able to use the vanilla client to connect to a vanilla server
using the rcon password alone ?

**Comment by TTSKarlsson** [comment]
It's very off-topic, but if you have to know I'm not using rcon password when playing the game. The rcon password is only used for when connecting remotely with scripts like these to remotely administrate, automate and fetch information from the server continuously.

**Comment by rom1504** [comment]
Ok so you answered your own question. It's not possible to connect to the
game using rcon password. Node-minecraft-protocol is just another way to
connect to the game.

If you want to connect to rcon, use node-rcon

**Comment by TTSKarlsson** [comment]
Thank you.

node-rcon (and about a dozen other rcon implementations I've tried) doesn't provide what this library says it provides, namely fetching all the packets so we can log them.

It doesn't make sense to need to buy an extra minecraft account just to do normal rcon logging, but it's not this librarys fault ofcourse, just a flaw of the game.

**Comment by rom1504** [comment]
If you want to log all the packets you could also put a proxy (using
node-minecraft-protocol) on top of your server. You can do that if you
control the server.

**Comment by TTSKarlsson** [comment]
Yes, I'm aware of a multitude of different ways to parse the log, output or through modding log the ingame packets. But it's not my server.

I was trying to help to do this to a rented server that doesn't allow any shell scripts or mods. That's why it has to be by remote. It also has to be 'realtime' so downloading the log through ftp doesn't solve it either.

I have advised the affected party that it is not possible without having more control over the server.

**Comment by TTSKarlsson** [comment]
This issue can be closed, btw.
