### ISSUE TITLE
Is there any way to join server on 1.15.2 with chunks?

### ISSUE THREAD

**Issue by skyrawr** [PrismarineJS/node-minecraft-protocol#697]
for example hypixel queue works on 1.15.2 and i think they use nodejs servers because:
1. uses very little resources
2. any broken blocks remain until you reconnect (same on a node-minecraft-protocol server)
3. keepalive gets sent every 4 seconds (default for node-minecraft-protocol) and i get kicked after 10 seconds after not responding to keepalive.

so could this be possible with prismarine-chunk or another library?
even a proxy is okay if it works fine, but i prefer keeping only one nodejs server running.

you can find my code [here](https://pastebin.com/ZC7yDNdF)

_sorry for bad english_

**Comment by skyrawr** [comment]
also skins would be nice in online mode

**Comment by rom1504** [comment]
Yes.
For 1.15.2 you'll have to first update prismarine-chunk to 1.15
It supports 1.13 (and previous versions) for now

**Comment by skyrawr** [comment]
Is there any other library or maybe a proxy to load chunks with 1.15.2?

**Comment by rom1504** [comment]
no

**Comment by rom1504** [comment]
use mineflayer
