### ISSUE TITLE
spawn_entity_living doesn't send the position properly in 1.8

### ISSUE THREAD

**Issue by ImHarvol** [PrismarineJS/node-minecraft-protocol#699]
I noticed while working on https://github.com/PrismarineJS/mineflayer/pull/941 that the packet `spawn_entity_living` seems to not send the position properly in version 1.8.

If I send this in 1.8:
```js
client.write('spawn_entity_living', {
          entityId: 8,
          entityUUID: '00112233-4455-6677-8899-aabbccddeeff',
          type: zombieId,
          x: zombiePos.x,
          y: zombiePos.y,
          z: zombiePos.z,
          yaw: 0,
          pitch: 0,
          headPitch: 0,
          velocityX: 0,
          velocityY: 0,
          velocityZ: 0,
          metadata: []
})
```
The bot receives:
```js
Entity {
  ...
  position: Vec3 { x: 0.3125, y: 0, z: 0 },
  ...
}
```
While in other versions the bot receives the right value:
```js
Entity {
  ...
  position: Vec3 { x: 10, y: 0, z: 0 },
  ...
}
```

From 1.8 to 1.9 they changed from i32 to f64. Looks like its not being converted properly. Could that be the problem?

**Comment by rom1504** [comment]
Yes it's the problem.
Mineflayer and flying-squid both have a compatibility layer on top of this
to be able to handle this transparently.

What you can do either :
* Use mineflayer or flying-squid
* Copy paste the compatibility layer in your code
* Create a new package providing that compatibility layer for flying-squid
and mineflayer and other users

First and third point are the best options.
