### ISSUE TITLE
Cannot move using packets on proxy, server either teleports me back or doesnt move

### ISSUE THREAD

**Issue by AkosMaster** [PrismarineJS/node-minecraft-protocol#703]
`

                delta = 0.1
		newPosition = lastPosition;
		newPosition.x += Math.random() > 0.5 ? delta : -delta;
		newPosition.y += Math.random() > 0.5 ? delta : -delta;
		newPosition.z += Math.random() > 0.5 ? delta : -delta;

		client.write("position", newPosition);

		lastPosition = newPosition;
`

this is what I'm using to do antiafk from my proxy client. The server either teleports me back or I just don't appear to move at all. I am interested in how other libraries achieved movement with packets. If anyone knows a reliable method, please help.

(lastPosition is always the last position packet the server sent me)
I am on 1.12.2

**Comment by rom1504** [comment]
you need to send the position every tick
see how mineflayer does it in https://github.com/PrismarineJS/mineflayer/blob/504e8f21a05e2f900bafe66abaf120860b1336f1/lib/plugins/physics.js#L375
