### ISSUE TITLE
Proxy gets randomly disconnected by server after some time. (Sometimes hours)

### ISSUE THREAD

**Issue by AkosMaster** [PrismarineJS/node-minecraft-protocol#710]
If you are reporting a bug please report on these points :

I am trying to build a proxy server based on the 2bored2wait code
I save the login packet and the surrounding chunks upon login so I can connect to the proxy and get sent that information.
It runs fine, I can connect and disconnect later. The proxy is quite laggy but that's expected behaviour. Every server I tried it on however, ends my connection either without any message or just a simple "Lost connection to the server" message.

Here is my code to create the client:

		client = mc.createClient({ // connect to server

				host: config.debug.serverip,
				port: config.debug.serverport,

				username: secrets.username,
				session: authSession, //generated by other program, works perfectly
				version: config.MCversion,

				keepAlive: true,
				skipValidation: true
		})
and my server, probably not at fault:

		server = mc.createServer({ // create a server for us to connect to
				'online-mode': false,
				encryption: true,
				host: '0.0.0.0',
				port: config.ports.minecraft,
				version: config.MCversion,
				'max-players': maxPlayers = 2
		});
I also connect a mineflayer bot to the proxy server when I am not online and disconnect it when I log in.

The issue could be related to socks too.

**Comment by rom1504** [comment]
How long does it take to disconnect ?
Can you produce a minimal example reproducing your issue ?

**Comment by rom1504** [comment]
not enough info
