### ISSUE TITLE
Make it easy for a server to encode a packet once and send it to multiple clients

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#713]
Basically use client.writeRaw + a convenient way to encode packets only once.

use case : https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/plugins/world.js#L62

(@Karang idea)

would make server implementations faster

**Comment by Saiv46** [comment]
`{} !== {}`

Maybe there should be a way to make a cache for that things (WeakMap + Hash)

**Comment by rom1504** [comment]
Invalidating caches is hard. It's better to do this explicitly

**Comment by Karang** [comment]
Why doing complicated things where it just boils down to exposing 3 things:
* A method to serialize a packet and return a buffer
* the list of connected clients
* a way to send a raw packet
Maybe a convenience method can be added to the server:
```javascript
server.writeToClients = (clients, data) {
  const buf = server.serializer.createBuffer(data)
  clients.forEach(client => client.writeRaw(buf))
}
```
The problem with cache is that the buffers will tend to be very short lived. Take for instance a position update packet: it needs to be rebuilt very often and only sent at a point in time, to all players around. But once it is sent, there is no point in keeping it in memory.

The only exception I could think of would be the map_chunk packets, that are fairly large, not modified very often and need to be sent to every new player coming in the area. But I think if we want to do some chunk packet caching, it makes more sense to handle that one in prismarine-chunks
