### ISSUE TITLE
Automatically dump lot of packets to improve benchmark and testing

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#718]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%247%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/PrismarineJS/node-minecraft-protocol/issues/718)

similar to https://github.com/PrismarineJS/minecraft-chunk-dumper

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $7.00)

- [<img src='https://avatars.githubusercontent.com/u/2346494?v=4' alt='rom1504' width=24 height=24> rom1504](https://issuehunt.io/u/rom1504) ($2.00)
- $5.00 have been anonymously funded.
### Submitted pull Requests
- [#842 Add packet cycletests](https://issuehunt.io/r/PrismarineJS/node-minecraft-protocol/pull/842)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/PrismarineJS/node-minecraft-protocol/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by rom1504** [comment]
in progress at https://github.com/PrismarineJS/prismarine-packet-dumper

**Comment by rom1504** [comment]
Idea here :
* Dump a reasonable number of packets per kind (4 maybe) : the raw buffer
* Store that somewhere convenient (some minecraft-protocol-stub repo maybe)
* Build tests for node-minecraft-protocol using that : automatically parse then serialise the packets, check it matches

This can be done first for vanilla, then for some other servers.

This is a good way to fix all the "packet is broken" issue

**Comment by Heath123** [comment]
Would running this on a test server help with packet collection?

**Comment by rom1504** [comment]
Yes but the important thing is to implement the code to do all this,
finding server is easy.

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/prismarine-packet-dumper/issues to know what to do

**Comment by rom1504** [comment]
done in https://github.com/PrismarineJS/node-minecraft-protocol/pull/842 ; thanks @u9g 
either take the money in issuehunt of reinvest it in other issues ;)
