### ISSUE TITLE
How do I catch errors(ECONNRESET and Invalid credentials)

### ISSUE THREAD

**Issue by Footsiefat** [PrismarineJS/node-minecraft-protocol#720]
This is my current code: 
`var mineflayer = require('mineflayer');

var readline = require('readline-sync');

var bot = mineflayer.createBot({
  host: "", // optional
  port: 25565,       // optional
  username: "", // email and password are required only for
  password: "",          // online-mode=true servers
  version: false                 // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});

bot.once('spawn', () => {
  console.log('Successfully connected to server')
  bot.quit()
})

bot.once('kicked',(reason,loggedIn) => {
  if(loggedIn == false){
    console.log(reason)
  }
})
`

and sometimes when I run it too often it blocks me from logging in and throws the "Error: Invalid credentials. Invalid username or password." error. Is there anyway to stop me from getting this error, like not relogging in each time when joining a server? or at least catch it?

Sometimes if the server is laggy the bot gets disconnected with the error "ECONNRESET", is there anyway to catch this error?

**Comment by rom1504** [comment]
bot.on('error' but those 2 error are fatal errors, you need to reconnect
the bot in these cases

**Comment by Footsiefat** [comment]
How do I reconnect the bot automatically without making a new one? (because logging in too many times stops me fro  logging in)

Also I've found that bot.on('spawn' doesn't always work. It registers the log on event but it doesn't always register the spawn event

**Comment by Gjum** [comment]
you can use `prismarine-tokens` to avoid logging in too many times by caching the token:

```js
const tokens = require('prismarine-tokens')

const authConfig = {
	username: process.env.MC_USERNAME,
	password: process.env.MC_PASSWORD,
	tokensLocation: ".tokens.json",
	tokensDebug: true,
}

const { session } = await new Promise((res, rej) =>
		tokens.use(authConfig, (err, tokenParams) => {
			if (err) rej(err)
			else res(tokenParams)
		}))
if (!session || !session.accessToken) {
	throw new Error(`Failed to authenticate, probably rate limited`)
}

const mc = mcProto.createClient({ ...session, ...config })
```
