### ISSUE TITLE
unhandled exception when throwing fireworks at 1.15.2

### ISSUE THREAD

**Issue by duxeyo** [PrismarineJS/node-minecraft-protocol#723]
using slightly modified example proxy with a paperspigot server.
throwing fireworks causes this: https://pastebin.com/Lp26gahH

minecraft-protocol@1.12.0

**Comment by Karang** [comment]
Same error as https://github.com/PrismarineJS/mineflayer/issues/1002
The type must be a varint not a byte.

**Comment by rom1504** [comment]
fixed
