### ISSUE TITLE
Execute title command in node-minecraft-protocol server

### ISSUE THREAD

**Issue by xNextu** [PrismarineJS/node-minecraft-protocol#726]
Hello, I'm working on minecraft server using node-minecraft-protocol server and I have no clue how can I display title like this
![image](https://user-images.githubusercontent.com/51535369/83968678-27560e00-a8cb-11ea-9bca-66ea4dfc07cc.png)
Can anyone provide code example?

**Comment by roblabla** [comment]
https://wiki.vg/Protocol#Title
https://minecraft-data.prismarine.js.org/?v=20w14a&d=protocol#toClient_title

```js
bot.write('title', {
  action: 3, // Set how long the title will stay on the user's screen
  fadeIn: 10, // Fade in for 10 ticks (half a second)
  stay: 20 * 5, // Stay on screen for 80 ticks (5 seconds)
  fadeIn: 10, // Fade out for 10 ticks (half a second)
});
bot.write('title', {
  action: 0, // Sets the title
  text: '{"text": "Test"}' // This is a JSON chat message. More documentation at https://wiki.vg/Chat
});
```

**Comment by xNextu** [comment]
works, thanks a lot
