### ISSUE TITLE
Can't Connect To Some Servers

### ISSUE THREAD

**Issue by Gamer745** [PrismarineJS/node-minecraft-protocol#727]
There is a DDoS protection server for minecraft called TCPShield. If you try to direct connect to a domains ip it will give you an error. I fixed this by changing the tcp_dns.js to directly connect and not resolve the host.

This will work for most servers, however there seems the be a weird server. 

IP: convictmc.net

Pinging it in cmd just says it cant even resolve the host name but you are able to join in minecraft. The bot just gets ENOTFOUND when trying to connect. Im not sure what they are doing but is anyone able to join this server?

**Comment by rom1504** [comment]
Can you try again with the version I just released ? (1.12.1)

**Comment by Gamer745** [comment]
Seems to fix it, thanks
