### ISSUE TITLE
Changing server type

### ISSUE THREAD

**Issue by MeetPing** [PrismarineJS/node-minecraft-protocol#742]
**Is your feature request related to a problem? Please describe.** No

**Describe the solution you'd like** When press F3 you can see server type currently it says "null" but my idea is that i could like change that to a value in the options thing.

**Describe alternatives you've considered** Havent really considered alternatives

**Additional context** https://i.imgur.com/Z6XjzXf.png

**Comment by rom1504** [comment]
What code are you running ?

**Comment by MeetPing** [comment]
what do you mean?
this isnt a issue but a feature suggestion

**Comment by rom1504** [comment]
Ok this feature can already be implemented in code you can write using node-minecraft-protocol

**Comment by MeetPing** [comment]
ok how?

**Comment by MeetPing** [comment]
@rom1504

**Comment by rom1504** [comment]
Probably level type in this packet
https://minecraft-data.prismarine.js.org/?v=1.15.2&d=protocol#toClient_login

All packets are supported

**Comment by MeetPing** [comment]
i changed the leveltype but it dosent do anything

**Comment by rom1504** [comment]
Ok then the easiest way to find the right packet is to use the proxy with a
server that defines a "server type"

**Comment by MeetPing** [comment]
ok so how?

**Comment by MeetPing** [comment]
@rom1504 how?

**Comment by rom1504** [comment]
Check the proxy example, it has a readme

**Comment by MeetPing** [comment]
where?

**Comment by MeetPing** [comment]
Im confused on how this would like change the server type

**Comment by MeetPing** [comment]
Also how do i make it unlock a custom advancement?

**Comment by rom1504** [comment]
You need to identify the packets you need to send
One way is to read the doc.
Another way is to use the proxy to check what packets the vanilla server
send for the same thing
Yet another way is to use flying-squid

**Comment by MeetPing** [comment]
Arent you just going to tell me? i cant see anything in the docs

**Comment by rom1504** [comment]
I don't know all the features of the minecraft protocol that mojang changes every 6 months by heart no.
If you try a little bit with the instructions I gave you can find the information you need in 10 minutes and learn how to find more information for yourself
