### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-protocol#743]
Electron is missing the cipher we use because it doesn't use openssl

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/pull/735 related

**Comment by kukelekuuk** [comment]
Was just about to make an issue about this. A fallback implementation with aes-js or another library if the client doesn't contain the aes-128-cfb8 cipher would be preferred, personally.

**Comment by rom1504** [comment]
Done
