### ISSUE TITLE
Particle packet sliced

### ISSUE THREAD

**Issue by 837951602** [PrismarineJS/node-minecraft-protocol#756]
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.15.1
 - server: git-paper-134 (MC: 1.16.1) viaversion
 - node: v10.15.3

## Detailed description of a problem
Paricle packet contains field `Data` but isn't read.
```
Chunk size is 66 but only 50 was read ; partial packet : {"name":"world_particle
s","params":{"particleId":14,"longDistance":false,"x":-1599.5,"y":81,"z":-1599.5
,"offsetX":0.10000000149011612,"offsetY":0,"offsetZ":0.10000000149011612,"partic
leData":1,"particles":5}}; buffer :240000000e00c098fe00000000004054400000000000c
098fe00000000003dcccccd000000003dcccccd3f80000000000005000000003ec8c8c9000000003
f800000
```
when using as a proxy, this packet sending out crashes, as it's sliced

**Comment by rom1504** [comment]
now this is non crashing
