### ISSUE TITLE
Error given while using mc.ping(options,callback) function

### ISSUE THREAD

**Issue by AngeryFrog** [PrismarineJS/node-minecraft-protocol#760]
While using the mc.ping() function with the code given bellow, I am given an error "TypeError: cb is not a function" coming from client.js 
```javascript
const mc = require('minecraft-protocol')

module.exports = serverStatus = (ip, port) => {
    let serverInfo = mc.ping({
        host:ip,
        port:port || 25565
    });
};

serverStatus("hypixel.net");
```

**Comment by rom1504** [comment]
Yeah you have the answer in your title: you didn't provide a callback
function

**Comment by AngeryFrog** [comment]
ah my mistake, thank you for the help
