### ISSUE TITLE
server_world example doesn't work

### ISSUE THREAD

**Issue by Oreoezi** [PrismarineJS/node-minecraft-protocol#761]
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.16.0
 - server: vanilla/spigot/paper: minecraft-protocol
 - node: 14.10.0

## Detailed description of a problem

When logging in I get ```Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Failed to decode: No key name in MapLike[{}] {dimension:[{}]}```

Replacing
 ```dimensionCodec: { name: '', type: 'compound', value: { dimension: { type: 'list', value: { type: 'compound', value: [{ name: w }] } } } }``` 
with 
```dimensionCodec: { name: '', type: 'compound', value: { dimension: { type: 'list', value: { type: 'compound', value: [w] } } } }``` 
simply kicked me with the message "Disconnected".

Game output doesn't show anything either.

## Expected behavior
To log in on the server and see the chunk.

**Comment by rom1504** [comment]
This example is only for 1.16.1
You can adapt it to 1.16.0 by dumping the packet using the example proxy
(or debug mode with a nmp client)

You can also use flying-squid

**Comment by IMarkoMC** [comment]
The example does not work in 1.16.x for me lol.

**Comment by rom1504** [comment]
what code are you running?

**Comment by GroobleDierne** [comment]
Ha yes it's my fault I missed something when I updated the examples

**Comment by GroobleDierne** [comment]
For the moment use this file if you want to test https://github.com/PrismarineJS/node-minecraft-protocol/blob/ff9774a5f3258933c17f0844ac0e663cbda57f9b/examples/server_world/mc.js

**Comment by IMarkoMC** [comment]
It's working now, nice
