### ISSUE TITLE
Support for Minecraft 1.16.3

### ISSUE THREAD

**Issue by Trikolon** [PrismarineJS/node-minecraft-protocol#762]
I'm using the library for `mc.ping` and the request fails when I set the server version to `1.16.3`.

**Comment by kysadro** [comment]
Same problem here. When setting the version to 1.16.2 it works just fine but once i set it to 1.16.3 i get a `unsupported protocol version: 1.16.3` error and i'm trying to use Mineflayer to run MC commands on my MC server trough NodeJS so unless i downgrade my server to 1.16.2 (which will most definitely break things) i'm kinda stuck

**Comment by rom1504** [comment]
What did you try when updating the current PR on this ?
