### ISSUE TITLE
(Support) parse a packet

### ISSUE THREAD

**Issue by MrGeorgen** [PrismarineJS/node-minecraft-protocol#763]
I use the raw event on a client to receive packets . How can I parse a packet?
I know I could use the packet event, but I'm building a proxy and want to get more performance. I tried to use `mc.createDeserializer`, but I can't get it working

**Comment by rom1504** [comment]
using the raw event won't give you more performance, it still parses all packets

**Comment by MrGeorgen** [comment]
ok thanks
