### ISSUE TITLE
Failed to verify username

### ISSUE THREAD

**Issue by junebug12851** [PrismarineJS/node-minecraft-protocol#778]
I've copied and pasted your server example in README.md and changed `1.16` to `1.15.2`. It tries to connect but then gives me this error. I've looked at your FAQ and didn't see a solution.

![image](https://user-images.githubusercontent.com/1305564/98902464-c9ce7a80-2483-11eb-9360-175859364660.png)

**Comment by owenflaherty** [comment]
I can reproduce this on 1.16.4 and 1.8.9

**Comment by xy-ko** [comment]
If you don't require online mode then you can switch online-mode to false.

**Comment by junebug12851** [comment]
So the proposed answer is to set online-mode to false if your technically able to? I understand online-mode is optional here but for most other servers it's mandatory for a lot of reasons. That isn't a very good suggestion to the problem, even as a temporary fix.

**Comment by rom1504** [comment]
Can you show the code you ran exactly?
Online mode definitely works if you're connecting with the client with a mojang account and your code is correct

**Comment by junebug12851** [comment]
```js
var mc = require('minecraft-protocol');

var server = mc.createServer({
  'online-mode': true,   // optional
  encryption: true,      // optional
  host: '0.0.0.0',       // optional
  port: 25565,           // optional
  version: '1.15.2'
});

const mcData = require('minecraft-data')(server.version)

server.on('login', function(client) {
  
  let loginPacket = mcData.loginPacket

  client.write('login', {
    entityId: client.id,
    isHardcore: false,
    gameMode: 0,
    previousGameMode: 255,
    worldNames: loginPacket.worldNames,
    dimensionCodec: loginPacket.dimensionCodec,
    dimension: loginPacket.dimension,
    worldName: 'minecraft:overworld',
    hashedSeed: [0, 0],
    maxPlayers: server.maxPlayers,
    viewDistance: 10,
    reducedDebugInfo: false,
    enableRespawnScreen: true,
    isDebug: false,
    isFlat: false
  });

  client.write('position', {
    x: 0,
    y: 1.62,
    z: 0,
    yaw: 0,
    pitch: 0,
    flags: 0x00
  });

  var msg = {
    translate: 'chat.type.announcement',
    "with": [
      'Server',
      'Hello, world!'
    ]
  };

  client.write("chat", { message: JSON.stringify(msg), position: 0, sender: '0' });
});

```
