### ISSUE TITLE
The string dilemna

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#78]
Right now, we have two string types, string and ustring. The former is limited to 255 characters, while the other isn't limited at all. The whole problem is, minecraft limits the length of certain fields to a certain amount of characters. Generally speaking, the limit is 255 characters, but that is not always the case.

Unfortunately, this has caused many issues in the library in the past, where a field would be marked as a "string" when it could receive input longer than 255 characters.  To make matters worse, wiki.vg doesn't really give much insight in which fields are limited in length.

I suggest we simply remove the limit from the packets entirely. It should be the user's responsibility to make sure the other side doesn't give unwanted input, and thus sanitize the input.

**Comment by rom1504** [comment]
It seems all client->server string are limited.
A fix to this would be adding a "length" typearg to the string type and having it default to infinity (useful for server->client string fields)
