### ISSUE TITLE
blockId undefined on the client althought a valid value is sent

### ISSUE THREAD

**Issue by MrGeorgen** [PrismarineJS/node-minecraft-protocol#783]
[x ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.19.0
 - server: paper 1.12.2
 - node: 14.13.1

## Detailed description of a problem
If I send a "set_slot" packet which looks this:
```
{
  windowId: 0,
  slot: 37,
  item: { blockId: 6, itemCount: 2, itemDamage: 0, nbtData: undefined }
}
```
The client says
```
Connection Lost
TypeError: Serialization errorfor play.toClient : Sizeof error for undefined : Cannot read property 'blockId' of undefined
```

## Current code
[most relevant code](https://github.com/themoonisacheese/2bored2wait/blob/inventory_cache/cachePackets.js) 

## Expected behavior
The client stays connects and shows the correct item in the inventory.

**Comment by DeltaEvo** [comment]
Are you really sending a set_slot packet with the content that you described ?

In the code that you linked
```js
var inventory = [45];
```
Create un array of size 1 with 45 as first value

If you want to create an array of size 45 you can do
```js
const inventory = Array.from({ length: 45 })
```
So in your code if you don't receive a set_slot for the slot 0 you will call

```js
proxyClient.write("set_slot", 45);
```

And
```js
(45).item === undefined
```

So this can explain the `Cannot read property 'blockId' of undefined`

**Comment by MrGeorgen** [comment]
> Are you really sending a set_slot packet with the content that you described ?
> 
> In the code that you linked
> 
> ```js
> var inventory = [45];
> ```
> 
> Create un array of size 1 with 45 as first value
> 
> If you want to create an array of size 45 you can do
> 
> ```js
> const inventory = Array.from({ length: 45 })
> ```
> 
> So in your code if you don't receive a set_slot for the slot 0 you will call
> 
> ```js
> proxyClient.write("set_slot", 45);
> ```
> 
> And
> 
> ```js
> (45).item === undefined
> ```
> 
> So this can explain the `Cannot read property 'blockId' of undefined`

yeah I wanted to create an array of the size 45. Sometimes I make really dumb mistakes xd. thanks a lot for your help
