### ISSUE TITLE
NMP hangs when connecting to a Fabric server with the Fabric API mod installed

### ISSUE THREAD

**Issue by ph0t0shop** [PrismarineJS/node-minecraft-protocol#794]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: any
 - server: fabricmc
 - node: any

## Detailed description of a problem
NMP hangs when connecting to a Fabric server with the Fabric API mod installed

## Expected behavior
The bot  joins successfully

## Additional context
This is just a dummy issue report. The fix is already known, when I get the time and it hasn't been fixed yet I'll open a PR for it.

**Comment by Karang** [comment]
The fix:
```js
targetClient.on('login_plugin_request', (packet) => {
  targetClient.write('login_plugin_response', {messageId: packet.messageId})
})
```
