### ISSUE TITLE
high severity vulnerability in axios

### ISSUE THREAD

**Issue by MrGeorgen** [PrismarineJS/node-minecraft-protocol#803]
themoonisacheese/2bored2wait#182

updating axios should fix it

**Comment by Karang** [comment]
yes, the problem is we don't depend directly on axios, but use https://github.com/XboxReplay/xboxlive-auth which does

**Comment by Karang** [comment]
https://github.com/XboxReplay/xboxlive-auth/pull/10 seems like it will be fixed soon

**Comment by MrGeorgen** [comment]
the pr is merged so only we have to update the dependencies

**Comment by Kashalls** [comment]
This will be fixed in PR https://github.com/PrismarineJS/node-minecraft-protocol/pull/806 .
