### ISSUE TITLE
How can I get entities movement ?

### ISSUE THREAD

**Issue by tanguyprvst** [PrismarineJS/node-minecraft-protocol#812]
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.22.0
 - server: spigot
 - node: 12.19.0

## Detailed description of a problem
Hello,
I'm trying to retrieve the movements of all players and my entity but I can't find which listener to use.
Thank you in advance!

**Comment by rom1504** [comment]
use mineflayer for this or check https://wiki.vg/Protocol
