### ISSUE TITLE
Importing worlds.

### ISSUE THREAD

**Issue by spiderlord202** [PrismarineJS/node-minecraft-protocol#817]
I have been searching all over the internet for a way to host a Minecraft on node.js that I can import Minecraft worlds like the ones utilized in the popular spigot/bukkit plugin multiverse (different overworlds, nethers, etc) from my previous host into and just change data and I found no way of doing so.  I would like that you can specify the location of a directory where the world folders are stored and if possible the plugin folder too. If you cannot do world folders then try plugin folders.

**Comment by spiderlord202** [comment]
If there is a way of importing worlds please tell me.

**Comment by extremeheat** [comment]
Do you want to host a server? You’re looking for https://github.com/PrismarineJS/flying-squid. This is just a protocol library for other projects to use to communicate with Minecraft.

**Comment by spiderlord202** [comment]
Ok. I will suggest this in flying-squid
