### ISSUE TITLE
Client ID is missing from typings.

### ISSUE THREAD

**Issue by steven-peralta** [PrismarineJS/node-minecraft-protocol#818]
When trying to reference `Client.id` in a Typescript project, you get the error `Property 'id' does not exist on type 'Client'.` because it is missing from the Client typings. There should be an optional `id` property here representing the client id.

**Comment by steven-peralta** [comment]
also the key type of ClientsMap is a string which doesn't make sense because the id of the client is always set to be an incrementation of `nextId` in `Server#listen`

**Comment by u9g** [comment]
can be closed, added in #836
