### ISSUE TITLE
unable to serialize object with empty string

### ISSUE THREAD

**Issue by u9g** [PrismarineJS/node-minecraft-protocol#820]
[ ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: newest
 - server: (vanilla)/spigot/paper 1.16.5
 - node: v14.8.0

## Detailed description of a problem
client.write is unable to send a packet that is just a property = empty string

## Current code
```js
client.write('name_item', { name: '' })
```

## Expected behavior
The packet to be sent with an empty field

## Additional context
It doesn't send the packet at all.

**Comment by Karang** [comment]
I just tested it in the benchmark test of this package and it works properly (i can PR the test if needed).

Here is how it gets serialized:
```
{
  data: { name: 'name_item', params: { name: '' } },
  metadata: { size: 2 },
  buffer: <Buffer 20 00>
}
```

Of course, the packet is only defined for versions >= 1.13 it doesn't exist in protocol for earlier versions.
