### ISSUE TITLE
Beginning 1.17 Support

### ISSUE THREAD

**Issue by KaidenP** [PrismarineJS/node-minecraft-protocol#823]
Begging 1.17 support thread:

I'm going to start looking into supporting the newest snapshots/1.17. Might be a little over my head but the least I can do is try. At the least it should mean some of the work is already done. [~I'll link to my fork when I start working on it.~ Iron-Watt/node-minecraft-protocol](https://github.com/IronWatt/node-minecraft-protocol)

This is a continuation of https://github.com/PrismarineJS/mineflayer/issues/1730

As previously mentioned, the following are useful link to help in this endeavor:

> A lot is needed, especially since they changed a lot of things. Stuff that should be updated in order:
> 
> * minecraft-data https://github.com/PrismarineJS/minecraft-data/blob/master/doc/add-data-new-version.md
> * prismarine-chunk
> * prismarine-world
> * mineflayer
> 
> We don't plan to support snapshot, so we'll wait for the 1.17 release, but feel free to start working on it.

> https://github.com/PrismarineJS/prismarine-contribute#updating-to-new-minecraft-versions that's the process to update prismarinejs stuff in general for a new version
> 
> if you want 1.17 to be supported earlier, you could start by updating protocol.json for the latest snapshot using https://wiki.vg/Pre-release_protocol as a reference
> 
> We sometimes support snapshots in minecraft-protocol, but usually not in mineflayer

**Comment by rom1504** [comment]
cool

protocol goes there https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc
