### ISSUE TITLE
Unable to set end dimension for client

### ISSUE THREAD

**Issue by MrZillaGold** [PrismarineJS/node-minecraft-protocol#834]
## Versions
 - minecraft-protocol: 1.24.1
 - server: minecraft-protocol createServer
 - node: 14.16.0

## Detailed description of a problem
When the client enters the server, it is disconnected with an error: 
![image](https://user-images.githubusercontent.com/42776347/112729142-66e30900-8f76-11eb-9cea-a36431c3327b.png)

## Current code
```js
const lobby = createServer({
  'online-mode': true,
  host: '0.0.0.0',
  port: 25565,
  version: '1.16.5'
});

lobby.on("login", (client) => {
    client.write("login", {
        entityId: client.id,
        isHardcore: true,
        gameMode: 0,
        previousGameMode: 255,
        worldNames: loginPacket.worldNames,
        dimensionCodec: loginPacket.dimensionCodec,
        dimension: "minecraft:the_end",
        worldName: "minecraft:the_end",
        hashedSeed: [0, 0],
        viewDistance: 10,
        reducedDebugInfo: false,
        enableRespawnScreen: true,
        isDebug: false,
        isFlat: false
    });

    client.write("position", {
        x: 0,
        y: 64,
        z: 0,
        yaw: 0,
        pitch: 0,
        flags: 0x00
    });
});
```

**Comment by u9g** [comment]
dimension isn't a string its a nbt compound, see: https://wiki.vg/Protocol#Join_Game down below the packet description it describes what is expected for dimension

**Comment by MrZillaGold** [comment]
I didn’t pay attention to it. Thanks!
