### ISSUE TITLE
Support 1.17.1

### ISSUE THREAD

**Issue by Cwickks** [PrismarineJS/node-minecraft-protocol#874]
Error: unsupported/unknown protocol version: 756, update minecraft-data

**Comment by krystlerc** [comment]
Same problem when using 1.17.1. I was using mcserversleeper by vincs. tutorial said to check the version compatibility here.

**Comment by Kashalls** [comment]
We only have support for 755 (1.17). As 1.17.1 is 756 we need someone to update Minecraft data first.

**Comment by Cwickks** [comment]
![image](https://user-images.githubusercontent.com/69566792/126121871-eff6ac66-055b-4050-a874-56bb11e43ce3.png)

**Comment by rom1504** [comment]
this is done
