### ISSUE TITLE
Chunk Decompression error on 1.8 client (MacOS)

### ISSUE THREAD

**Issue by GhqstMC** [PrismarineJS/node-minecraft-protocol#885]
[X] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.25.0
 - server: Hypixel spigot 1.8.9 (protocol 47)
 - node: 16.5.0/14.17.4

## Detailed description of a problem
Multiple chunk decompression errors occur randomly causing chunks to be missing. Example error is viewable here: https://hastebin.com/raw/oruyucociw

## Current code
```js
mc.createClient({
  host: "mc.hypixel.net",
  port: 25565,
  version: '1.8',
  hideErrors: false,
  username: "email@example.com", // set to example credentials
  password: "12345678", // set to example credentials
  auth: 'mojang' // set to example credentials
});
```

## Expected behavior
No chunk decompression errors

## Additional context
This only seems to happen on Mac OS and not Windows or Linux. Using vercel/pkg at the moment but will test without it soon

**Comment by rom1504** [comment]
try to change your zlib version

**Comment by rom1504** [comment]
try to not use vercel/pkg

**Comment by GhqstMC** [comment]
The issue appears to be with vercel/pkg 5.3.0+ breaking zlib on OS X. Reverting to 5.2.1 fixed this issue.
