### ISSUE TITLE
Investigate race condition around state changes

### ISSUE THREAD

**Issue by Eluinhost** [PrismarineJS/node-minecraft-protocol#90]
Connecting to a created server with a regular minecraft (1.7.9) throws an error about the UUID being 0. I think it has to do with this note:

'As of 1.7.6 all UUIDs used in the protocol now contain '-'. The session server still returns them without'

I did the following change to fix for my particular use case but being new to nodejs and this project too I have no idea of the 'proper' fix for this

https://github.com/Eluinhost/node-minecraft-protocol/commit/16681cf6dae3f80a0ac1019520d5fe98fc9b6b96

On the same kind of note, when I go to connect a lot of the time I get a ClassCastException 'bll cannot be cast to fv'. I don't know how to fix this one but there is a mojang ticket here: https://bugs.mojang.com/browse/MC-42286 that says the Keep Alive packet may be being sent too early causing Minecraft to choke

**Comment by rom1504** [comment]
If this is still relevant I guess it should be in a PR, @Eluinhost ?

**Comment by roblabla** [comment]
What we seriously need to do is process.nextTick() the event emitted when changing state. This probably would avoid a _lot_ of race conditions when doing code like

```client.on('state', function(newstate) {
  if (newstate === states.PLAY)
    client.write(/*stuff*/);
});
```

The above crashes the server due to the server not being in PLAY state yet. Using process.nextTick seems to fix the issue.

**Comment by rom1504** [comment]
hmm would this happened to be solved now that #157 is solved ?

**Comment by roblabla** [comment]
Don't think so, this is a race condition from the notchian stuff that we have to manually work around ^^

**Comment by rom1504** [comment]
The title of that issue should be changed. I'm not sure exactly what the new title would be ("Fix race condition when changing state" maybe ?), but the current one doesn't describe the problem we're trying to solve here, and it's confusing.

**Comment by rom1504** [comment]
That kind of thing should not happen unless we have an async read/write/sizeOf (see https://github.com/roblabla/ProtoDef/issues/49 and https://github.com/PrismarineJS/node-minecraft-protocol/pull/309#issuecomment-166793030 )

I believe it doesn't happen in current nmp, so closing this. We can always reopen if there are new problems related to this.
