### ISSUE TITLE
Deprecate/Remove onlineModeExceptions ?

### ISSUE THREAD

**Issue by DeltaEvo** [PrismarineJS/node-minecraft-protocol#906]
I'm interested in avoiding to generate the RSA keypair when `online-mode` is `false` to speed up startup time

However `onlineModeExceptions` seems to make it possible to enable encryption for some usernames with `online-mode` to `false`

I see two solution for that:
- Remove `onlineModeExceptions`
- Lazily generate the RSA keypair

As I don't see an use case of `onlineModeExceptions` :thinking:  I'm tempted to choose the first solution, what do you think ?

**Comment by rom1504** [comment]
The use case of onlineModeExceptions is to make an offline server while having a few people that are authenticated and hence can be trusted (for example admins), it's a pretty common use case

To achieve your goal, why not avoid generating the RSA keypair if onlineModeExceptions is empty ?

did you measure what time it takes to generate this RSA keypar ?

**Comment by DeltaEvo** [comment]
> The use case of onlineModeExceptions is to make an offline server while having a few people that are authenticated and hence can be trusted (for example admins), it's a pretty common use case

:thinking:  Ok, seems fair

> To achieve your goal, why not avoid generating the RSA keypair if onlineModeExceptions is empty ?

Because it is not passed as an options and is not immutable :(, this mean that the values are assigned after the creation of the server

> did you measure what time it takes to generate this RSA keypar ?

Yes on my pc, it goes from 500ms (with only the server running) up to 3 second (with a minecraft client running)

**Comment by rom1504** [comment]
> Because it is not passed as an options and is not immutable :(, this mean that the values are assigned after the creation of the server

you could make the onlineModeExceptions object a  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy and enable rsa keypair generation only when (if) values are added in it

**Comment by rom1504** [comment]
why did you close it?
what I said seems like a valid solution, no ?

**Comment by DeltaEvo** [comment]
Yes it is :smiley: so the question of deprecating onlineModeException for me is closed, I will follow up with a pull request for the RSA keypair

**Comment by rom1504** [comment]
thanks for the pr
