### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by foxodever** [PrismarineJS/node-minecraft-protocol#912]
![image](https://user-images.githubusercontent.com/52624723/138247120-8981381f-2e87-4099-a3c3-112d7ae92df6.png)
With code ^

![image](https://user-images.githubusercontent.com/52624723/138247129-e0a9f650-4e43-4570-a88b-fbb48592799a.png)
With password ^

**Comment by extremeheat** [comment]
Make sure your account date of birth is >= 18 years old. Will be fixed with prismarine-auth
