### ISSUE TITLE
Tab complete not working

### ISSUE THREAD

**Issue by Lucaslah** [PrismarineJS/node-minecraft-protocol#935]
- [x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.29.0
 - server: node-minecraft-protocol
 - node: 14.9.0

## Detailed description of a problem
No commands options show up on my client where I press `/`

## Current code
```js
server.on("login", async (client) => {
    client.on("tab_complete", (data) => {
        console.log(data);

        client.write("tab_complete", {
            matches: ["exit", "disconnect"]
        });
    });
});
```

## Expected behavior
I should see command options, or what do I do to set command options?
There are no errors on the client or server

**Comment by u9g** [comment]
the commands that show up when you press / in the box of commands to fill in the box above the chat box come from the https://wiki.vg/Protocol#Declare_Commands packet, not the tab complete packet

**Comment by Lucaslah** [comment]
Oh alright, I guess I missed that.

Do you know the name of the packet?

**Comment by Lucaslah** [comment]
Well I’m guessing it’s `declare_commands`, but now I’m not sure what data to send.

**Comment by Lucaslah** [comment]
```javascript
client.write("declare_commands" ...What to put here)
```

What do I need to sent with this packet

**Comment by Lucaslah** [comment]
I figured it out
