### ISSUE TITLE
Occasional IndexOutOfBoundsException on spawn_entity

### ISSUE THREAD

**Issue by Robbilie** [PrismarineJS/node-minecraft-protocol#947]
[ x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: ^1.29.1
 - server: vanilla 1.18.1
 - node: v16.8.0

## Detailed description of a problem
I am currently working on some server reconnection logic where a client switches servers. This library is acting as a proxy and switches from one client to another. This seems to work quite well and reliably. Occasionally after switching i receive the following log output:

```
Chunk size is 188 but only 56 was read ; partial packet : {"name":"spawn_entity","params":{"entityId":185,"objectUUID":"7b227472-616e-736c-6174-65223a226469","type":115,"x":9.489665354112813e+170,"y":1.1935881242136542e+190,"z":2.262901882749459e+180,"pitch":119,"yaw":105,"objectData":1952981562,"velocityX":23330,"velocityY":18798,"velocityZ":29797}}; buffer :00b9017b227472616e736c617465223a22646973636f6e6e6563742e67656e65726963526561736f6e222c2277697468223a5b22496e7465726e616c20457863657074696f6e3a20696f2e6e657474792e68616e646c65722e636f6465632e4465636f646572457863657074696f6e3a206a6176612e6c616e672e496e6465784f75744f66426f756e6473457863657074696f6e3a20496e646578203137206f7574206f6620626f756e647320666f72206c656e6774682033225d7d
```

the spawn_entity event is triggered, the clients connection to the real minecraft server is ended though and the server logs present the following:

```
[22:30:27] [Server thread/INFO]: Robbilie lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 17 out of bounds for length 3
[22:30:27] [Server thread/INFO]: Robbilie left the game
[22:30:27] [Server thread/WARN]: handleDisconnection() called twice
```

It is always the "same" error on both node and the server, in that the type stays 115…

I am not yet sure which packet sent to the server causes the index out of bounds though

**Comment by nickelpro** [comment]
115 isn't a valid entity type, so something more complicated is going on here

**Comment by Robbilie** [comment]
yeah it feels like the parser tried to parse garbage and this came out…
i think when switching servers the client sending movement packets to the new server too early was the issue, i added some pause and ive not been able to reproduce it since
