### ISSUE TITLE
Entity Effect : Show Icon

### ISSUE THREAD

**Issue by Robbilie** [PrismarineJS/node-minecraft-protocol#951]
**Is your feature request related to a problem? Please describe.**
https://wiki.vg/Protocol#Entity_Effect
Currently there seems to be a flag to hide the icon of an effect which doesnt seem possible on the entity_effect object.

**Describe the solution you'd like**
Analog to the show/hide particles field a show/hide icon field should be added.

**Describe alternatives you've considered**
None

**Additional context**
Maybe having a flags field that is not precisely named would be a more dynamic option although possibly harder to understand…

**Comment by u9g** [comment]
https://minecraft-data.prismarine.js.org/?v=1.18&d=protocol#toClient_entity_effect

`hideParticles` is the flag field. I agree the name is bad though.

**Comment by Robbilie** [comment]
hm yeah especially if someone thinks hideParticles === 1 is like true and that actually makes it appear as if it was a beacon effect :D

thanks, couldve figured that one out myself i guess, any chance that one could be renamed to flags then in an upcoming release or such?

**Comment by u9g** [comment]
Uh, throw an issue up on mcdata issues tracker, that's a better place for someone to find it.

**Comment by Robbilie** [comment]
done, thanks for the note
