### ISSUE TITLE
Unexpected token '.' on require

### ISSUE THREAD

**Issue by pikachub2005** [PrismarineJS/node-minecraft-protocol#954]
- [x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.30.0
 - node: 12.22.6

## Detailed description of a problem
```
/home/runner/Prismarinejs-test/node_modules/prismarine-nbt/nbt.js:168
    const type = value?.type ?? 'end'
                       ^

SyntaxError: Unexpected token '.'
```
SyntaxError when I require it

## Current code
```js
var mc = require('minecraft-protocol');
```

## Expected behavior
There shouldn't be an error

## Additional context
I'm using [Replit](https://replit.com) but I don't know if that matters

**Comment by nickelpro** [comment]
Node 6 is unsupported, minimum version is node 14. The real bug here is the package.json is out of date.

**Comment by pikachub2005** [comment]
k

**Comment by pikachub2005** [comment]
> Node 6 is unsupported, minimum version is node 14. The real bug here is the package.json is out of date.

Whoops, I put my npm version. My node version is 12.22.6, but I guess that still doesn't work ;-;
