### ISSUE TITLE
Support 1.8

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/node-minecraft-protocol#96]
Just realized 1.8 came out. It's that time of the year I guess. Time to update the protocol definition for 1.8.

~~With this, I thought I might try to tackle #65 using roblabla-sauce awesomeness.~~

Turns out, #65 will come later. 

TODO : 

- [x] Update the packet definitions (almost done, just missing the slot (de)serializer).
- [x] Update the tests
- [x] Add new compression system... Mojang why did you change the pipeline again :unamused:
- [x] Smoke test with a full protocol reserializer proxy (decodes every packet, and recodes them, sitting between the client and the server).

**Comment by JavaPortal** [comment]
@roblabla

Awesome news. I would love to help, but raw networking isn't something I'm really good at :/ Thanks for the awesome work

**Comment by roblabla** [comment]
@wtfaremyinitials we need to figure out what packet is wrong. http://wiki.vg/Debugging should be a great help.

**Comment by roblabla** [comment]
@wtfaremyinitials I just reviewed your code for compression aaand it's wrong (probably should have done that earlier). You should read through the [wiki.vg packet format]|(http://wiki.vg/Protocol#Packet_format), you'll see that even if [```buffer.length > this.compressionThreshold```](https://github.com/wtfaremyinitials/node-minecraft-protocol/blob/675d358dec51d1d3e56068768062881c51b681d1/lib/client.js#L169), you should still pack the packet in the new format, just with dataLength to 0. There are a couple other mistakes, such as giving the wrong value to [packetLength](https://github.com/wtfaremyinitials/node-minecraft-protocol/blob/675d358dec51d1d3e56068768062881c51b681d1/lib/protocol.js#L1295). It's supposed to be the size of the COMPRESSED packet, whereas you're always giving it the size of the uncompressed packet. 

I'm going to be forking your work and try to fix it.

**Comment by roblabla** [comment]
Alright, I'm almost done. I got the client not to crash, however the client stays stuck at Logging In, probably because we never send a "Set Compression" packet. Going to fix this, and then open a PR. Huge thanks to you @wtfaremyinitials

**Comment by JavaPortal** [comment]
Sounds awesome! And happy new year to you too!

**Comment by wtfaremyinitials** [comment]
Couple of things:

1. Do you still want me to send a PR @roblabla? or did you just manually pull from my fork?

2. I don't think I ever implemented (read/write)Position because I found a potential issue with it. When trying to encode something in a 64 bit int/long, we are getting to numbers so high that the fact that all numbers in JS are floats becomes a problem. I assume that's why writeLong currently takes an array of two numbers. I'm not sure how we should go about fixing that.

Also, Happy New Year to both of you!

**Comment by roblabla** [comment]
@wtfaremyinitials 

1. Well right now I kind of just locally pulled your changes. I'll push my current version for you to see.

2. oh... fuck. You're right. Those are the days I hate javascript. Well, I guess this means we'll have to split it into two ints. Here's what I'm thinking

```javascript
function readPosition(buffer, offset) {
  var longVal = readLong(buffer, offset).value; // I wish I could do destructuring...
  var x = longVal[0] >> 6;
  var y = ((longVal[0] & 3F) << 6) | ((longVal[1] & 0xFC000000) >> 26);
  var z = longVal[1] & 0x3FFFFFF;
  return {
    value: { x: x, y: y, z: z },
    size: 8
  };
}
```

FunFact : calc.exe on windows can be pretty handy to figure out those binary operations...

**Comment by wtfaremyinitials** [comment]
@roblabla All of those binary operators are completely over my head. I need to learn them sometime.

**Comment by wtfaremyinitials** [comment]
@roblabla Just noticed your messages about the compression packet issues. I guess I should have read wiki.vg more closely :stuck_out_tongue:

**Comment by roblabla** [comment]
For some reason I fail to understand, the client no longer logs in. I am guessing you need to actually send the client a map for it to actually display anything. This is slightly annoying...

**Comment by wtfaremyinitials** [comment]
@roblabla Would you mind pushing your changes? I'd like to try to take a stab at getting it fully working.

**Comment by roblabla** [comment]
And it works ! Hours of debugging, just to find out that it was bugging because the context of "this" is different [there](https://github.com/wtfaremyinitials/node-minecraft-protocol/blob/packets-1.8/lib/client.js#L165).

Anyway, going to push to my branch and open a PR for reviewing. I'd appreciate it if you guys could use it and stress-test it.

**Comment by wtfaremyinitials** [comment]
Woo! Sorry, I thought I had replaced all the instances of `this` with `that`. Glad to see it's working now.

**Comment by wtfaremyinitials** [comment]
Well yeah, about the completely screwing up compression originally @roblabla.

![](http://i.imgur.com/ibEgFUV.png)

**Comment by roblabla** [comment]
Haha yeah I read that. It wasn't too off-the-mark though. It's just the fields inside the compression that needed to have their values changed a little bit.

**Comment by jerwuqu** [comment]
I would much like to see this happen. Is there any interest in continuing with this project to support the latest version?

**Comment by roblabla** [comment]
see #108 . If I manage to figure out why the thing leaks like crazy, then it can be pushed and called done.

**Comment by roblabla** [comment]
Done
