### ISSUE TITLE
Docs | Certain stuff inside the docs

### ISSUE THREAD

**Issue by NotZer0Two** [PrismarineJS/node-minecraft-protocol#966]
Reading the docs i found many part saying u8, f32, i8, i32 and many other what this Field Type mean thanks

**Comment by rom1504** [comment]
Check protodef doc

**Comment by NotZer0Two** [comment]
yes but what i need to insert sort or where i can found what that mean?

**Comment by NotZer0Two** [comment]
because inside the docs nothing its explained about what that mean

**Comment by NotZer0Two** [comment]
oh found it 

https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes/numeric.md
