### ISSUE TITLE
Login packet broken in 1.18.2

### ISSUE THREAD

**Issue by matthi4s** [PrismarineJS/node-minecraft-protocol#969]
[ X ] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.18.2
 - node: v14.19.0

## Detailed description of a problem
Running the [`examples/server/server.js`](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/server/server.js) and connecting with a Vanilla 1.18.2 client results in a disconnect like this:

![Screenshot_20220307_121113](https://user-images.githubusercontent.com/8943286/157020853-e5a02caa-a8f2-440c-b8e9-5553f948d58e.png)

## Expected behavior
The login should work as expected and not produce that error.

## Additional context

- <=1.18.1 works.
- The same problem happened using other examples or our own code. 
- Removing all other packets sent by the server except the login packet results in the same error.

**Comment by darksunlight** [comment]
Reproducible
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/78575721/157099236-a5f3a660-7a08-4bf5-b690-c27f5f59e87a.png">

**Comment by darksunlight** [comment]
Probably some changes in the dimension codec in 1.18.2 that were not reflected in the latest minecraft-data update.

**Comment by nickelpro** [comment]
Didn't bump the mcd example packet at all. Someone just needs to capture and PR a vanilla login packet.

**Comment by nickelpro** [comment]
Although I'll take this opportunity to point out that blindly replaying a packet capture is also wrong. We're actively lying to the client about the server's configuration. Server providers should have some mechanism to _construct_ these packets, not just say "I am a default vanilla server"

**Comment by rom1504** [comment]
yes

**Comment by darksunlight** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/78575721/157135827-306ea11e-2864-41d1-b10d-0be6d317d72b.png">

**Comment by darksunlight** [comment]
https://github.com/PrismarineJS/minecraft-data/pull/523

**Comment by BasToTheMax** [comment]
Having the same issue ( 1.20.1 ). Any fix?

**Comment by PondWader** [comment]
> Having the same issue ( 1.20.1 ). Any fix?

The 1.20 data does not contain an up to date login packet. You can dump the packet yourself and PR it.
