### ISSUE TITLE
`minecraft-protocol` increases `node_modules` size by more than 200%

### ISSUE THREAD

**Issue by jojomatik** [PrismarineJS/node-minecraft-protocol#978]
[x] The [FAQ](https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - minecraft-protocol: 1.30.0
 - server: vanilla/spigot/paper n.a.
 - node: 16

## Detailed description of a problem
The library includes a lot of dependencies, it increased the size of `/node_modules` by more than 200% and my docker image by about 50%. I believe this might be a bug (e.g. dev-dependencies included as prod-dependencies).

See also jojomatik/blockcluster#390. I've taken a look at the compressed sizes on dockerhub and have narrowed the range of commits down to the addition of this library to my project (even though the difference on dockerhub is pretty small in the compressed sizes).

Would you be able to take a look at all dependencies? Which ones are strictly necessary? Which dependencies would suffice as dev-dependencies? Would it be possible to make some dependencies optional, based on the protocol used?

## Current code
n.a.

## Expected behavior
`/node_modules` and docker image don't increase dramatically.

## Additional context
Before:
![image](https://user-images.githubusercontent.com/66277921/162574289-74695db8-d78a-4855-b461-38e6e747b10f.png)

![image](https://user-images.githubusercontent.com/66277921/162574320-9acc623e-e76c-47b2-a589-a33b17a85c54.png)

After:
![image](https://user-images.githubusercontent.com/66277921/162574276-b5b08a02-bb2f-4c59-bde6-c03436ba8da9.png)

![image](https://user-images.githubusercontent.com/66277921/162574312-0e6cd3ac-7288-4efc-94e0-f150c3f39fad.png)

**Comment by rom1504** [comment]
We have a single dependency that uses space: minecraft data. It uses 70MB when uncompressed, 4MB when compressed

What problem are you trying to solve?

**Comment by jojomatik** [comment]
I only use a very small portion of this library: I create a mock server that listens for a connection and starts the "real" minecraft server as soon as a client tries to connect. 

If `minecraft-data` really uses that much space, that is really unfortunate for my use-case, as I'd believe that I only use a very small part of that data. Would there be a possibility to only include the relevant parts?

I've tried to decrease the docker image size in the past to fasten download times especially for automatic re-deployment to minimize the downtime. Adding this much data is really unfortunate in that case.

**Comment by rom1504** [comment]
docker images are compressed by default, so this shouldn't cause you any issue

**Comment by jojomatik** [comment]
Yeah, that seems to be true for download times. 

They seem to get uncompressed as soon as they are downloaded, but that shouldn't be too much of an issue then the more I think about i. If I remove all unused/ old images and never have to run a lot of different versions of my software at the same time, those 70MB should not cause any issues.

Thanks for the fast response and clarification :)

**Comment by rom1504** [comment]
yeah, you're not the first one to point this out though
we could consider keeping the files as compressed in the npm package and only uncompressing at run time 
https://github.com/PrismarineJS/node-minecraft-data/issues/185 here's an issue to track that idea
